// Auto-generated flag index from amckenna41/iso3166-flag-icons
// Source: iso3166-2-icons CSS — maps ISO 3166-2 codes to their flag file extension
// CDN: https://cdn.jsdelivr.net/gh/amckenna41/iso3166-flags@main/iso3166-2-flags/

// Non-SVG extension overrides (SVG is the default for unlisted codes)
const NON_SVG_EXT: Record<string, string> = {
  "AE-DU": "png",
  "AE-FU": "svg.png",
  "AE-RK": "png",
  "AE-SH": "png",
  "AL-04": "png",
  "AL-05": "png",
  "AL-08": "png",
  "AL-09": "png",
  "AL-10": "png",
  "AM-GR": "jpeg",
  "AM-KT": "jpeg",
  "AM-LO": "gif",
  "AM-VD": "png",
  "AZ-BA": "png",
  "AZ-SA": "jpeg",
  "AZ-SM": "png",
  "AZ-XA": "png",
  "AZ-YE": "jpg",
  "BA-BRC": "png",
  "BANDERA-DE-LA-PROVINCIA-BIOKO-DEL-NORTE": "png",
  "BANDERA-DE-LA-PROVINCIA-BIOKO-DEL-SUR": "png",
  "BANDERA-DE-LA-PROVINCIA-CENTRO-SUR": "png",
  "BANDERA-DE-LA-PROVINCIA-KIE-NTEM": "png",
  "BANDERA-DE-LA-PROVINCIA-LITORAL": "png",
  "BANDERA-DE-LA-PROVINCIA-WELE-NZAS": "png",
  "BEQUIA": "gif",
  "BR-RJ": "png",
  "BW-GA": "gif",
  "CD-BC": "png",
  "CD-BU": "png",
  "CD-HK": "png",
  "CD-HU": "png",
  "CD-IT": "png",
  "CD-KC": "png",
  "CD-KE": "png",
  "CD-KL": "png",
  "CD-KS": "png",
  "CD-LU": "png",
  "CD-MA": "png",
  "CD-MN": "png",
  "CD-NK": "png",
  "CD-SK": "png",
  "CD-T0": "png",
  "CD-TA": "png",
  "CD-TU": "png",
  "CH-NW": "png",
  "CI-AB": "png",
  "CRYSTAL-LOCALE": "png",
  "CU-04": "jpeg",
  "CU-05": "png",
  "CV-PR": "gif",
  "CV-RB": "png",
  "DJ-DJ": "png",
  "DO-02": "png",
  "DO-03": "png",
  "DO-05": "png",
  "DO-06": "png",
  "DO-09": "png",
  "DO-10": "png",
  "DO-11": "png",
  "DO-13": "png",
  "DO-14": "png",
  "DO-15": "png",
  "DO-16": "png",
  "DO-17": "png",
  "DO-19": "png",
  "DO-21": "png",
  "DO-24": "png",
  "DO-26": "png",
  "DO-29": "png",
  "DO-30": "png",
  "DO-31": "png",
  "DO-32": "png",
  "EE-205": "png",
  "EE-441": "png",
  "EE-486": "png",
  "EE-792": "png",
  "EE-899": "png",
  "EG-AST": "png",
  "EG-BA": "png",
  "EG-C": "png",
  "EG-FYM": "png",
  "EG-GH": "png",
  "EG-GZ": "png",
  "EG-IS": "png",
  "EG-KB": "png",
  "EG-KN": "png",
  "EG-LX": "png",
  "EG-MN": "png",
  "EG-MNF": "png",
  "EG-MT": "png",
  "EG-SHG": "png",
  "EG-WAD": "png",
  "ES-AL": "png",
  "ES-BI": "png",
  "ES-BU": "png",
  "ES-C": "png",
  "ES-CR": "png",
  "ES-CS": "png",
  "ES-GC": "png",
  "ES-GU": "png",
  "ES-MA": "png",
  "ES-MU": "png",
  "ES-V": "png",
  "ES-ZA": "png",
  "ET-DD": "png",
  "FI-02": "png",
  "FI-09": "png",
  "FI-10": "png",
  "FI-11": "png",
  "FI-12": "png",
  "FI-14": "png",
  "FI-19": "png",
  "FM-KSA": "png",
  "FM-PNI": "png",
  "FM-TRK": "svg.png",
  "FM-YAP": "png",
  "FR-2A": "jpeg",
  "FR-67": "jpeg",
  "GB-ANS": "png",
  "GB-BFS": "png",
  "GB-BGE": "png",
  "GB-BNH": "png",
  "GB-BOL": "png",
  "GB-BPL": "png",
  "GB-BRD": "png",
  "GB-BUR": "png",
  "GB-CAY": "png",
  "GB-CLD": "png",
  "GB-DAL": "jpeg",
  "GB-DNC": "png",
  "GB-DND": "png",
  "GB-DUD": "gif",
  "GB-EAY": "jpeg",
  "GB-ERY": "jpg",
  "GB-GAT": "png",
  "GB-GRE": "png",
  "GB-GWN": "png",
  "GB-HPL": "jpeg",
  "GB-HRT": "png",
  "GB-KIR": "png",
  "GB-KWL": "png",
  "GB-LBC": "png",
  "GB-LCE": "png",
  "GB-LEC": "png",
  "GB-MTY": "png",
  "GB-NAY": "jpeg",
  "GB-NLK": "jpeg",
  "GB-NSM": "png",
  "GB-NTL": "png",
  "GB-NTY": "png",
  "GB-NWP": "jpeg",
  "GB-OLD": "png",
  "GB-PLY": "jpg",
  "GB-RCH": "png",
  "GB-RCT": "png",
  "GB-RDB": "jpeg",
  "GB-RDG": "png",
  "GB-ROT": "png",
  "GB-SAW": "png",
  "GB-SAY": "png",
  "GB-SHF": "png",
  "GB-SKP": "png",
  "GB-SLF": "png",
  "GB-SLK": "jpeg",
  "GB-SOL": "png",
  "GB-SOS": "png",
  "GB-STE": "png",
  "GB-STG": "png",
  "GB-STH": "png",
  "GB-STT": "jpeg",
  "GB-STY": "png",
  "GB-SWA": "jpeg",
  "GB-TOB": "gif",
  "GB-TRF": "png",
  "GB-WDU": "png",
  "GB-WGN": "png",
  "GB-WKF": "png",
  "GB-WLN": "png",
  "GB-WOR": "png",
  "GB-WRL": "png",
  "GH-AA": "gif",
  "GH-CP": "gif",
  "GH-EP": "gif",
  "GH-TV": "png",
  "GH-WP": "gif",
  "GL-QT": "jpg",
  "GM-B": "png",
  "GQ-BN": "png",
  "GQ-BS": "png",
  "GQ-CS": "png",
  "GQ-KN": "png",
  "GQ-LI": "png",
  "GQ-WN": "png",
  "GR-E": "jpg",
  "GR-G": "png",
  "GT-01": "png",
  "GT-02": "jpg",
  "GT-04": "gif",
  "GT-06": "gif",
  "GT-07": "gif",
  "GT-09": "gif",
  "GT-10": "png",
  "GT-11": "gif",
  "GT-12": "gif",
  "GT-13": "gif",
  "GT-14": "png",
  "GT-15": "png",
  "GT-17": "png",
  "GT-18": "gif",
  "GT-19": "png",
  "GT-20": "png",
  "GT-22": "gif",
  "GT-BV": "png",
  "GT-ES": "gif",
  "GT-JU": "gif",
  "GT-RE": "gif",
  "GT-SR": "gif",
  "GT-SU": "png",
  "GT-ZA": "gif",
  "GW-BS": "png",
  "HN-AT": "png",
  "HN-CL": "gif",
  "HN-CM": "png",
  "HN-CP": "png",
  "HN-FM": "png",
  "HN-OL": "jpg",
  "HR-03": "png",
  "HR-05": "png",
  "HR-06": "png",
  "HR-07": "gif",
  "HR-08": "png",
  "HR-09": "png",
  "HR-10": "png",
  "HR-11": "png",
  "HR-13": "png",
  "HR-14": "png",
  "HR-19": "png",
  "HU-BC": "png",
  "HU-CS": "png",
  "HU-DE": "png",
  "HU-DU": "png",
  "HU-EG": "png",
  "HU-ER": "png",
  "HU-GY": "png",
  "HU-HV": "png",
  "HU-KM": "png",
  "HU-KV": "png",
  "HU-MI": "png",
  "HU-NK": "png",
  "HU-NY": "png",
  "HU-PS": "png",
  "HU-SD": "png",
  "HU-SF": "png",
  "HU-SH": "png",
  "HU-SK": "png",
  "HU-SN": "png",
  "HU-SS": "png",
  "HU-ST": "png",
  "HU-TB": "png",
  "HU-VM": "png",
  "HU-ZE": "png",
  "ID-BE": "png",
  "ID-KI": "png",
  "ID-KS": "png",
  "ID-KT": "png",
  "ID-KU": "png",
  "ID-NT": "png",
  "ID-SA": "png",
  "ID-SN": "png",
  "IE-CE": "png",
  "IE-CN": "png",
  "IE-CO": "png",
  "IE-CW": "svg.png",
  "IE-DL": "png",
  "IE-G": "png",
  "IE-KE": "png",
  "IE-KK": "png",
  "IE-KY": "png",
  "IE-LD": "png",
  "IE-LH": "png",
  "IE-LK": "png",
  "IE-LM": "png",
  "IE-LS": "png",
  "IE-MH": "png",
  "IE-MN": "png",
  "IE-MO": "png",
  "IE-OY": "png",
  "IE-RN": "png",
  "IE-SO": "png",
  "IE-TA": "png",
  "IE-WD": "png",
  "IE-WH": "png",
  "IE-WW": "png",
  "IE-WX": "png",
  "IN-AN": "png",
  "IN-AP": "png",
  "IN-AR": "png",
  "IN-BR": "png",
  "IN-CH": "png",
  "IN-CT": "png",
  "IN-DH": "png",
  "IN-GA": "png",
  "IN-JH": "png",
  "IN-JK": "png",
  "IN-KA": "png",
  "IN-KL": "png",
  "IN-LA": "png",
  "IN-LD": "png",
  "IN-ML": "png",
  "IN-MN": "png",
  "IN-MZ": "png",
  "IN-NL": "png",
  "IN-OR": "png",
  "IN-PY": "png",
  "IN-TG": "png",
  "IN-TN": "png",
  "IN-TR": "png",
  "IN-UT": "png",
  "IQ-AN": "png",
  "IQ-AR": "png",
  "IQ-BA": "png",
  "IQ-BB": "png",
  "IQ-BG": "png",
  "IQ-DA": "jpeg",
  "IQ-DI": "png",
  "IQ-DQ": "png",
  "IQ-KA": "png",
  "IQ-KI": "png",
  "IQ-KR": "png",
  "IQ-MA": "png",
  "IQ-MU": "png",
  "IQ-NA": "png",
  "IQ-NI": "png",
  "IQ-QA": "png",
  "IQ-SD": "png",
  "IQ-SU": "png",
  "IQ-WA": "png",
  "IS-AKN": "jpeg",
  "IS-AKU": "png",
  "IS-ARN": "jpg",
  "IS-ASA": "png",
  "IS-BLA": "png",
  "IS-BOG": "png",
  "IS-BOL": "png",
  "IS-DAB": "png",
  "IS-FLD": "png",
  "IS-FLR": "png",
  "IS-GRN": "png",
  "IS-GRU": "png",
  "IS-HAF": "png",
  "IS-HRU": "png",
  "IS-HUT": "png",
  "IS-HUV": "png",
  "IS-HVA": "png",
  "IS-HVE": "png",
  "IS-ISA": "png",
  "IS-KAL": "jpg",
  "IS-KJO": "png",
  "IS-KOP": "png",
  "IS-MOS": "png",
  "IS-MYR": "png",
  "IS-RGE": "png",
  "IS-RKV": "png",
  "IS-SDN": "png",
  "IS-SDV": "png",
  "IS-SKU": "png",
  "IS-SNF": "png",
  "IS-SOG": "png",
  "IS-SSS": "png",
  "IS-STR": "png",
  "IS-STY": "png",
  "IS-TAL": "png",
  "IS-THG": "png",
  "IS-VER": "png",
  "IT-AG": "png",
  "IT-AP": "png",
  "IT-AR": "gif",
  "IT-BI": "jpeg",
  "IT-BR": "gif",
  "IT-BS": "gif",
  "IT-BT": "jpeg",
  "IT-CR": "gif",
  "IT-CZ": "gif",
  "IT-EN": "jpeg",
  "IT-FC": "gif",
  "IT-FM": "gif",
  "IT-FR": "jpeg",
  "IT-GE": "gif",
  "IT-IS": "gif",
  "IT-KR": "png",
  "IT-LC": "gif",
  "IT-LE": "jpeg",
  "IT-LT": "png",
  "IT-MC": "png",
  "IT-MN": "png",
  "IT-MS": "png",
  "IT-MT": "jpeg",
  "IT-PE": "gif",
  "IT-PO": "gif",
  "IT-RO": "png",
  "IT-SO": "png",
  "IT-SP": "gif",
  "IT-SV": "gif",
  "IT-TV": "gif",
  "IT-VA": "gif",
  "IT-VB": "jpg",
  "IT-VI": "png",
  "IT-VV": "png",
  "JUANA-DIAZ": "jpg",
  "JUBA": "png",
  "KE-01": "png",
  "KE-02": "png",
  "KE-03": "gif",
  "KE-04": "png",
  "KE-05": "png",
  "KE-06": "png",
  "KE-07": "gif",
  "KE-08": "png",
  "KE-09": "gif",
  "KE-10": "png",
  "KE-11": "gif",
  "KE-12": "png",
  "KE-13": "png",
  "KE-14": "png",
  "KE-15": "png",
  "KE-16": "gif",
  "KE-17": "png",
  "KE-18": "jpeg",
  "KE-19": "png",
  "KE-20": "png",
  "KE-21": "gif",
  "KE-22": "png",
  "KE-23": "jpeg",
  "KE-24": "png",
  "KE-25": "png",
  "KE-26": "png",
  "KE-27": "gif",
  "KE-28": "png",
  "KE-29": "png",
  "KE-31": "gif",
  "KE-32": "gif",
  "KE-33": "gif",
  "KE-34": "gif",
  "KE-35": "png",
  "KE-36": "gif",
  "KE-37": "png",
  "KE-38": "png",
  "KE-39": "png",
  "KE-40": "gif",
  "KE-41": "png",
  "KE-42": "png",
  "KE-43": "png",
  "KE-44": "png",
  "KE-45": "png",
  "KE-46": "png",
  "KE-47": "png",
  "KG-GO": "png",
  "KG-J": "png",
  "KG-Y": "png",
  "KH-1": "png",
  "KH-10": "png",
  "KH-11": "png",
  "KH-13": "png",
  "KH-14": "png",
  "KH-15": "png",
  "KH-16": "png",
  "KH-17": "png",
  "KH-19": "png",
  "KH-2": "png",
  "KH-20": "png",
  "KH-21": "png",
  "KH-22": "png",
  "KH-24": "png",
  "KH-25": "png",
  "KH-3": "png",
  "KH-4": "png",
  "KH-5": "png",
  "KH-6": "png",
  "KH-7": "png",
  "KH-8": "png",
  "KH-9": "png",
  "KR-28": "png",
  "KZ-AKM": "png",
  "KZ-AKT": "png",
  "KZ-ALM": "png",
  "KZ-ATY": "png",
  "KZ-KAR": "png",
  "KZ-KUS": "png",
  "KZ-KZY": "png",
  "KZ-MAN": "jpeg",
  "KZ-SEV": "png",
  "KZ-SHY": "png",
  "KZ-VOS": "png",
  "KZ-YUZ": "png",
  "KZ-ZAP": "png",
  "KZ-ZHA": "png",
  "LES-DORIS-DE-SAINT-PIERRE-ET-MIQUELON": "jpg",
  "LK-1": "png",
  "LK-2": "png",
  "LK-22": "png",
  "LK-3": "png",
  "LK-5": "png",
  "LK-7": "png",
  "LK-9": "png",
  "LT-01": "png",
  "LT-02": "gif",
  "LT-03": "png",
  "LT-04": "png",
  "LT-05": "png",
  "LT-06": "png",
  "LT-07": "png",
  "LT-08": "png",
  "LT-09": "png",
  "LT-10": "png",
  "LT-11": "png",
  "LT-12": "png",
  "LT-13": "png",
  "LT-14": "png",
  "LT-15": "png",
  "LT-16": "png",
  "LT-17": "png",
  "LT-18": "png",
  "LT-19": "png",
  "LT-20": "png",
  "LT-21": "png",
  "LT-22": "png",
  "LT-23": "png",
  "LT-24": "png",
  "LT-26": "png",
  "LT-27": "png",
  "LT-28": "png",
  "LT-29": "png",
  "LT-30": "png",
  "LT-31": "png",
  "LT-32": "png",
  "LT-33": "png",
  "LT-34": "png",
  "LT-35": "png",
  "LT-36": "png",
  "LT-37": "png",
  "LT-38": "png",
  "LT-39": "gif",
  "LT-40": "png",
  "LT-41": "png",
  "LT-42": "png",
  "LT-43": "png",
  "LT-45": "png",
  "LT-46": "png",
  "LT-47": "png",
  "LT-48": "png",
  "LT-49": "png",
  "LT-50": "png",
  "LT-51": "png",
  "LT-52": "png",
  "LT-53": "png",
  "LT-MR": "png",
  "LT-PN": "png",
  "LT-SA": "png",
  "LT-TA": "png",
  "LT-TE": "png",
  "LU-CA": "svg.png",
  "LU-CL": "png",
  "LU-DI": "png",
  "LU-EC": "png",
  "LU-ES": "png",
  "LU-GR": "png",
  "LU-LU": "png",
  "LU-ME": "png",
  "LU-RD": "png",
  "LU-RM": "png",
  "LU-VD": "png",
  "LV-002": "png",
  "LV-007": "png",
  "LV-011": "png",
  "LV-015": "png",
  "LV-016": "png",
  "LV-022": "png",
  "LV-026": "png",
  "LV-033": "png",
  "LV-041": "png",
  "LV-042": "png",
  "LV-047": "png",
  "LV-050": "png",
  "LV-054": "png",
  "LV-056": "png",
  "LV-058": "png",
  "LV-062": "png",
  "LV-067": "png",
  "LV-068": "png",
  "LV-073": "png",
  "LV-080": "png",
  "LV-087": "jpg",
  "LV-088": "png",
  "LV-089": "png",
  "LV-091": "png",
  "LV-094": "png",
  "LV-097": "png",
  "LV-099": "png",
  "LV-101": "png",
  "LV-102": "png",
  "LV-106": "png",
  "LV-112": "png",
  "LV-50": "png",
  "LV-54": "png",
  "LV-DGV": "png",
  "LY-BA": "png",
  "MA-01": "png",
  "MA-02": "png",
  "MA-06": "png",
  "MA-07": "png",
  "MA-08": "png",
  "MA-09": "png",
  "MA-10": "jpeg",
  "MA-12": "png",
  "MA-BOD": "png",
  "MA-BOM": "png",
  "MA-CAS": "png",
  "MA-ESI": "png",
  "MA-FES": "png",
  "MA-HAO": "png",
  "MA-HOC": "png",
  "MA-KES": "png",
  "MA-OUA": "png",
  "MA-OUJ": "png",
  "MA-RAB": "png",
  "MA-SAF": "gif",
  "MA-SAL": "png",
  "MA-SIB": "png",
  "MD-AN": "gif",
  "MD-BA": "png",
  "MD-BD": "jpeg",
  "MD-BS": "png",
  "MD-CL": "gif",
  "MD-CM": "gif",
  "MD-CR": "gif",
  "MD-CS": "jpg",
  "MD-CU": "gif",
  "MD-DO": "gif",
  "MD-DR": "png",
  "MD-FA": "gif",
  "MD-FL": "png",
  "MD-GL": "gif",
  "MD-HI": "gif",
  "MD-IA": "gif",
  "MD-LE": "gif",
  "MD-NI": "gif",
  "MD-OC": "gif",
  "MD-OR": "gif",
  "MD-RI": "gif",
  "MD-SD": "gif",
  "MD-SI": "gif",
  "MD-SN": "png",
  "MD-SO": "png",
  "MD-ST": "gif",
  "MD-SV": "gif",
  "MD-TA": "gif",
  "MD-TE": "jpg",
  "MD-UN": "png",
  "ME-01": "jpeg",
  "ME-02": "png",
  "ME-03": "png",
  "ME-04": "png",
  "ME-06": "png",
  "ME-07": "jpeg",
  "ME-08": "jpg",
  "ME-09": "gif",
  "ME-10": "png",
  "ME-11": "png",
  "ME-12": "gif",
  "ME-13": "png",
  "ME-14": "png",
  "ME-15": "png",
  "ME-16": "png",
  "ME-17": "png",
  "ME-18": "png",
  "ME-19": "png",
  "ME-21": "png",
  "ME-22": "png",
  "MH-UTI": "png",
  "MK-102": "gif",
  "MK-108": "jpeg",
  "MK-209": "png",
  "MK-310": "png",
  "MK-405": "png",
  "MK-406": "png",
  "MK-701": "png",
  "MK-702": "png",
  "MK-813": "png",
  "MK-816": "jpg",
  "ML-BKO": "png",
  "MM-02": "png",
  "MM-17": "png",
  "MN-069": "png",
  "MN-073": "png",
  "MP-L": "png",
  "MP-MPM": "png",
  "MT-05": "gif",
  "MT-21": "gif",
  "MT-39": "gif",
  "MU-RO": "png",
  "MX-CMX": "png",
  "MX-MIC": "png",
  "MX-TAB": "png",
  "MX-YUC": "png",
  "MY-04": "png",
  "MZ-I": "gif",
  "MZ-L": "png",
  "MZ-MPM": "png",
  "MZ-N": "gif",
  "MZ-P": "png",
  "MZ-S": "png",
  "MZ-T": "gif",
  "NG-AB": "gif",
  "NG-AD": "jpeg",
  "NG-AN": "png",
  "NG-BA": "png",
  "NG-BE": "png",
  "NG-BO": "gif",
  "NG-CR": "gif",
  "NG-DE": "gif",
  "NG-EB": "png",
  "NG-ED": "png",
  "NG-EK": "gif",
  "NG-EN": "png",
  "NG-FC": "png",
  "NG-IM": "png",
  "NG-JI": "png",
  "NG-KD": "png",
  "NG-KE": "png",
  "NG-KN": "png",
  "NG-KO": "png",
  "NG-KT": "png",
  "NG-KW": "jpg",
  "NG-LA": "gif",
  "NG-NA": "png",
  "NG-NI": "png",
  "NG-OG": "jpeg",
  "NG-ON": "jpg",
  "NG-OY": "png",
  "NG-PL": "jpg",
  "NG-RI": "png",
  "NG-SO": "png",
  "NG-TA": "png",
  "NG-YO": "png",
  "NG-ZA": "png",
  "NI-CA": "png",
  "NI-CO": "png",
  "NI-JI": "gif",
  "NI-SJ": "png",
  "NO-18": "png",
  "NO-30": "png",
  "NO-46": "png",
  "NO-50": "png",
  "NO-54": "png",
  "NP-P1": "png",
  "NP-P2": "png",
  "NP-P3": "jpeg",
  "NP-P4": "png",
  "NP-P5": "png",
  "NP-P6": "png",
  "NP-P7": "png",
  "NZ-GIS": "jpeg",
  "NZ-TKI": "png",
  "PA-8": "png",
  "PA-EM": "png",
  "PA-NT": "png",
  "PE-AMA": "png",
  "PE-ANC": "png",
  "PE-ICA": "png",
  "PE-LOR": "png",
  "PE-PUN": "png",
  "PE-SAM": "png",
  "PG-EPW": "png",
  "PG-ESW": "png",
  "PG-GPK": "png",
  "PG-MPL": "png",
  "PG-NPP": "png",
  "PH-14": "svg.png",
  "PH-15": "png",
  "PH-ABR": "png",
  "PH-AGN": "png",
  "PH-AGS": "png",
  "PH-AKL": "png",
  "PH-ALB": "png",
  "PH-ANT": "png",
  "PH-APA": "png",
  "PH-AUR": "png",
  "PH-BAN": "png",
  "PH-BAS": "png",
  "PH-BEN": "png",
  "PH-BIL": "png",
  "PH-BOH": "png",
  "PH-BTG": "png",
  "PH-BTN": "png",
  "PH-BUK": "png",
  "PH-BUL": "png",
  "PH-CAM": "png",
  "PH-CAP": "png",
  "PH-CAS": "png",
  "PH-CAT": "png",
  "PH-CAV": "png",
  "PH-COM": "jpg",
  "PH-DAO": "png",
  "PH-DAS": "gif",
  "PH-DAV": "png",
  "PH-DIN": "png",
  "PH-DVO": "png",
  "PH-EAS": "png",
  "PH-GUI": "png",
  "PH-IFU": "png",
  "PH-ILI": "png",
  "PH-ILN": "png",
  "PH-ILS": "png",
  "PH-KAL": "png",
  "PH-LAG": "png",
  "PH-LAN": "png",
  "PH-LAS": "png",
  "PH-LEY": "png",
  "PH-LUN": "png",
  "PH-MAD": "png",
  "PH-MAG": "png",
  "PH-MAS": "png",
  "PH-MDC": "png",
  "PH-MDR": "png",
  "PH-MOU": "png",
  "PH-MSR": "png",
  "PH-NCO": "png",
  "PH-NEC": "png",
  "PH-NER": "png",
  "PH-NSA": "png",
  "PH-NUE": "gif",
  "PH-NUV": "png",
  "PH-PAM": "png",
  "PH-PLW": "png",
  "PH-QUE": "png",
  "PH-QUI": "png",
  "PH-RIZ": "png",
  "PH-ROM": "png",
  "PH-SAR": "png",
  "PH-SCO": "png",
  "PH-SIG": "png",
  "PH-SLE": "png",
  "PH-SOR": "png",
  "PH-SUK": "png",
  "PH-SUR": "png",
  "PH-TAR": "png",
  "PH-TAW": "png",
  "PH-WSA": "gif",
  "PH-ZAN": "png",
  "PH-ZAS": "png",
  "PH-ZMB": "png",
  "PH-ZSI": "png",
  "PK-TA": "png",
  "PT-01": "png",
  "PT-02": "png",
  "PT-03": "png",
  "PT-04": "png",
  "PT-05": "png",
  "PT-06": "png",
  "PT-07": "png",
  "PT-09": "png",
  "PT-10": "png",
  "PT-11": "png",
  "PT-12": "png",
  "PT-13": "png",
  "PT-14": "png",
  "PT-15": "png",
  "PT-16": "png",
  "PT-17": "png",
  "PT-18": "png",
  "PW-004": "png",
  "PW-150": "png",
  "PW-212": "png",
  "PW-222": "png",
  "PW-228": "png",
  "PY-13": "png",
  "PY-2": "jpg",
  "PY-3": "jpg",
  "PY-7": "png",
  "PY-8": "jpg",
  "PY-9": "jpg",
  "QA-WA": "jpeg",
  "RO-AB": "jpg",
  "RO-AG": "png",
  "RO-BH": "png",
  "RO-BV": "png",
  "RO-BZ": "png",
  "RO-CS": "png",
  "RO-CT": "png",
  "RO-HD": "png",
  "RO-IF": "png",
  "RO-MH": "png",
  "RO-MM": "jpg",
  "RO-OT": "png",
  "RO-SB": "png",
  "RO-SM": "png",
  "RO-SV": "png",
  "RO-TM": "png",
  "RU-CU": "png",
  "RU-SAR": "png",
  "RUWENG": "png",
  "SABANAGRANDE": "jpg",
  "SB-CE": "png",
  "SB-CH": "png",
  "SB-CT": "png",
  "SB-GU": "png",
  "SB-IS": "png",
  "SB-MK": "png",
  "SB-TE": "png",
  "SB-WE": "png",
  "SC-01": "png",
  "SC-02": "png",
  "SC-03": "png",
  "SC-04": "png",
  "SC-05": "png",
  "SC-06": "png",
  "SC-07": "png",
  "SC-08": "png",
  "SC-09": "png",
  "SC-10": "png",
  "SC-11": "png",
  "SC-12": "png",
  "SC-13": "png",
  "SC-14": "png",
  "SC-17": "jpeg",
  "SC-18": "png",
  "SC-19": "png",
  "SC-20": "png",
  "SC-21": "png",
  "SC-22": "png",
  "SC-23": "jpeg",
  "SC-24": "jpeg",
  "SC-25": "png",
  "SC-26": "jpeg",
  "SC-27": "jpeg",
  "SD-DC": "png",
  "SD-DE": "png",
  "SD-DN": "png",
  "SD-DS": "png",
  "SD-DW": "png",
  "SD-GD": "png",
  "SD-GK": "png",
  "SD-GZ": "png",
  "SD-KA": "png",
  "SD-KH": "png",
  "SD-KS": "png",
  "SD-NB": "png",
  "SD-NO": "png",
  "SD-NR": "png",
  "SD-NW": "png",
  "SD-RS": "png",
  "SD-SI": "png",
  "SG-02": "jpeg",
  "SG-03": "png",
  "SG-04": "jpeg",
  "SG-05": "jpeg",
  "SI-001": "gif",
  "SI-002": "gif",
  "SI-003": "gif",
  "SI-004": "gif",
  "SI-005": "gif",
  "SI-006": "gif",
  "SI-007": "gif",
  "SI-008": "gif",
  "SI-009": "gif",
  "SI-010": "gif",
  "SI-011": "gif",
  "SI-012": "gif",
  "SI-013": "gif",
  "SI-014": "gif",
  "SI-015": "gif",
  "SI-016": "gif",
  "SI-017": "gif",
  "SI-018": "gif",
  "SI-019": "gif",
  "SI-020": "gif",
  "SI-021": "gif",
  "SI-022": "gif",
  "SI-023": "gif",
  "SI-024": "gif",
  "SI-025": "gif",
  "SI-026": "gif",
  "SI-027": "gif",
  "SI-028": "gif",
  "SI-029": "gif",
  "SI-030": "gif",
  "SI-031": "gif",
  "SI-032": "gif",
  "SI-033": "png",
  "SI-034": "gif",
  "SI-035": "gif",
  "SI-036": "gif",
  "SI-037": "gif",
  "SI-038": "gif",
  "SI-039": "gif",
  "SI-040": "gif",
  "SI-041": "gif",
  "SI-042": "gif",
  "SI-043": "gif",
  "SI-044": "gif",
  "SI-045": "gif",
  "SI-046": "gif",
  "SI-047": "gif",
  "SI-048": "png",
  "SI-049": "gif",
  "SI-050": "gif",
  "SI-051": "gif",
  "SI-052": "gif",
  "SI-053": "gif",
  "SI-054": "gif",
  "SI-055": "gif",
  "SI-056": "gif",
  "SI-057": "gif",
  "SI-058": "gif",
  "SI-059": "gif",
  "SI-060": "gif",
  "SI-061": "gif",
  "SI-062": "gif",
  "SI-063": "gif",
  "SI-064": "gif",
  "SI-065": "gif",
  "SI-066": "gif",
  "SI-067": "gif",
  "SI-068": "gif",
  "SI-069": "gif",
  "SI-070": "gif",
  "SI-071": "gif",
  "SI-072": "gif",
  "SI-073": "gif",
  "SI-074": "gif",
  "SI-075": "gif",
  "SI-076": "gif",
  "SI-077": "gif",
  "SI-078": "gif",
  "SI-079": "gif",
  "SI-080": "gif",
  "SI-081": "gif",
  "SI-082": "gif",
  "SI-083": "gif",
  "SI-084": "gif",
  "SI-085": "gif",
  "SI-086": "gif",
  "SI-087": "gif",
  "SI-088": "gif",
  "SI-089": "gif",
  "SI-090": "gif",
  "SI-091": "gif",
  "SI-092": "gif",
  "SI-093": "gif",
  "SI-094": "gif",
  "SI-095": "gif",
  "SI-096": "gif",
  "SI-097": "gif",
  "SI-098": "gif",
  "SI-099": "gif",
  "SI-100": "gif",
  "SI-101": "gif",
  "SI-102": "gif",
  "SI-103": "gif",
  "SI-104": "gif",
  "SI-105": "gif",
  "SI-106": "gif",
  "SI-107": "gif",
  "SI-108": "gif",
  "SI-109": "gif",
  "SI-110": "gif",
  "SI-111": "gif",
  "SI-112": "gif",
  "SI-113": "gif",
  "SI-114": "gif",
  "SI-115": "gif",
  "SI-116": "gif",
  "SI-117": "gif",
  "SI-118": "gif",
  "SI-119": "gif",
  "SI-120": "gif",
  "SI-121": "gif",
  "SI-122": "gif",
  "SI-123": "gif",
  "SI-124": "gif",
  "SI-125": "gif",
  "SI-126": "gif",
  "SI-127": "gif",
  "SI-128": "gif",
  "SI-129": "gif",
  "SI-130": "gif",
  "SI-131": "gif",
  "SI-132": "gif",
  "SI-133": "gif",
  "SI-134": "gif",
  "SI-135": "gif",
  "SI-136": "gif",
  "SI-137": "gif",
  "SI-138": "gif",
  "SI-139": "gif",
  "SI-140": "gif",
  "SI-141": "gif",
  "SI-142": "gif",
  "SI-143": "gif",
  "SI-144": "gif",
  "SI-146": "gif",
  "SI-147": "gif",
  "SI-148": "gif",
  "SI-149": "gif",
  "SI-150": "gif",
  "SI-151": "gif",
  "SI-152": "gif",
  "SI-153": "gif",
  "SI-154": "gif",
  "SI-155": "gif",
  "SI-156": "gif",
  "SI-157": "gif",
  "SI-158": "gif",
  "SI-159": "gif",
  "SI-160": "gif",
  "SI-161": "gif",
  "SI-162": "gif",
  "SI-163": "gif",
  "SI-164": "gif",
  "SI-165": "gif",
  "SI-166": "gif",
  "SI-167": "gif",
  "SI-168": "gif",
  "SI-169": "gif",
  "SI-170": "gif",
  "SI-171": "gif",
  "SI-172": "gif",
  "SI-173": "gif",
  "SI-174": "gif",
  "SI-175": "gif",
  "SI-176": "gif",
  "SI-177": "gif",
  "SI-178": "gif",
  "SI-179": "gif",
  "SI-180": "gif",
  "SI-181": "gif",
  "SI-182": "gif",
  "SI-183": "gif",
  "SI-184": "gif",
  "SI-185": "gif",
  "SI-186": "gif",
  "SI-187": "gif",
  "SI-188": "gif",
  "SI-189": "gif",
  "SI-190": "gif",
  "SI-191": "gif",
  "SI-192": "gif",
  "SI-193": "gif",
  "SI-194": "gif",
  "SI-195": "gif",
  "SI-196": "gif",
  "SI-197": "gif",
  "SI-198": "gif",
  "SI-199": "gif",
  "SI-200": "gif",
  "SI-201": "gif",
  "SI-202": "gif",
  "SI-203": "gif",
  "SI-204": "gif",
  "SI-205": "gif",
  "SI-206": "gif",
  "SI-207": "gif",
  "SI-208": "gif",
  "SI-209": "gif",
  "SI-210": "gif",
  "SI-211": "gif",
  "SI-212": "gif",
  "SI-213": "gif",
  "SI-48": "gif",
  "SM-01": "jpg",
  "SM-02": "jpg",
  "SM-03": "jpg",
  "SM-04": "jpg",
  "SM-05": "jpg",
  "SM-06": "jpg",
  "SM-08": "jpg",
  "SM-09": "jpg",
  "SN-DK": "png",
  "SO-BK": "png",
  "SO-BY": "png",
  "SO-GE": "png",
  "SO-SH": "png",
  "SS-BN": "png",
  "SS-BW": "png",
  "SS-EC": "png",
  "SS-EE": "png",
  "SS-EW": "png",
  "SS-JG": "png",
  "SS-LK": "png",
  "SS-NU": "png",
  "SS-UY": "png",
  "SS-WR": "png",
  "ST-01": "gif",
  "SV-AH": "png",
  "SV-CU": "png",
  "SV-PA": "jpg",
  "SV-SM": "png",
  "SV-SO": "png",
  "SV-SS": "png",
  "TH-11": "png",
  "TH-13": "png",
  "TH-15": "png",
  "TH-16": "png",
  "TH-17": "png",
  "TH-18": "png",
  "TH-19": "png",
  "TH-20": "png",
  "TH-21": "png",
  "TH-22": "jpeg",
  "TH-23": "png",
  "TH-24": "png",
  "TH-25": "jpeg",
  "TH-26": "png",
  "TH-27": "png",
  "TH-30": "png",
  "TH-31": "png",
  "TH-32": "png",
  "TH-33": "png",
  "TH-35": "png",
  "TH-36": "png",
  "TH-37": "png",
  "TH-38": "png",
  "TH-39": "png",
  "TH-40": "png",
  "TH-41": "png",
  "TH-42": "png",
  "TH-43": "png",
  "TH-44": "png",
  "TH-45": "png",
  "TH-46": "png",
  "TH-47": "png",
  "TH-49": "png",
  "TH-50": "png",
  "TH-51": "png",
  "TH-52": "png",
  "TH-53": "png",
  "TH-54": "png",
  "TH-57": "png",
  "TH-58": "png",
  "TH-60": "png",
  "TH-61": "png",
  "TH-62": "png",
  "TH-63": "png",
  "TH-66": "png",
  "TH-67": "png",
  "TH-70": "png",
  "TH-71": "png",
  "TH-72": "png",
  "TH-73": "png",
  "TH-74": "png",
  "TH-75": "png",
  "TH-76": "png",
  "TH-77": "png",
  "TH-80": "png",
  "TH-81": "png",
  "TH-82": "png",
  "TH-83": "png",
  "TH-84": "png",
  "TH-85": "png",
  "TH-86": "png",
  "TH-90": "png",
  "TH-91": "png",
  "TH-92": "png",
  "TH-93": "png",
  "TH-94": "png",
  "TH-95": "png",
  "TH-96": "png",
  "TH-S": "png",
  "TJ-DU": "png",
  "TL-BA": "png",
  "TL-CO": "png",
  "TL-ER": "png",
  "TL-LI": "png",
  "TL-MF": "png",
  "TL-OE": "png",
  "TN-73": "jpeg",
  "TN-81": "png",
  "TR-34": "png",
  "TR-48": "jpeg",
  "TR-54": "png",
  "TT-ARI": "png",
  "TT-CHA": "png",
  "TT-CTT": "png",
  "TT-DMN": "png",
  "TT-MRC": "png",
  "TT-PRT": "png",
  "TT-TUP": "jpeg",
  "TW-HSQ": "png",
  "UM-67": "png",
  "UM-79": "png",
  "US-GA": "svg.png",
  "US-UM": "png",
  "UY-FD": "png",
  "UY-FS": "png",
  "UY-LA": "png",
  "UY-MA": "png",
  "UY-MO": "png",
  "UY-RN": "png",
  "UY-RV": "png",
  "UY-TA": "png",
  "UZ-TK": "png",
  "VANNES-SEMAINE-DU-GOLFE-2015-2": "jpg",
  "VE-X": "png",
  "VE-Z": "png",
  "YAUCO-THROUGH-2004": "gif",
  "ZA-EC": "png",
  "ZA-FS": "png",
  "ZA-GP": "png",
  "ZA-KZN": "png",
  "ZA-LP": "png",
  "ZA-NC": "png",
  "ZA-NW": "png",
  "ZA-WC": "png",
  "ZM-01": "png",
  "ZM-02": "png",
  "ZM-03": "png",
  "ZM-04": "jpeg",
  "ZM-05": "png",
  "ZM-06": "png",
  "ZM-07": "png",
  "ZM-08": "png",
  "ZM-09": "png",
  "ZM-10": "png",
};

// All ISO 3166-2 codes with a known flag in the index
const FLAG_CODES = new Set<string>([
  "1868-LARES-REVOLUTIONAY","AD-02","AD-03","AD-04","AD-05","AD-06","AD-07","AD-08","ADJUNTAS-PUERTO-RICO","AE-AJ",
  "AE-AZ","AE-DU","AE-FU","AE-RK","AE-SH","AE-UQ","AG-10","AGUADA-PR","AGUAS-BUENAS","AL-01",
  "AL-02","AL-03","AL-04","AL-05","AL-06","AL-07","AL-08","AL-09","AL-10","AL-11",
  "AL-12","ALAVA","AM-ER","AM-GR","AM-KT","AM-LO","AM-VD","ANASCO","AO-CAB","AR-A",
  "AR-B","AR-C","AR-D","AR-E","AR-F","AR-G","AR-H","AR-J","AR-K","AR-L",
  "AR-M","AR-N","AR-P","AR-Q","AR-R","AR-S","AR-T","AR-U","AR-V","AR-W",
  "AR-X","AR-Y","AR-Z","AT-1","AT-2","AT-3","AT-4","AT-5","AT-6","AT-7",
  "AT-8","AT-9","AU-ACT","AU-NSW","AU-NT","AU-QLD","AU-SA","AU-TAS","AU-VIC","AU-WA",
  "AZ-BA","AZ-SA","AZ-SM","AZ-XA","AZ-YE","BA-BRC","BA-SRP","BANDERA-DE-AGUADILLA-PUERTO-RICO","BANDERA-DE-AIBONITO-PUERTO-RICO","BANDERA-DE-ARECIBO-PUERTO-RICO",
  "BANDERA-DE-CANOVANAS-PUERTO-RICO","BANDERA-DE-CIDRA-PUERTO-RICO","BANDERA-DE-LA-PROVINCIA-BIOKO-DEL-NORTE","BANDERA-DE-LA-PROVINCIA-BIOKO-DEL-SUR","BANDERA-DE-LA-PROVINCIA-CENTRO-SUR","BANDERA-DE-LA-PROVINCIA-KIE-NTEM","BANDERA-DE-LA-PROVINCIA-LITORAL","BANDERA-DE-LA-PROVINCIA-WELE-NZAS","BANDERA-DE-LUQUILLO","BANDERA-DE-MOROVIS-PUERTO-RICO",
  "BANDERA-DE-NAGUABO-PUERTO-RICO","BANDERA-DE-NAVARRA","BANDERA-DE-SAN-GERMAN","BANDERA-DE-VIZCAYA","BANDERA-DE-YAUCO-PUERTO-RICO","BANDERA-PENUELAS","BARCELONETA-PUERTO-RICO","BARRANQUITAS","BASQUE-COUNTRY","BAYAMON",
  "BE-BRU","BE-VAN","BE-VBR","BE-VLG","BE-VLI","BE-VOV","BE-VWV","BE-WAL","BE-WBR","BE-WHT",
  "BE-WLG","BE-WLX","BE-WNA","BEQUIA","BG-23","BH-13","BH-14","BH-15","BH-17","BO-B",
  "BO-C","BO-H","BO-L","BO-N","BO-O","BO-P","BO-S","BO-T","BQ-BO","BQ-SA",
  "BQ-SE","BR-AC","BR-AL","BR-AM","BR-AP","BR-BA","BR-CE","BR-DF","BR-ES","BR-GO",
  "BR-MA","BR-MG","BR-MS","BR-MT","BR-PA","BR-PB","BR-PE","BR-PI","BR-PR","BR-RJ",
  "BR-RN","BR-RO","BR-RR","BR-RS","BR-SC","BR-SE","BR-SP","BR-TO","BUBI-TRIBAL","BW-GA",
  "BY-BR","BY-HM","BY-HO","BY-HR","BY-MA","BY-MI","BY-VI","BZ-BZ","CA-AB","CA-BC",
  "CA-MB","CA-NB","CA-NL","CA-NS","CA-NT","CA-NU","CA-ON","CA-PE","CA-QC","CA-SK",
  "CA-YT","CABO-ROJO","CAGUAS","CAMUYFLAG","CAROLINA-PUERTO-RICO","CATANO-PUERTO-RICO","CAYEY","CD-BC","CD-BU","CD-HK",
  "CD-HU","CD-IT","CD-KC","CD-KE","CD-KL","CD-KN","CD-KS","CD-LU","CD-MA","CD-MN",
  "CD-NK","CD-SA","CD-SK","CD-T0","CD-TA","CD-TU","CEIBAFLAG","CG-16","CH-AG","CH-AI",
  "CH-AR","CH-BE","CH-BL","CH-BS","CH-FR","CH-GE","CH-GL","CH-GR","CH-JU","CH-LU",
  "CH-NE","CH-NW","CH-OW","CH-SG","CH-SH","CH-SO","CH-SZ","CH-TG","CH-TI","CH-UR",
  "CH-VD","CH-VS","CH-ZG","CH-ZH","CI-AB","CIALES","CIENFUEGOS-PROVINCEPROPOSAL","CITY-OF-HAVANA","CL-AI","CL-AN",
  "CL-AP","CL-AR","CL-AT","CL-BI","CL-CO","CL-LI","CL-LL","CL-LR","CL-MA","CL-ML",
  "CL-NB","CL-RM","CL-TA","CL-VS","CN-HK","CN-MO","CN-TW","CO-AMA","CO-ANT","CO-ARA",
  "CO-ATL","CO-BOL","CO-BOY","CO-CAL","CO-CAQ","CO-CAS","CO-CAU","CO-CES","CO-CHO","CO-COR",
  "CO-CUN","CO-DC","CO-GUA","CO-GUV","CO-HUI","CO-LAG","CO-MAG","CO-MET","CO-NAR","CO-NSA",
  "CO-PUT","CO-QUI","CO-RIS","CO-SAN","CO-SAP","CO-SUC","CO-TOL","CO-VAC","CO-VAU","CO-VID",
  "COAMO","COMERIO","COROZAL","CR-A","CR-C","CR-G","CR-H","CR-L","CR-P","CR-SJ",
  "CRYSTAL-LOCALE","CU-01","CU-03","CU-04","CU-05","CU-06","CU-07","CU-08","CU-09","CU-10",
  "CU-11","CU-12","CU-13","CU-14","CU-15","CU-16","CU-99","CULEBRA-PUERTO-RICO","CV-MO","CV-PR",
  "CV-RB","CV-SM","CY-01","CZ-10","CZ-20","CZ-31","CZ-32","CZ-41","CZ-42","CZ-51",
  "CZ-52","CZ-53","CZ-63","CZ-64","CZ-71","CZ-72","CZ-80","DE-BB","DE-BE","DE-BW",
  "DE-BY","DE-HB","DE-HE","DE-HH","DE-MV","DE-NI","DE-NW","DE-RP","DE-SH","DE-SL",
  "DE-SN","DE-ST","DE-TH","DJ-DJ","DK-81","DK-82","DK-83","DK-84","DK-85","DO-01",
  "DO-02","DO-03","DO-04","DO-05","DO-06","DO-07","DO-08","DO-09","DO-10","DO-11",
  "DO-12","DO-13","DO-14","DO-15","DO-16","DO-17","DO-18","DO-19","DO-20","DO-21",
  "DO-22","DO-23","DO-24","DO-25","DO-26","DO-27","DO-28","DO-29","DO-30","DO-31",
  "DO-32","DORADOFLAG","DRAPEAU-PROPOSE-POUR-LES-PYRENEES-ATLANTIQUES","EC-A","EC-B","EC-C","EC-D","EC-E","EC-F","EC-G",
  "EC-H","EC-I","EC-L","EC-M","EC-N","EC-O","EC-P","EC-R","EC-S","EC-SD",
  "EC-SE","EC-T","EC-U","EC-W","EC-X","EC-Y","EC-Z","EE-130","EE-142","EE-171",
  "EE-184","EE-191","EE-198","EE-205","EE-214","EE-245","EE-247","EE-251","EE-255","EE-272",
  "EE-283","EE-284","EE-291","EE-293","EE-296","EE-303","EE-305","EE-317","EE-321","EE-338",
  "EE-353","EE-37","EE-39","EE-424","EE-430","EE-431","EE-432","EE-441","EE-442","EE-446",
  "EE-45","EE-478","EE-480","EE-486","EE-50","EE-503","EE-511","EE-514","EE-52","EE-528",
  "EE-557","EE-56","EE-567","EE-586","EE-60","EE-615","EE-618","EE-622","EE-624","EE-638",
  "EE-64","EE-651","EE-653","EE-661","EE-663","EE-668","EE-68","EE-689","EE-698","EE-708",
  "EE-71","EE-712","EE-714","EE-719","EE-726","EE-732","EE-735","EE-74","EE-784","EE-79",
  "EE-792","EE-793","EE-796","EE-803","EE-809","EE-81","EE-824","EE-834","EE-84","EE-855",
  "EE-87","EE-890","EE-897","EE-899","EE-901","EE-903","EE-907","EE-917","EE-919","EE-928",
  "EG-ALX","EG-ASN","EG-AST","EG-BA","EG-BH","EG-BNS","EG-C","EG-DK","EG-DT","EG-FYM",
  "EG-GH","EG-GZ","EG-IS","EG-JS","EG-KB","EG-KFS","EG-KN","EG-LX","EG-MN","EG-MNF",
  "EG-MT","EG-PTS","EG-SHG","EG-SHR","EG-SIN","EG-SUZ","EG-WAD","ES-A","ES-AB","ES-AL",
  "ES-AN","ES-AR","ES-AS","ES-AV","ES-B","ES-BA","ES-BI","ES-BU","ES-C","ES-CA",
  "ES-CB","ES-CC","ES-CE","ES-CL","ES-CM","ES-CN","ES-CO","ES-CR","ES-CS","ES-CT",
  "ES-CU","ES-EX","ES-GA","ES-GC","ES-GI","ES-GR","ES-GU","ES-H","ES-HU","ES-IB",
  "ES-J","ES-L","ES-LE","ES-LO","ES-LU","ES-M","ES-MA","ES-MC","ES-MD","ES-ML",
  "ES-MU","ES-NA","ES-NC","ES-O","ES-OR","ES-P","ES-PM","ES-PO","ES-PV","ES-RI",
  "ES-S","ES-SA","ES-SE","ES-SG","ES-SO","ES-SS","ES-T","ES-TE","ES-TF","ES-TO",
  "ES-V","ES-VA","ES-VC","ES-VI","ES-Z","ES-ZA","ESTONIA","ESTUAIRE-PROVINCE-GABON","ET-AA","ET-AF",
  "ET-AM","ET-BE","ET-DD","ET-GA","ET-HA","ET-HARJU-MAAKOND","ET-OR","ET-SI","ET-SN","ET-SO",
  "ET-TI","FAJARDO","FI-01","FI-02","FI-03","FI-04","FI-05","FI-06","FI-07","FI-08",
  "FI-09","FI-10","FI-11","FI-12","FI-13","FI-14","FI-15","FI-16","FI-17","FI-18",
  "FI-19","FLORIDA-PUERTO-RICO","FM-KSA","FM-PNI","FM-TRK","FM-YAP","FORMER-LA-HABANA-1976-2010","FORMER-LA-HABANA-PROVINCE-1976---2010","FORMER-LA-HABANA-PROVINCE-1976-2010","FR-01",
  "FR-02","FR-03","FR-04","FR-05","FR-06","FR-07","FR-08","FR-09","FR-10","FR-11",
  "FR-12","FR-13","FR-14","FR-15","FR-16","FR-17","FR-18","FR-19","FR-20R","FR-21",
  "FR-22","FR-23","FR-24","FR-25","FR-26","FR-27","FR-28","FR-29","FR-2A","FR-2B",
  "FR-30","FR-32","FR-33","FR-34","FR-35","FR-36","FR-37","FR-38","FR-39","FR-40",
  "FR-41","FR-42","FR-43","FR-44","FR-45","FR-46","FR-47","FR-48","FR-49","FR-50",
  "FR-51","FR-52","FR-53","FR-54","FR-55","FR-56","FR-57","FR-58","FR-59","FR-60",
  "FR-61","FR-62","FR-63","FR-64","FR-65","FR-66","FR-67","FR-68","FR-69","FR-6AE",
  "FR-70","FR-71","FR-72","FR-73","FR-74","FR-75C","FR-76","FR-77","FR-78","FR-79",
  "FR-80","FR-81","FR-82","FR-83","FR-84","FR-85","FR-86","FR-87","FR-88","FR-89",
  "FR-90","FR-91","FR-92","FR-93","FR-94","FR-95","FR-971","FR-972","FR-973","FR-974",
  "FR-976","FR-ARA","FR-BFC","FR-BL","FR-BRE","FR-CP","FR-CVL","FR-GES","FR-HDF","FR-IDF",
  "FR-MF","FR-NAQ","FR-NC","FR-NOR","FR-OCC","FR-PAC","FR-PDL","FR-PF","FR-PM","FR-TF",
  "FR-WF","FRANCE","GA-1","GA-2","GA-3","GA-4","GA-6","GA-7","GA-8","GA-9",
  "GB-ABE","GB-AGB","GB-AGY","GB-ANS","GB-BBD","GB-BDF","GB-BDG","GB-BEN","GB-BEX","GB-BFS",
  "GB-BGE","GB-BGW","GB-BIR","GB-BKM","GB-BNE","GB-BNH","GB-BNS","GB-BOL","GB-BPL","GB-BRD",
  "GB-BRY","GB-BST","GB-BUR","GB-CAM","GB-CAY","GB-CBF","GB-CGN","GB-CHE","GB-CHW","GB-CLD",
  "GB-CLK","GB-CMA","GB-CMD","GB-CMN","GB-CON","GB-COV","GB-CRF","GB-CRY","GB-DAL","GB-DBY",
  "GB-DEN","GB-DEV","GB-DGY","GB-DNC","GB-DND","GB-DOR","GB-DUD","GB-DUR","GB-EAL","GB-EAY",
  "GB-EDH","GB-EDU","GB-ELN","GB-ENF","GB-ENG","GB-ERW","GB-ERY","GB-ESS","GB-ESX","GB-FAL",
  "GB-FIF","GB-FLN","GB-GAT","GB-GLG","GB-GLS","GB-GRE","GB-GWN","GB-HAM","GB-HAV","GB-HCK",
  "GB-HEF","GB-HIL","GB-HLD","GB-HMF","GB-HNS","GB-HPL","GB-HRT","GB-HRW","GB-HRY","GB-IOS",
  "GB-IOW","GB-ISL","GB-IVC","GB-KEC","GB-KEN","GB-KHL","GB-KIR","GB-KTT","GB-KWL","GB-LAN",
  "GB-LBC","GB-LBH","GB-LCE","GB-LDS","GB-LEC","GB-LEW","GB-LIN","GB-LIV","GB-LND","GB-MAN",
  "GB-MDB","GB-MDW","GB-MLN","GB-MON","GB-MRT","GB-MRY","GB-MTY","GB-NAY","GB-NBL","GB-NEL",
  "GB-NET","GB-NFK","GB-NGM","GB-NIR","GB-NLK","GB-NSM","GB-NTH","GB-NTL","GB-NTT","GB-NTY",
  "GB-NWM","GB-NWP","GB-NYK","GB-OLD","GB-ORK","GB-OXF","GB-PEM","GB-PKN","GB-PLY","GB-POR",
  "GB-POW","GB-RCC","GB-RCH","GB-RCT","GB-RDB","GB-RDG","GB-RFW","GB-RIC","GB-ROT","GB-RUT",
  "GB-SAW","GB-SAY","GB-SCB","GB-SCT","GB-SFK","GB-SHF","GB-SHN","GB-SHR","GB-SKP","GB-SLF",
  "GB-SLK","GB-SND","GB-SOL","GB-SOM","GB-SOS","GB-SRY","GB-STE","GB-STG","GB-STH","GB-STN",
  "GB-STS","GB-STT","GB-STY","GB-SWA","GB-SWK","GB-TAM","GB-TOB","GB-TOF","GB-TRF","GB-TWH",
  "GB-VGL","GB-WAR","GB-WBK","GB-WDU","GB-WFT","GB-WGN","GB-WIL","GB-WKF","GB-WLN","GB-WLS",
  "GB-WLV","GB-WND","GB-WNM","GB-WOR","GB-WRL","GB-WSM","GB-WSX","GB-YOR","GB-ZET","GE-AB",
  "GE-AJ","GE-TB","GH-AA","GH-AF","GH-AH","GH-CP","GH-EP","GH-TV","GH-WP","GL-AV",
  "GL-KU","GL-QE","GL-QT","GL-SM","GM-B","GQ-AN","GQ-BN","GQ-BS","GQ-C","GQ-CS",
  "GQ-DJ","GQ-KN","GQ-LI","GQ-WN","GR-E","GR-G","GR-M","GT-01","GT-02","GT-03",
  "GT-04","GT-05","GT-06","GT-07","GT-08","GT-09","GT-10","GT-11","GT-12","GT-13",
  "GT-14","GT-15","GT-16","GT-17","GT-18","GT-19","GT-20","GT-21","GT-22","GT-BV",
  "GT-ES","GT-GU","GT-JU","GT-RE","GT-SO","GT-SR","GT-SU","GT-ZA","GUANICA","GUAYAMA-PUERTO-RICO",
  "GUAYANILLA","GUAYNABO","GUIPUZCOA","GURABO","GW-BS","HATILLO-PUERTO-RICO","HAUT-OGOOUE-PROVINCE-GABON","HN-AT","HN-CL","HN-CM",
  "HN-CP","HN-FM","HN-OC","HN-OL","HN-SB","HOLGUIN-PROVINCEPROPOSAL","HOLGUINPROPOSAL","HORMIGUEROSFLAG","HR-01","HR-02",
  "HR-03","HR-04","HR-05","HR-06","HR-07","HR-08","HR-09","HR-10","HR-11","HR-12",
  "HR-13","HR-14","HR-15","HR-16","HR-17","HR-18","HR-19","HR-20","HR-21","HU-BA",
  "HU-BC","HU-BE","HU-BK","HU-BU","HU-BZ","HU-CS","HU-DE","HU-DU","HU-EG","HU-ER",
  "HU-FE","HU-GS","HU-GY","HU-HB","HU-HE","HU-HV","HU-JN","HU-KE","HU-KM","HU-KV",
  "HU-MI","HU-NK","HU-NO","HU-NY","HU-PE","HU-PS","HU-SD","HU-SF","HU-SH","HU-SK",
  "HU-SN","HU-SO","HU-SS","HU-ST","HU-SZ","HU-TB","HU-TO","HU-VA","HU-VE","HU-VM",
  "HU-ZA","HU-ZE","HUMACAO","ID-AC","ID-BA","ID-BB","ID-BE","ID-BT","ID-GO","ID-JA",
  "ID-JB","ID-JI","ID-JK","ID-JT","ID-KB","ID-KI","ID-KR","ID-KS","ID-KT","ID-KU",
  "ID-LA","ID-MA","ID-MU","ID-NB","ID-NT","ID-PA","ID-PB","ID-RI","ID-SA","ID-SB",
  "ID-SG","ID-SN","ID-SR","ID-SS","ID-ST","ID-SU","ID-YO","IE-C","IE-CE","IE-CN",
  "IE-CO","IE-CW","IE-D","IE-DL","IE-G","IE-KE","IE-KK","IE-KY","IE-L","IE-LD",
  "IE-LH","IE-LK","IE-LM","IE-LS","IE-M","IE-MH","IE-MN","IE-MO","IE-OY","IE-RN",
  "IE-SO","IE-TA","IE-U","IE-WD","IE-WH","IE-WW","IE-WX","IL-JM","IL-TA","IN-AN",
  "IN-AP","IN-AR","IN-AS","IN-BR","IN-CH","IN-CT","IN-DH","IN-DL","IN-GA","IN-GJ",
  "IN-HP","IN-HR","IN-JH","IN-JK","IN-KA","IN-KL","IN-LA","IN-LD","IN-MH","IN-ML",
  "IN-MN","IN-MP","IN-MZ","IN-NL","IN-OR","IN-PB","IN-PY","IN-RJ","IN-SK","IN-TG",
  "IN-TN","IN-TR","IN-UP","IN-UT","IN-WB","IQ-AN","IQ-AR","IQ-BA","IQ-BB","IQ-BG",
  "IQ-DA","IQ-DI","IQ-DQ","IQ-KA","IQ-KI","IQ-KR","IQ-MA","IQ-MU","IQ-NA","IQ-NI",
  "IQ-QA","IQ-SD","IQ-SU","IQ-WA","IS-AKN","IS-AKU","IS-ARN","IS-ASA","IS-BLA","IS-BOG",
  "IS-BOL","IS-DAB","IS-DAV","IS-EYF","IS-FJD","IS-FLD","IS-FLR","IS-GAR","IS-GRN","IS-GRU",
  "IS-HAF","IS-HRU","IS-HUT","IS-HUV","IS-HVA","IS-HVE","IS-ISA","IS-KAL","IS-KJO","IS-KOP",
  "IS-MOS","IS-MYR","IS-RGE","IS-RHH","IS-RKN","IS-RKV","IS-SDN","IS-SDV","IS-SEL","IS-SKO",
  "IS-SKU","IS-SNF","IS-SOG","IS-SSS","IS-STR","IS-STY","IS-TAL","IS-THG","IS-VER","ISABELA",
  "IT-21","IT-23","IT-25","IT-32","IT-34","IT-36","IT-42","IT-45","IT-52","IT-55",
  "IT-57","IT-62","IT-65","IT-67","IT-72","IT-75","IT-77","IT-78","IT-82","IT-88",
  "IT-AG","IT-AL","IT-AN","IT-AP","IT-AQ","IT-AR","IT-AT","IT-AV","IT-BA","IT-BG",
  "IT-BI","IT-BL","IT-BN","IT-BO","IT-BR","IT-BS","IT-BT","IT-BZ","IT-CA","IT-CB",
  "IT-CE","IT-CH","IT-CL","IT-CN","IT-CO","IT-CR","IT-CT","IT-CZ","IT-EN","IT-FC",
  "IT-FE","IT-FG","IT-FI","IT-FM","IT-FR","IT-GE","IT-GO","IT-GR","IT-IM","IT-IS",
  "IT-KR","IT-LC","IT-LE","IT-LI","IT-LO","IT-LT","IT-LU","IT-MB","IT-MC","IT-ME",
  "IT-MI","IT-MN","IT-MO","IT-MS","IT-MT","IT-NA","IT-NO","IT-OR","IT-PA","IT-PC",
  "IT-PD","IT-PE","IT-PG","IT-PI","IT-PN","IT-PO","IT-PR","IT-PT","IT-PU","IT-PV",
  "IT-PZ","IT-RA","IT-RC","IT-RE","IT-RG","IT-RI","IT-RM","IT-RN","IT-RO","IT-SA",
  "IT-SI","IT-SO","IT-SP","IT-SR","IT-SS","IT-SV","IT-TA","IT-TE","IT-TN","IT-TO",
  "IT-TP","IT-TR","IT-TS","IT-TV","IT-UD","IT-VA","IT-VB","IT-VC","IT-VE","IT-VI",
  "IT-VR","IT-VT","IT-VV","JAYUYA","JP-01","JP-02","JP-03","JP-04","JP-05","JP-06",
  "JP-07","JP-08","JP-09","JP-10","JP-11","JP-12","JP-13","JP-14","JP-15","JP-16",
  "JP-17","JP-18","JP-19","JP-20","JP-21","JP-22","JP-23","JP-24","JP-25","JP-26",
  "JP-27","JP-28","JP-29","JP-30","JP-31","JP-32","JP-33","JP-34","JP-35","JP-36",
  "JP-37","JP-38","JP-39","JP-40","JP-41","JP-42","JP-43","JP-44","JP-45","JP-46",
  "JP-47","JUANA-DIAZ","JUBA","JUNCOS","KE-01","KE-02","KE-03","KE-04","KE-05","KE-06",
  "KE-07","KE-08","KE-09","KE-10","KE-11","KE-12","KE-13","KE-14","KE-15","KE-16",
  "KE-17","KE-18","KE-19","KE-20","KE-21","KE-22","KE-23","KE-24","KE-25","KE-26",
  "KE-27","KE-28","KE-29","KE-30","KE-31","KE-32","KE-33","KE-34","KE-35","KE-36",
  "KE-37","KE-38","KE-39","KE-40","KE-41","KE-42","KE-43","KE-44","KE-45","KE-46",
  "KE-47","KG-B","KG-C","KG-GB","KG-GO","KG-J","KG-N","KG-O","KG-T","KG-Y",
  "KH-1","KH-10","KH-11","KH-12","KH-13","KH-14","KH-15","KH-16","KH-17","KH-19",
  "KH-2","KH-20","KH-21","KH-22","KH-24","KH-25","KH-3","KH-4","KH-5","KH-6",
  "KH-7","KH-8","KH-9","KM-A","KM-G","KM-M","KN-N","KP-01","KR-11","KR-26",
  "KR-27","KR-28","KR-29","KR-30","KR-31","KR-41","KR-42","KR-43","KR-44","KR-45",
  "KR-46","KR-47","KR-48","KR-49","KR-50","KZ-AKM","KZ-AKT","KZ-ALA","KZ-ALM","KZ-AST",
  "KZ-ATY","KZ-KAR","KZ-KUS","KZ-KZY","KZ-MAN","KZ-PAV","KZ-SEV","KZ-SHY","KZ-VOS","KZ-YUZ",
  "KZ-ZAP","KZ-ZHA","LAJAS-PR","LAPURDI","LASMARIAS","LASPIEDRASFLAG","LES-DORIS-DE-SAINT-PIERRE-ET-MIQUELON","LI-01","LI-02","LI-03",
  "LI-04","LI-05","LI-06","LI-07","LI-08","LI-09","LI-10","LI-11","LK-1","LK-2",
  "LK-22","LK-3","LK-4","LK-5","LK-6","LK-7","LK-8","LK-9","LOIZA","LR-BG",
  "LR-BM","LR-CM","LR-GB","LR-GG","LR-GK","LR-GP","LR-LO","LR-MG","LR-MO","LR-MY",
  "LR-NI","LR-RG","LR-RI","LR-SI","LT-01","LT-02","LT-03","LT-04","LT-05","LT-06",
  "LT-07","LT-08","LT-09","LT-10","LT-11","LT-12","LT-13","LT-14","LT-15","LT-16",
  "LT-17","LT-18","LT-19","LT-20","LT-21","LT-22","LT-23","LT-24","LT-25","LT-26",
  "LT-27","LT-28","LT-29","LT-30","LT-31","LT-32","LT-33","LT-34","LT-35","LT-36",
  "LT-37","LT-38","LT-39","LT-40","LT-41","LT-42","LT-43","LT-44","LT-45","LT-46",
  "LT-47","LT-48","LT-49","LT-50","LT-51","LT-52","LT-53","LT-54","LT-55","LT-56",
  "LT-57","LT-58","LT-59","LT-60","LT-AL","LT-KL","LT-KU","LT-MR","LT-PN","LT-SA",
  "LT-TA","LT-TE","LT-UT","LT-VL","LU-CA","LU-CL","LU-DI","LU-EC","LU-ES","LU-GR",
  "LU-LU","LU-ME","LU-RD","LU-RM","LU-VD","LU-WI","LV-002","LV-007","LV-011","LV-015",
  "LV-016","LV-022","LV-026","LV-033","LV-041","LV-042","LV-047","LV-050","LV-052","LV-054",
  "LV-056","LV-058","LV-059","LV-062","LV-067","LV-068","LV-073","LV-077","LV-080","LV-087",
  "LV-088","LV-089","LV-091","LV-094","LV-097","LV-099","LV-101","LV-102","LV-106","LV-112",
  "LV-113","LV-50","LV-54","LV-DGV","LV-JEL","LV-JUR","LV-LPX","LV-REZ","LV-RIX","LV-VEN",
  "LY-BA","MA-01","MA-02","MA-06","MA-07","MA-08","MA-09","MA-10","MA-12","MA-BOD",
  "MA-BOM","MA-CAS","MA-ESI","MA-FES","MA-HAO","MA-HOC","MA-KES","MA-MAR","MA-OUA","MA-OUJ",
  "MA-RAB","MA-SAF","MA-SAL","MA-SIB","MA-TAT","MA-TNT","MANATI","MARICAO","MAUNABO-PUERTO-RICO","MAYAGUEZ",
  "MD-AN","MD-BA","MD-BD","MD-BS","MD-CA","MD-CL","MD-CM","MD-CR","MD-CS","MD-CU",
  "MD-DO","MD-DR","MD-DU","MD-ED","MD-FA","MD-FL","MD-GA","MD-GL","MD-HI","MD-IA",
  "MD-LE","MD-NI","MD-OC","MD-OR","MD-RE","MD-RI","MD-SD","MD-SI","MD-SN","MD-SO",
  "MD-ST","MD-SV","MD-TA","MD-TE","MD-UN","ME-01","ME-02","ME-03","ME-04","ME-05",
  "ME-06","ME-07","ME-08","ME-09","ME-10","ME-11","ME-12","ME-13","ME-14","ME-15",
  "ME-16","ME-17","ME-18","ME-19","ME-20","ME-21","ME-22","ME-24","MH-ALK","MH-EBO",
  "MH-KIL","MH-KWA","MH-MAJ","MH-NMK","MH-UJA","MH-UTI","MH-WTH","MIQUELON-LANGLADE","MK-101","MK-102",
  "MK-103","MK-104","MK-105","MK-106","MK-107","MK-108","MK-109","MK-201","MK-202","MK-203",
  "MK-204","MK-205","MK-206","MK-207","MK-208","MK-209","MK-210","MK-211","MK-301","MK-303",
  "MK-304","MK-307","MK-308","MK-310","MK-311","MK-312","MK-313","MK-401","MK-402","MK-403",
  "MK-404","MK-405","MK-406","MK-407","MK-408","MK-409","MK-410","MK-501","MK-502","MK-503",
  "MK-504","MK-505","MK-506","MK-507","MK-508","MK-509","MK-601","MK-602","MK-603","MK-604",
  "MK-605","MK-606","MK-607","MK-608","MK-609","MK-701","MK-702","MK-703","MK-704","MK-705",
  "MK-706","MK-801","MK-802","MK-803","MK-804","MK-805","MK-806","MK-807","MK-808","MK-809",
  "MK-810","MK-811","MK-812","MK-813","MK-814","MK-815","MK-816","MK-817","ML-BKO","MM-01",
  "MM-02","MM-03","MM-04","MM-05","MM-06","MM-07","MM-11","MM-12","MM-13","MM-14",
  "MM-15","MM-16","MM-17","MM-18","MN-035","MN-037","MN-039","MN-041","MN-043","MN-046",
  "MN-047","MN-049","MN-051","MN-053","MN-055","MN-057","MN-059","MN-061","MN-063","MN-064",
  "MN-065","MN-067","MN-069","MN-071","MN-073","MN-1","MOCA","MOYEN-OGOOUE-PROVINCE-GABON","MP-L","MP-MPM",
  "MT-01","MT-02","MT-03","MT-04","MT-05","MT-06","MT-07","MT-08","MT-09","MT-10",
  "MT-11","MT-12","MT-13","MT-14","MT-15","MT-16","MT-17","MT-18","MT-19","MT-20",
  "MT-21","MT-22","MT-23","MT-24","MT-25","MT-26","MT-27","MT-28","MT-29","MT-30",
  "MT-31","MT-32","MT-33","MT-34","MT-35","MT-36","MT-37","MT-38","MT-39","MT-40",
  "MT-41","MT-42","MT-43","MT-44","MT-45","MT-46","MT-47","MT-48","MT-49","MT-50",
  "MT-51","MT-52","MT-53","MT-54","MT-55","MT-56","MT-57","MT-58","MT-59","MT-60",
  "MT-61","MT-62","MT-63","MT-64","MT-65","MT-66","MT-67","MT-68","MU-PL","MU-RO",
  "MX-AGU","MX-BCN","MX-BCS","MX-CAM","MX-CHH","MX-CHP","MX-CMX","MX-COA","MX-COL","MX-DUR",
  "MX-GRO","MX-GUA","MX-HID","MX-JAL","MX-MEX","MX-MIC","MX-MOR","MX-NAY","MX-NLE","MX-OAX",
  "MX-PUE","MX-QUE","MX-ROO","MX-SIN","MX-SLP","MX-SON","MX-TAB","MX-TAM","MX-TLA","MX-VER",
  "MX-YUC","MX-ZAC","MY-01","MY-02","MY-03","MY-04","MY-05","MY-06","MY-07","MY-08",
  "MY-09","MY-10","MY-11","MY-12","MY-13","MY-14","MY-15","MY-16","MZ-I","MZ-L",
  "MZ-MPM","MZ-N","MZ-P","MZ-S","MZ-T","NARANJITO-PUERTO-RICO","NG-AB","NG-AD","NG-AK","NG-AN",
  "NG-BA","NG-BE","NG-BO","NG-BY","NG-CR","NG-DE","NG-EB","NG-ED","NG-EK","NG-EN",
  "NG-FC","NG-GO","NG-IM","NG-JI","NG-KD","NG-KE","NG-KN","NG-KO","NG-KT","NG-KW",
  "NG-LA","NG-NA","NG-NI","NG-OG","NG-ON","NG-OS","NG-OY","NG-PL","NG-RI","NG-SO",
  "NG-TA","NG-YO","NG-ZA","NGOUNIE-PROVINCE-GABON","NI-AN","NI-AS","NI-BO","NI-CA","NI-CI","NI-CO",
  "NI-ES","NI-GR","NI-JI","NI-LE","NI-MD","NI-MN","NI-MS","NI-MT","NI-NS","NI-RI",
  "NI-SJ","NL-AW","NL-BQ1","NL-BQ2","NL-BQ3","NL-CW","NL-DR","NL-FL","NL-FR","NL-GE",
  "NL-GR","NL-NB","NL-NH","NL-OV","NL-SX","NL-UT","NL-ZE","NL-ZH","NO-03","NO-11",
  "NO-15","NO-18","NO-30","NO-34","NO-38","NO-42","NO-46","NO-50","NO-54","NP-P1",
  "NP-P2","NP-P3","NP-P4","NP-P5","NP-P6","NP-P7","NYANGA-GABON","NYANGA-PROVINCE-GABON","NZ-AUK","NZ-CIT",
  "NZ-GIS","NZ-NSN","NZ-OTA","NZ-TAS","NZ-TKI","OFFICIAL-OF-ARROYO","OGOOUE-IVINDO-PROVINCE-GABON","OGOOUE-LOLO-PROVINCE-GABON","OGOOUE-MARITIME-PROVINCE-GABON","OROCOVIS-PUERTO-RICO",
  "PA-1","PA-10","PA-2","PA-3","PA-4","PA-5","PA-6","PA-7","PA-8","PA-9",
  "PA-EM","PA-KY","PA-NB","PA-NT","PALAU","PATILLAS","PE-AMA","PE-ANC","PE-APU","PE-ARE",
  "PE-AYA","PE-CAJ","PE-CAL","PE-CUS","PE-HUC","PE-HUV","PE-ICA","PE-JUN","PE-LAL","PE-LAM",
  "PE-LIM","PE-LMA","PE-LOR","PE-MDD","PE-MOQ","PE-PAS","PE-PIU","PE-PUN","PE-SAM","PE-TAC",
  "PE-TUM","PE-UCA","PETSERIMAA","PG-CPK","PG-CPM","PG-EBR","PG-EHG","PG-EPW","PG-ESW","PG-GPK",
  "PG-HLA","PG-JWK","PG-MBA","PG-MPL","PG-MPM","PG-MRL","PG-NCD","PG-NIK","PG-NPP","PG-NSB",
  "PG-SAN","PG-SHM","PG-WBK","PG-WHM","PG-WPD","PH-14","PH-15","PH-ABR","PH-AGN","PH-AGS",
  "PH-AKL","PH-ALB","PH-ANT","PH-APA","PH-AUR","PH-BAN","PH-BAS","PH-BEN","PH-BIL","PH-BOH",
  "PH-BTG","PH-BTN","PH-BUK","PH-BUL","PH-CAG","PH-CAM","PH-CAN","PH-CAP","PH-CAS","PH-CAT",
  "PH-CAV","PH-CEB","PH-COM","PH-DAO","PH-DAS","PH-DAV","PH-DIN","PH-DVO","PH-EAS","PH-GUI",
  "PH-IFU","PH-ILI","PH-ILN","PH-ILS","PH-ISA","PH-KAL","PH-LAG","PH-LAN","PH-LAS","PH-LEY",
  "PH-LUN","PH-MAD","PH-MAG","PH-MAS","PH-MDC","PH-MDR","PH-MOU","PH-MSC","PH-MSR","PH-NCO",
  "PH-NEC","PH-NER","PH-NSA","PH-NUE","PH-NUV","PH-PAM","PH-PAN","PH-PLW","PH-QUE","PH-QUI",
  "PH-RIZ","PH-ROM","PH-SAR","PH-SCO","PH-SIG","PH-SLE","PH-SLU","PH-SOR","PH-SUK","PH-SUN",
  "PH-SUR","PH-TAR","PH-TAW","PH-WSA","PH-ZAN","PH-ZAS","PH-ZMB","PH-ZSI","PINAR-DEL-RIO-PROVINCEPROPOSAL","PK-BA",
  "PK-GB","PK-JK","PK-KP","PK-PB","PK-SD","PK-TA","PL-02","PL-04","PL-06","PL-08",
  "PL-10","PL-12","PL-14","PL-16","PL-18","PL-20","PL-22","PL-24","PL-26","PL-28",
  "PL-30","PL-32","PT-01","PT-02","PT-03","PT-04","PT-05","PT-06","PT-07","PT-08",
  "PT-09","PT-10","PT-11","PT-12","PT-13","PT-14","PT-15","PT-16","PT-17","PT-18",
  "PT-20","PT-30","PW-002","PW-004","PW-010","PW-050","PW-100","PW-150","PW-212","PW-214",
  "PW-218","PW-222","PW-224","PW-226","PW-227","PW-228","PW-350","PW-370","PY-1","PY-10",
  "PY-11","PY-12","PY-13","PY-14","PY-15","PY-16","PY-19","PY-2","PY-3","PY-4",
  "PY-5","PY-6","PY-7","PY-8","PY-9","PY-ASU","QA-WA","QUEBRADILLAS","RINCON","RIO-GRANDE-PUERTO-RICO",
  "RO-AB","RO-AG","RO-AR","RO-B","RO-BC","RO-BH","RO-BN","RO-BR","RO-BT","RO-BV",
  "RO-BZ","RO-CJ","RO-CL","RO-CS","RO-CT","RO-CV","RO-DB","RO-DJ","RO-GJ","RO-GL",
  "RO-GR","RO-HD","RO-HR","RO-IF","RO-IL","RO-IS","RO-MH","RO-MM","RO-MS","RO-NT",
  "RO-OT","RO-PH","RO-SB","RO-SJ","RO-SM","RO-SV","RO-TL","RO-TM","RO-TR","RO-VL",
  "RO-VN","RO-VS","ROTUMA-1987-1988","RS-OO","RS-VO","RU-AD","RU-AL","RU-ALT","RU-AMU","RU-ARK",
  "RU-AST","RU-BA","RU-BEL","RU-BRY","RU-BU","RU-CE","RU-CHE","RU-CHU","RU-CU","RU-DA",
  "RU-IN","RU-IRK","RU-IVA","RU-KAM","RU-KB","RU-KC","RU-KDA","RU-KEM","RU-KGD","RU-KGN",
  "RU-KHA","RU-KHM","RU-KIR","RU-KK","RU-KL","RU-KLU","RU-KO","RU-KOS","RU-KR","RU-KRS",
  "RU-KYA","RU-LEN","RU-LIP","RU-MAG","RU-ME","RU-MO","RU-MUR","RU-NEN","RU-NGR","RU-NIZ",
  "RU-NVS","RU-OMS","RU-ORE","RU-PER","RU-PNZ","RU-PRI","RU-PSK","RU-ROS","RU-RYA","RU-SA",
  "RU-SAK","RU-SAM","RU-SAR","RU-SE","RU-SMO","RU-SPE","RU-STA","RU-SVE","RU-TA","RU-TAM",
  "RU-TOM","RU-TUL","RU-TVE","RU-TY","RU-TYU","RU-UD","RU-ULY","RU-VGG","RU-VLA","RU-VLG",
  "RU-VOR","RU-YAN","RU-YAR","RU-YEV","RU-ZAB","RUWENG","SABANAGRANDE","SAINT-PIERRE-AND-MIQUELON","SALINAS-PUERTO-RICO","SAN-JUAN-PUERTO-RICO",
  "SAN-LORENZO","SAN-SEBASTIAN-PUERTO-RICO","SANKURU-PROVINCE","SANTA-ISABEL","SB-CE","SB-CH","SB-CT","SB-GU","SB-IS","SB-MK",
  "SB-ML","SB-RB","SB-TE","SB-WE","SC-01","SC-02","SC-03","SC-04","SC-05","SC-06",
  "SC-07","SC-08","SC-09","SC-10","SC-11","SC-12","SC-13","SC-14","SC-17","SC-18",
  "SC-19","SC-20","SC-21","SC-22","SC-23","SC-24","SC-25","SC-26","SC-27","SD-DC",
  "SD-DE","SD-DN","SD-DS","SD-DW","SD-GD","SD-GK","SD-GZ","SD-KA","SD-KH","SD-KN",
  "SD-KS","SD-NB","SD-NO","SD-NR","SD-NW","SD-RS","SD-SI","SE-AB","SE-AC","SE-BD",
  "SE-C","SE-D","SE-E","SE-F","SE-G","SE-H","SE-I","SE-K","SE-M","SE-N",
  "SE-O","SE-S","SE-T","SE-U","SE-W","SE-X","SE-Y","SE-Z","SG-02","SG-03",
  "SG-04","SG-05","SH-AC","SH-HL","SH-TA","SI-001","SI-002","SI-003","SI-004","SI-005",
  "SI-006","SI-007","SI-008","SI-009","SI-010","SI-011","SI-012","SI-013","SI-014","SI-015",
  "SI-016","SI-017","SI-018","SI-019","SI-020","SI-021","SI-022","SI-023","SI-024","SI-025",
  "SI-026","SI-027","SI-028","SI-029","SI-030","SI-031","SI-032","SI-033","SI-034","SI-035",
  "SI-036","SI-037","SI-038","SI-039","SI-040","SI-041","SI-042","SI-043","SI-044","SI-045",
  "SI-046","SI-047","SI-048","SI-049","SI-050","SI-051","SI-052","SI-053","SI-054","SI-055",
  "SI-056","SI-057","SI-058","SI-059","SI-060","SI-061","SI-062","SI-063","SI-064","SI-065",
  "SI-066","SI-067","SI-068","SI-069","SI-070","SI-071","SI-072","SI-073","SI-074","SI-075",
  "SI-076","SI-077","SI-078","SI-079","SI-080","SI-081","SI-082","SI-083","SI-084","SI-085",
  "SI-086","SI-087","SI-088","SI-089","SI-090","SI-091","SI-092","SI-093","SI-094","SI-095",
  "SI-096","SI-097","SI-098","SI-099","SI-100","SI-101","SI-102","SI-103","SI-104","SI-105",
  "SI-106","SI-107","SI-108","SI-109","SI-110","SI-111","SI-112","SI-113","SI-114","SI-115",
  "SI-116","SI-117","SI-118","SI-119","SI-120","SI-121","SI-122","SI-123","SI-124","SI-125",
  "SI-126","SI-127","SI-128","SI-129","SI-130","SI-131","SI-132","SI-133","SI-134","SI-135",
  "SI-136","SI-137","SI-138","SI-139","SI-140","SI-141","SI-142","SI-143","SI-144","SI-146",
  "SI-147","SI-148","SI-149","SI-150","SI-151","SI-152","SI-153","SI-154","SI-155","SI-156",
  "SI-157","SI-158","SI-159","SI-160","SI-161","SI-162","SI-163","SI-164","SI-165","SI-166",
  "SI-167","SI-168","SI-169","SI-170","SI-171","SI-172","SI-173","SI-174","SI-175","SI-176",
  "SI-177","SI-178","SI-179","SI-180","SI-181","SI-182","SI-183","SI-184","SI-185","SI-186",
  "SI-187","SI-188","SI-189","SI-190","SI-191","SI-192","SI-193","SI-194","SI-195","SI-196",
  "SI-197","SI-198","SI-199","SI-200","SI-201","SI-202","SI-203","SI-204","SI-205","SI-206",
  "SI-207","SI-208","SI-209","SI-210","SI-211","SI-212","SI-213","SI-48","SK-BC","SK-BL",
  "SK-KI","SK-NI","SK-PV","SK-TA","SK-TC","SK-ZI","SM-01","SM-02","SM-03","SM-04",
  "SM-05","SM-06","SM-07","SM-08","SM-09","SN-DK","SO-BK","SO-BN","SO-BR","SO-BY",
  "SO-GE","SO-SH","SS-BN","SS-BW","SS-EC","SS-EE","SS-EW","SS-JG","SS-LK","SS-NU",
  "SS-UY","SS-WR","ST-01","ST-P","SV-AH","SV-CA","SV-CH","SV-CU","SV-LI","SV-MO",
  "SV-PA","SV-SA","SV-SM","SV-SO","SV-SS","SV-SV","SV-UN","SV-US","TH-10","TH-11",
  "TH-12","TH-13","TH-14","TH-15","TH-16","TH-17","TH-18","TH-19","TH-20","TH-21",
  "TH-22","TH-23","TH-24","TH-25","TH-26","TH-27","TH-30","TH-31","TH-32","TH-33",
  "TH-34","TH-35","TH-36","TH-37","TH-38","TH-39","TH-40","TH-41","TH-42","TH-43",
  "TH-44","TH-45","TH-46","TH-47","TH-48","TH-49","TH-50","TH-51","TH-52","TH-53",
  "TH-54","TH-55","TH-56","TH-57","TH-58","TH-60","TH-61","TH-62","TH-63","TH-64",
  "TH-65","TH-66","TH-67","TH-70","TH-71","TH-72","TH-73","TH-74","TH-75","TH-76",
  "TH-77","TH-80","TH-81","TH-82","TH-83","TH-84","TH-85","TH-86","TH-90","TH-91",
  "TH-92","TH-93","TH-94","TH-95","TH-96","TH-S","TJ-DU","TL-AL","TL-AN","TL-BA",
  "TL-BO","TL-CO","TL-DI","TL-ER","TL-LA","TL-LI","TL-MF","TL-MT","TL-OE","TL-VI",
  "TN-73","TN-81","TOA-ALTA","TOA-BAJA-PUERTO-RICO","TR-34","TR-48","TR-54","TRUJILLO-ALTO-PUERTO-RICO","TT-ARI","TT-CHA",
  "TT-CTT","TT-DMN","TT-MRC","TT-PRT","TT-TUP","TW-CHA","TW-CYI","TW-CYQ","TW-HSQ","TW-HSZ",
  "TW-HUA","TW-ILA","TW-KEE","TW-KHH","TW-KIN","TW-LIE","TW-MIA","TW-NAN","TW-NWT","TW-PEN",
  "TW-PIF","TW-TAO","TW-TNN","TW-TPE","TW-TTT","TW-TXG","TW-YUN","UA-05","UA-07","UA-09",
  "UA-12","UA-14","UA-18","UA-21","UA-23","UA-26","UA-30","UA-32","UA-35","UA-40",
  "UA-43","UA-46","UA-48","UA-51","UA-53","UA-56","UA-59","UA-61","UA-63","UA-65",
  "UA-68","UA-71","UA-74","UA-77","UG-206","UM-67","UM-79","US-AK","US-AL","US-AR",
  "US-AS","US-AZ","US-CA","US-CO","US-CT","US-DC","US-DE","US-FL","US-GA","US-GU",
  "US-HI","US-IA","US-ID","US-IL","US-IN","US-KS","US-KY","US-LA","US-MA","US-MD",
  "US-ME","US-MI","US-MN","US-MO","US-MP","US-MS","US-MT","US-NC","US-ND","US-NE",
  "US-NH","US-NJ","US-NM","US-NV","US-NY","US-OH","US-OK","US-OR","US-PA","US-PR",
  "US-RI","US-SC","US-SD","US-TN","US-TX","US-UM","US-UT","US-VA","US-VI","US-VT",
  "US-WA","US-WI","US-WV","US-WY","UTUADOFLAG","UY-AR","UY-CA","UY-CL","UY-CO","UY-DU",
  "UY-FD","UY-FS","UY-LA","UY-MA","UY-MO","UY-PA","UY-RN","UY-RO","UY-RV","UY-SA",
  "UY-SJ","UY-SO","UY-TA","UY-TT","UZ-QR","UZ-TK","VANNES-SEMAINE-DU-GOLFE-2015-2","VE-B","VE-C","VE-D",
  "VE-E","VE-F","VE-G","VE-H","VE-I","VE-J","VE-K","VE-L","VE-M","VE-N",
  "VE-O","VE-P","VE-R","VE-S","VE-T","VE-U","VE-V","VE-W","VE-X","VE-Y",
  "VE-Z","VEGA-ALTA","VEGA-BAJA","VIEQUES","VILLALBA","VN-HN","VU-MAP","VU-PAM","VU-SAM","VU-SEE",
  "VU-TAE","VU-TOB","WF-AL","WF-SG","WF-UV","WOLEU-NTEM-PROVINCE-GABON","YABUCOA","YAUCO-THROUGH-2004","YE-AD","YE-DH",
  "YE-HD","YE-LA","ZA-EC","ZA-FS","ZA-GP","ZA-KZN","ZA-LP","ZA-MP","ZA-NC","ZA-NW",
  "ZA-WC","ZM-01","ZM-02","ZM-03","ZM-04","ZM-05","ZM-06","ZM-07","ZM-08","ZM-09",
  "ZM-10","ZUBEROA","ZW-BU","ZW-HA",
]);

const CDN_BASE = "https://cdn.jsdelivr.net/gh/amckenna41/iso3166-flags@main/iso3166-2-flags";

/**
 * Returns a CDN URL for the flag of the given ISO 3166-2 subdivision code,
 * or null if no flag is available in the index.
 */
export function subdivisionFlagCdnUrl(isoCode: string): string | null {
  const key = isoCode.toUpperCase().replace(/_/g, "-");
  if (!FLAG_CODES.has(key)) return null;
  const cc = key.split("-")[0]!;
  const ext = NON_SVG_EXT[key] ?? "svg";
  return `${CDN_BASE}/${cc}/${key}.${ext}`;
}

export function hasSubdivisionFlag(isoCode: string): boolean {
  return FLAG_CODES.has(isoCode.toUpperCase().replace(/_/g, "-"));
}