#!/usr/bin/env python3
"""Country Personas — owner-review document and portrait checks (playbook step 12).

Reads the draft model, the Grand Index, the draft portraits and the input snapshot, then:

  1. checks every portrait claim against the data: a group claim must match the sign of the
     group-vs-world difference; a type claim must match the sign of the type-vs-group
     difference (or, for a superlative, the type-vs-world difference);
  2. lints names, lines and portraits: no country, continent or regional name, no banned
     judgement word, no ISO-code-looking token;
  3. writes docs/country-personas/PERSONAS_DRAFT.md for the owner to review.

Standard library only:  python3 scripts/country-personas/review.py
Exits 1 when a check fails, so it can later become the gate for the shipped portraits.
"""
from __future__ import annotations

import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MODEL = json.loads((ROOT / "scripts/data/country-personas-model.draft.json").read_text())
GRAND = json.loads((ROOT / "scripts/data/country-personas-grand-index.json").read_text())
PORTRAITS = json.loads((ROOT / "scripts/data/country-persona-portraits.draft.json").read_text())
SNAP = json.loads((ROOT / "scripts/data/country-persona-inputs.json").read_text())
OUT = ROOT / "docs/country-personas/PERSONAS_DRAFT.md"
NAMES = SNAP["names"]

BANNED = ["poor", "developing", "developed", "third world", "backward", "failed", "failing", "rogue", "elite",
          "primitive", "civilised", "civilized", "corrupt", "dictatorship", "fragile", "western", "eastern",
          "northern", "southern", "christian", "muslim", "islamic", "catholic", "hindu", "buddhist", "arab",
          "african", "asian", "european", "latin", "anglo", "slavic", "nordic", "gulf", "caribbean", "pacific",
          "island", "tribal", "emerging"]
PLACE_WORDS = ["africa", "asia", "europe", "america", "oceania", "middle east", "balkan", "sahel"] + [n.lower() for n in NAMES.values()]


def values(var: str, codes: list[str]) -> list[float]:
    out = []
    for c in codes:
        v = (SNAP["values"][c].get(var) or {}).get("v")
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            out.append(float(v))
    return out


def scale(xs: list[float], transform: bool) -> list[float]:
    return [math.asinh(x) for x in xs] if transform else xs


def diff_sign(var: str, members: list[str], reference: list[str]) -> tuple[float, int]:
    ref, mem = values(var, reference), values(var, members)
    if len(ref) < 5 or not mem:
        return float("nan"), len(mem)
    mean = sum(ref) / len(ref)
    skewish = min(ref) >= 0 and (sum((x - mean) ** 3 for x in ref) / len(ref)) / (
        (sum((x - mean) ** 2 for x in ref) / len(ref)) ** 1.5 or 1) > 2
    ref_s, mem_s = scale(ref, skewish), scale(mem, skewish)
    sd = math.sqrt(sum((x - sum(ref_s) / len(ref_s)) ** 2 for x in ref_s) / (len(ref_s) - 1)) or 1
    return (sum(mem_s) / len(mem_s) - sum(ref_s) / len(ref_s)) / sd, len(mem)


assigned = [c for c, a in MODEL["assignments"].items() if a["status"] != "unclassified"]
problems: list[str] = []
checked = 0
for kind in ("groups", "types"):
    for code, p in PORTRAITS[kind].items():
        members = GRAND[kind][code]["members"]
        parent = GRAND["groups"][code[0]]["members"] if kind == "types" else assigned
        for var, sign in p["claims"]:
            z, n = diff_sign(var, members, parent)
            if kind == "types" and (math.isnan(z) or (z > 0) != (sign == "+")):
                z, n = diff_sign(var, members, assigned)  # a superlative is judged against the world
            checked += 1
            if math.isnan(z) or n == 0 or (z > 0) != (sign == "+"):
                problems.append(f"{code}: claim {var} {sign} but the data says z = {z:+.2f} (n = {n})")
        text = " ".join([p["name"], p["line"], p["portrait"]]).lower()
        for w in BANNED:
            if re.search(rf"\b{re.escape(w)}\b", text):
                problems.append(f"{code}: banned term '{w}'")
        for w in PLACE_WORDS:
            if re.search(rf"\b{re.escape(w)}\b", " ".join([p["name"], p["line"]]).lower()):
                problems.append(f"{code}: place name '{w}' in a name or line")
        if re.search(r"\b[A-Z]{2}\b", p["name"] + " " + p["line"] + " " + p["portrait"].replace("GDP", "").replace("OPEC", "").replace("OECD", "").replace("RSF", "")):
            problems.append(f"{code}: looks like an ISO code in the text")
        if len(p["portrait"].split()) > 120:
            problems.append(f"{code}: portrait is {len(p['portrait'].split())} words (limit 120)")

# ── Review document ──────────────────────────────────────────────────────────
N = lambda cs: ", ".join(NAMES[c] for c in cs)  # noqa: E731
lines = [
    "# Country Personas — draft for owner review",
    "",
    "Auto-generated by `scripts/country-personas/review.py` from the draft model, the Grand Index and",
    "`scripts/data/country-persona-portraits.draft.json`. **Nothing here is in the app.** Edit the",
    "portraits JSON (not this file) and re-run the script.",
    "",
    f"Portrait checks: {checked} claims checked against the data, lint run on every name, line and portrait — "
    + ("**all pass**." if not problems else f"**{len(problems)} problem(s)**:"),
    "",
    *[f"- {p}" for p in problems],
    "",
    "How to read this:",
    "",
    "- **Letters are labels, not ranks.** Groups are ordered along the main axis of the family-tree",
    "  map (development), for readability only.",
    "- **Figures are averages across countries.** Each country counts once, whatever its population.",
    "- **\"Borderline\" members** sit close to another group (assignment confidence < 0.1). In the app",
    "  they would say \"sits between A and B\", and they would be left out of quiz decks.",
    "- **Key features** are the rows where the persona differs most from the world (|z|), drawn from",
    "  at least three themes. They exclude geography, geographic organisations and the app's own",
    "  catalogue counts.",
    "",
]
for L in sorted(PORTRAITS["groups"]):
    p, gi = PORTRAITS["groups"][L], GRAND["groups"][L]
    border = [c for c in gi["members"] if MODEL["assignments"][c].get("confidence", 1) < 0.1]
    lines += [f"## {L} — {p['name']}", "", f"*{p['line']}*", "", p["portrait"], "",
              f"**{gi['size']} countries · {gi['worldPopulationShare']:.1%} of world population** · "
              + ", ".join(f"{k} {v}" for k, v in gi["continents"].items()) + f" · typical: {N(gi['typicalMembers'][:4])}", "",
              "| Key feature | Persona | World | Index | z |", "|---|---|---|---|---|"]
    for r in gi["keyFeatures"]:
        fmt = (lambda x: f"{x:,.0f}") if abs(r["referenceMean"]) >= 100 else (lambda x: f"{x:.2f}")
        lines.append(f"| {r['label']} | {fmt(r['mean'])} | {fmt(r['referenceMean'])} | {r.get('index', '—')} | {r['z']:+.2f} |")
    lines += ["", "| Type | Name | Line | Members |", "|---|---|---|---|"]
    for T in sorted(t for t in PORTRAITS["types"] if t.startswith(L)):
        tp, ti = PORTRAITS["types"][T], GRAND["types"][T]
        mem = ", ".join(f"{NAMES[c]}{' (borderline)' if c in border else ''}" for c in ti["members"])
        lines.append(f"| **{T}** ({ti['size']}) | {tp['name']} | {tp['line']} | {mem} |")
    lines += [""]
    for T in sorted(t for t in PORTRAITS["types"] if t.startswith(L)):
        lines += [f"**{T} — {PORTRAITS['types'][T]['name']}.** {PORTRAITS['types'][T]['portrait']}", ""]
unc = [c for c, a in MODEL["assignments"].items() if a["status"] == "unclassified"]
lines += ["## Unclassified", "", f"{N(unc)}: not enough comparable data (fewer than half of the four domains observed).", "",
          "## Decisions for the owner", "",
          "1. **Five groups and twelve types**, not the 6–8 groups and 18–24 types the playbook targeted.",
          "   Finer splits were not stable (ledger D2–D4).",
          "2. **Names.** Approve, reword, or reject each one. The most sensitive is **E12**, the only type",
          "   distinguished mainly by governance scores; its name cites the scores, never a verdict.",
          "3. **Group D stays whole.** No split of its 42 countries was stable, so it has one type, D10.",
          "4. **Three acceptance criteria fail** (ledger D7): reweighting at ±27%, leave-one-variable-out, and the",
          "   permutation-null share. Accept them with the stored confidence scores, or ask for another design.",
          ""]
OUT.write_text("\n".join(lines) + "\n")
print(f"{checked} claims checked; {len(problems)} problem(s)")
for p in problems:
    print("  ✗", p)
sys.exit(1 if problems else 0)
