import { useMemo } from "react";
import { AutoFitName } from "./AutoFitName";
import { subdivisionFlagUrl } from "../api/subdivisions";
import { subdivisionCapital } from "../lib/cityRoles";
import { distinctCapitalFlagPath } from "../lib/capitalInfo";
import { DISPUTED_TERRITORY_HIERARCHY } from "../lib/disputedSubdivisions";
import { normalizeForSearch } from "../lib/searchNormalize";
import { NATIONAL_CITIES } from "../data/cities";
import { NATIONAL_CAPITAL_FLAGS } from "../data/nationalCapitalFlags";
import { NATIONAL_CAPITAL_SUBDIVISION } from "../data/nationalCapitalLocations";
import type { SubdivisionMeta } from "../types/subdivision";

/**
 * "Hierarchy chart" tab — an interactive org chart of a country's structure:
 *
 *   nation (root)
 *     └─ each subdivision TYPE (States, Federal Territory, Autonomous Region, …)
 *          └─ every subdivision of that type
 *               └─ its capital city/cities (a capital is a leaf)
 *
 * National capitals are surfaced WITHOUT ever duplicating an entity that already
 * exists in the tree (sourced from NATIONAL_CITIES, like the map overlay's ★), and
 * always at the CITY-LEAF level, level with every other capital city:
 *  - A capital that IS a subdivision (a city-territory whose own leaf is
 *    tautological — Kuala Lumpur, Putrajaya, Tokyo) → its subdivision node is
 *    MARKED "★ <role>". No second node.
 *  - A capital that is a subdivision's capital CITY (Canberra ≡ ACT, Cape Town ≡
 *    Western Cape) → that city leaf is MARKED. No second node.
 *  - A capital that heads no subdivision but sits INSIDE one (Ottawa → Ontario,
 *    Pretoria → Gauteng, Amsterdam → North Holland) → it is added as an extra
 *    capital LEAF under that subdivision, beside the subdivision's own capital
 *    (Ontario → Toronto + Ottawa), with its own sourced municipal flag. The
 *    containing subdivision is decided by point-in-polygon (NATIONAL_CAPITAL_
 *    SUBDIVISION, generated by scripts/build-national-capital-locations.mjs).
 *  - Only a capital we cannot place inside any subdivision falls back to a small
 *    standalone "National capital" group.
 * A multi-capital nation handles each seat independently (South Africa: Cape Town
 * + Bloemfontein leaves marked, Pretoria added as a leaf under Gauteng).
 *
 * The subdivisions are grouped by their `typeLabel`, and each type appears as its
 * own label node laddering up to the national flag, with its subdivision flags
 * laddering up to it (mirroring the "By type" grouping of the flag grid, incl. its
 * tier order: primary subdivisions, then dependent/external territories, then
 * disputed).
 *
 * The chart shows the FULL administrative tree, not just the flagged parts: every
 * subdivision appears, and every subdivision with a known capital gets a city
 * leaf — whether or not a flag exists for it. Where a flag IS bundled it renders
 * (national → country.flagSvg, subdivision → subdivisionFlagUrl, city → the
 * name-confirmed capital flag), and where none exists a neutral "—" placeholder
 * is shown. Nothing is fabricated: the capital NAME comes from the same
 * authoritative source as the map ★ (`subdivisionCapital`), and a subdivision no
 * source has a capital for simply gets no leaf.
 *
 * Clicking any flag node updates the parent selection (map highlight + widget):
 *  - root  → the country itself (clears the subdivision drill-down)
 *  - branch→ that subdivision
 *  - leaf  → that subdivision + its capital
 * The type labels are structural, not selectable entities, so they are not
 * interactive.
 */

// External/dependent territory type labels — kept in sync with the flag grid's
// DEPENDENCY_TYPES so the hierarchy's type order matches the grid's "By type"
// tier order (primary subdivisions first, dependencies next, disputed last).
const DEPENDENCY_TYPES: ReadonlySet<string> = new Set([
  "Crown Dependency",
  "Overseas Territory",
  "Overseas Collectivity",
  "Sui generis collectivity",
  "Autonomous Territory",
  "Special Administrative Region",
  "Constituent Country",
  "Associated State",
  "External Territory",
  "Unincorporated Territory",
]);

function groupTier(typeLabel: string, allDisputed: boolean): number {
  if (allDisputed) return 2;
  if (DEPENDENCY_TYPES.has(typeLabel)) return 1;
  return 0;
}

/** Plural form of a singular type label for the group heading. */
function pluralizeType(label: string): string {
  if (/s$/i.test(label)) return label;
  if (/[^aeiou]y$/i.test(label)) return label.replace(/y$/i, "ies");
  return `${label}s`;
}

type Props = {
  divisions: SubdivisionMeta[];
  countryName: string;
  /** ISO 3166-1 alpha-2 of the country — used to source its national capital(s). */
  countryCode: string;
  countryFlagUrl: string | null;
  /** Selected subdivision code (if any). */
  selectedCode: string | null;
  /** True when the "View capital" drill-down is open for the selected code. */
  capitalActive: boolean;
  /** Name of the selected standalone national capital (if any) — for its active
   *  highlight; these capitals head no subdivision so `selectedCode` can't mark them. */
  activeNationalCapital?: string | null;
  baseUrl: string;
  onSelectCountry: () => void;
  onSelectSubdivision: (code: string) => void;
  onSelectCapital: (code: string) => void;
  /** A national capital that heads no subdivision (Ottawa, Pretoria …) — selecting
   *  it populates its own panel in the widget above. */
  onSelectNationalCapital: (cap: { name: string; note: string | null; flagPath: string | null }) => void;
};

export function SubdivisionHierarchyChart({
  divisions,
  countryName,
  countryCode,
  countryFlagUrl,
  selectedCode,
  capitalActive,
  activeNationalCapital,
  baseUrl,
  onSelectCountry,
  onSelectSubdivision,
  onSelectCapital,
  onSelectNationalCapital,
}: Props) {
  const { nodes, standaloneCaps } = useMemo(() => {
    const visibleDivs = divisions.filter(
      (d) => !(d.code in DISPUTED_TERRITORY_HIERARCHY),
    );

    // A capital city under a subdivision. `kind` decides its click target: a
    // subdivision's own capital opens that subdivision's "View capital" panel; a
    // national capital placed here opens the national-capital panel. `role` is set
    // (coral badge) when the leaf is a national capital.
    type Leaf = {
      key: string;
      kind: "sub" | "national";
      name: string;
      flagPath: string | null;
      role: string | null;
      note: string | null;
    };

    const nodes = visibleDivs
      .map((d) => {
        const capital = subdivisionCapital(d.code);
        // The capital's DISTINCT flag (null when it merely duplicates the
        // subdivision's own flag — a city-territory like Canberra ≡ ACT, or a
        // shared coat-of-arms like Brasília ≡ Distrito Federal). Single source of
        // truth shared with the capital panel and the City-flags grid.
        const distinctFlag = capital
          ? distinctCapitalFlagPath(d.code, capital.name)
          : null;
        // Same name as its subdivision (São Paulo state → São Paulo city; Kuala
        // Lumpur → Kuala Lumpur).
        const sameName =
          capital != null &&
          normalizeForSearch(capital.name) === normalizeForSearch(d.name);
        // Show the subdivision's own capital as a leaf when it has a DISTINCT flag
        // (São Paulo city's red-cross flag), OR it is a distinctly-named place
        // (Canberra, Brasília, Victoria). Suppress it only when tautological AND
        // flagless: the subdivision IS that one city (Kuala Lumpur, Foggia, Zürich).
        const showCity = capital != null && (distinctFlag != null || !sameName);
        const leaves: Leaf[] = [];
        if (showCity) {
          leaves.push({
            key: `sub:${d.code}`,
            kind: "sub",
            name: capital!.name,
            flagPath: distinctFlag,
            role: null,
            note: null,
          });
        }
        return {
          div: d,
          subFlag: subdivisionFlagUrl(d.code),
          // Set (coral badge) when the subdivision node itself IS the national
          // capital — a city-territory whose own leaf is tautological (Kuala
          // Lumpur, Tokyo). Never a duplicate node.
          subCapitalRole: null as string | null,
          leaves,
        };
      })
      .sort((a, b) => a.div.name.localeCompare(b.div.name, "en"));

    const byCode = new Map(nodes.map((n) => [n.div.code, n]));

    // Attribute each national capital to the entity that ALREADY represents it,
    // else to the subdivision that geographically CONTAINS it (as an extra leaf),
    // and only if neither applies does it fall back to a standalone node.
    const nationalCaps = NATIONAL_CITIES[countryCode]?.capitals ?? [];
    const standaloneCaps: { name: string; note: string | null }[] = [];
    for (const cap of nationalCaps) {
      const k = normalizeForSearch(cap.name);
      // Sourced role note for a multi-capital nation (e.g. "Constitutional
      // capital"); a single capital just reads "National capital".
      const role = cap.note ?? "National capital";
      // (a) A shown subdivision-capital leaf IS this capital (Canberra ≡ ACT,
      //     Cape Town ≡ Western Cape) — mark that leaf in place.
      let marked = false;
      for (const n of nodes) {
        const leaf = n.leaves.find((l) => l.kind === "sub" && normalizeForSearch(l.name) === k);
        if (leaf) {
          leaf.role = role;
          leaf.note = cap.note ?? null;
          marked = true;
          break;
        }
      }
      if (marked) continue;
      // (b) A subdivision IS this capital — a city-territory whose own leaf is
      //     tautological and suppressed (Kuala Lumpur, Putrajaya, Tokyo).
      const cityTerritory = nodes.find((n) => normalizeForSearch(n.div.name) === k);
      if (cityTerritory) {
        cityTerritory.subCapitalRole = role;
        continue;
      }
      // (c) A capital that heads no subdivision but sits inside one (Ottawa →
      //     Ontario, Pretoria → Gauteng) — add it as an extra capital leaf under
      //     the containing subdivision, level with that subdivision's own capital.
      const host = byCode.get(NATIONAL_CAPITAL_SUBDIVISION[`${countryCode}|${cap.name}`] ?? "");
      if (host) {
        host.leaves.push({
          key: `nat:${cap.name}`,
          kind: "national",
          name: cap.name,
          flagPath: NATIONAL_CAPITAL_FLAGS[`${countryCode}|${k}`] ?? null,
          role,
          note: cap.note ?? null,
        });
        continue;
      }
      // (d) Could not place it inside any subdivision — a standalone fallback.
      standaloneCaps.push({ name: cap.name, note: cap.note ?? null });
    }

    return { nodes, standaloneCaps };
  }, [divisions, countryCode]);

  // Group the subdivisions by type, ordered by the same tier rule as the grid.
  const groups = useMemo(() => {
    const byType = new Map<string, typeof nodes>();
    for (const n of nodes) {
      const arr = byType.get(n.div.typeLabel) ?? [];
      arr.push(n);
      byType.set(n.div.typeLabel, arr);
    }
    return [...byType.entries()]
      .map(([typeLabel, items]) => ({
        typeLabel,
        items,
        allDisputed: items.every((i) => i.div.isDisputed),
      }))
      .sort((a, b) => {
        const ta = groupTier(a.typeLabel, a.allDisputed);
        const tb = groupTier(b.typeLabel, b.allDisputed);
        if (ta !== tb) return ta - tb;
        if (b.items.length !== a.items.length) return b.items.length - a.items.length;
        return a.typeLabel.localeCompare(b.typeLabel, "en");
      });
  }, [nodes]);

  if (nodes.length === 0) {
    return (
      <p className="flag-grid__no-match">
        No sub-national divisions are available for {countryName} yet.
      </p>
    );
  }

  const rootActive = !selectedCode;

  return (
    <div className="hierarchy" role="tree" aria-label={`${countryName} flag hierarchy`}>
      <div className="hierarchy__inner">
        <div className="hierarchy__root">
          <button
            type="button"
            className={`hierarchy__node hierarchy__node--national${rootActive ? " hierarchy__node--active" : ""}`}
            onClick={onSelectCountry}
            aria-pressed={rootActive}
            aria-label={`Select ${countryName}`}
          >
            <span className="hierarchy__thumb">
              {countryFlagUrl ? (
                <img
                  src={countryFlagUrl}
                  alt=""
                  loading="lazy"
                  draggable={false}
                  className="hierarchy__thumb-img"
                />
              ) : (
                <span className="flag-grid__thumb-empty" aria-hidden="true">—</span>
              )}
            </span>
            <AutoFitName className="hierarchy__name" text={countryName} />
            <span className="hierarchy__tier">Nation</span>
          </button>
        </div>

        <div className="hierarchy__branches">
          {standaloneCaps.length > 0 && (
            <div className="hierarchy__group" role="group" aria-label="National capital">
              <div className="hierarchy__group-label">
                <span className="hierarchy__group-type">National capital</span>
                {standaloneCaps.length > 1 && (
                  <span className="hierarchy__group-count">{standaloneCaps.length}</span>
                )}
              </div>

              <div className="hierarchy__subrow">
                {standaloneCaps.map((cap) => {
                  // A national capital that heads no subdivision (Ottawa, Belmopan)
                  // — its own sourced municipal flag if one is bundled, else "—".
                  const flagPath =
                    NATIONAL_CAPITAL_FLAGS[`${countryCode}|${normalizeForSearch(cap.name)}`] ?? null;
                  const active = activeNationalCapital === cap.name;
                  return (
                    <div key={cap.name} className="hierarchy__col">
                      <button
                        type="button"
                        className={`hierarchy__node hierarchy__node--capital${active ? " hierarchy__node--active" : ""}`}
                        onClick={() => onSelectNationalCapital({ name: cap.name, note: cap.note, flagPath })}
                        aria-pressed={active}
                        aria-label={`Select ${cap.name}, national capital of ${countryName}`}
                      >
                        <span className="hierarchy__thumb">
                          {flagPath ? (
                            <img
                              src={`${baseUrl}${flagPath}`}
                              alt=""
                              loading="lazy"
                              draggable={false}
                              className="hierarchy__thumb-img"
                              onError={(e) => { e.currentTarget.style.display = "none"; }}
                            />
                          ) : (
                            <span className="flag-grid__thumb-empty" aria-hidden="true">—</span>
                          )}
                        </span>
                        <AutoFitName className="hierarchy__name" text={cap.name} />
                        <AutoFitName
                          className="hierarchy__tier hierarchy__tier--capital"
                          text={`★ ${cap.note ?? "National capital"}`}
                        />
                      </button>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
          {groups.map((g) => (
            <div key={g.typeLabel} className="hierarchy__group" role="group" aria-label={pluralizeType(g.typeLabel)}>
              <div className="hierarchy__group-label">
                <span className="hierarchy__group-type">{pluralizeType(g.typeLabel)}</span>
                <span className="hierarchy__group-count">{g.items.length}</span>
              </div>

              <div className="hierarchy__subrow">
                {g.items.map(({ div, subFlag, subCapitalRole, leaves }) => {
                  const subActive = !capitalActive && div.code === selectedCode;
                  return (
                    <div key={div.code} className="hierarchy__col">
                      <button
                        type="button"
                        className={`hierarchy__node${subCapitalRole ? " hierarchy__node--capital" : ""}${subActive ? " hierarchy__node--active" : ""}`}
                        onClick={() => onSelectSubdivision(div.code)}
                        aria-pressed={subActive}
                        aria-label={
                          subCapitalRole
                            ? `Select ${div.name} — national capital of ${countryName}`
                            : `Select ${div.name}`
                        }
                      >
                        <span className="hierarchy__thumb">
                          {subFlag ? (
                            <img
                              src={subFlag}
                              alt=""
                              loading="lazy"
                              draggable={false}
                              className="hierarchy__thumb-img"
                              onError={(e) => { e.currentTarget.style.display = "none"; }}
                            />
                          ) : (
                            <span className="flag-grid__thumb-empty" aria-hidden="true">—</span>
                          )}
                        </span>
                        <AutoFitName className="hierarchy__name" text={div.name} />
                        {subCapitalRole && (
                          <AutoFitName
                            className="hierarchy__tier hierarchy__tier--capital"
                            text={`★ ${subCapitalRole}`}
                          />
                        )}
                      </button>

                      {leaves.length > 0 && (
                        <div className="hierarchy__leafrow">
                          {leaves.map((leaf) => {
                            const active =
                              leaf.kind === "national"
                                ? activeNationalCapital === leaf.name
                                : capitalActive && div.code === selectedCode;
                            const label =
                              leaf.kind === "national"
                                ? `Select ${leaf.name}, national capital of ${countryName}`
                                : leaf.role
                                  ? `Select ${leaf.name}, capital of ${div.name} and national capital of ${countryName}`
                                  : `Select ${leaf.name}, capital of ${div.name}`;
                            const handleClick =
                              leaf.kind === "national"
                                ? () =>
                                    onSelectNationalCapital({
                                      name: leaf.name,
                                      note: leaf.note,
                                      flagPath: leaf.flagPath,
                                    })
                                : () => onSelectCapital(div.code);
                            return (
                              <div key={leaf.key} className="hierarchy__leaf">
                                <button
                                  type="button"
                                  className={`hierarchy__node hierarchy__node--city${leaf.role ? " hierarchy__node--capital" : ""}${active ? " hierarchy__node--active" : ""}`}
                                  onClick={handleClick}
                                  aria-pressed={active}
                                  aria-label={label}
                                >
                                  <span className="hierarchy__thumb">
                                    {leaf.flagPath ? (
                                      <img
                                        src={`${baseUrl}${leaf.flagPath}`}
                                        alt=""
                                        loading="lazy"
                                        draggable={false}
                                        className="hierarchy__thumb-img"
                                        onError={(e) => { e.currentTarget.style.display = "none"; }}
                                      />
                                    ) : (
                                      <span className="flag-grid__thumb-empty" aria-hidden="true">—</span>
                                    )}
                                  </span>
                                  <AutoFitName className="hierarchy__name" text={leaf.name} />
                                  {leaf.role && (
                                    <AutoFitName
                                      className="hierarchy__tier hierarchy__tier--capital"
                                      text={`★ ${leaf.role}`}
                                    />
                                  )}
                                </button>
                              </div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
