import { AutoFitName } from "./AutoFitName";
import { NATIONAL_CAPITAL_FLAGS } from "../data/nationalCapitalFlags";
import { normalizeForSearch } from "../lib/searchNormalize";
import { useHierarchyData, pluralizeType } from "../lib/hierarchyData";
import type { NationalFlag } from "../data/nationalFlags";
import type { FlagMeaning } from "../data/flagMeanings";
import type { SubdivisionMeta } from "../types/subdivision";

/**
 * "Hierarchy chart" tab — an interactive org chart of a country's structure:
 *
 *   nation (root)
 *     └─ each subdivision TYPE (States, Federal Territory, Autonomous Region, …)
 *          └─ every subdivision of that type
 *               └─ its capital city/cities (a capital is a leaf)
 *
 * National capitals are surfaced WITHOUT ever duplicating an entity that already
 * exists in the tree (sourced from NATIONAL_CITIES, like the map overlay's ★), and
 * always at the CITY-LEAF level, level with every other capital city:
 *  - A capital that IS a subdivision (a city-territory whose own leaf is
 *    tautological — Kuala Lumpur, Putrajaya, Tokyo) → its subdivision node is
 *    MARKED "★ <role>". No second node.
 *  - A capital that is a subdivision's capital CITY (Canberra ≡ ACT, Cape Town ≡
 *    Western Cape) → that city leaf is MARKED. No second node.
 *  - A capital that heads no subdivision but sits INSIDE one (Ottawa → Ontario,
 *    Pretoria → Gauteng, Amsterdam → North Holland) → it is added as an extra
 *    capital LEAF under that subdivision, beside the subdivision's own capital
 *    (Ontario → Toronto + Ottawa), with its own sourced municipal flag. The
 *    containing subdivision is decided by point-in-polygon (NATIONAL_CAPITAL_
 *    SUBDIVISION, generated by scripts/build-national-capital-locations.mjs).
 *  - Only a capital we cannot place inside any subdivision falls back to a small
 *    standalone "National capital" group.
 * A multi-capital nation handles each seat independently (South Africa: Cape Town
 * + Bloemfontein leaves marked, Pretoria added as a leaf under Gauteng).
 *
 * The subdivisions are grouped by their `typeLabel`, and each type appears as its
 * own label node laddering up to the national flag, with its subdivision flags
 * laddering up to it (mirroring the "By type" grouping of the flag grid, incl. its
 * tier order: primary subdivisions, then dependent/external territories, then
 * disputed).
 *
 * The chart shows the FULL administrative tree, not just the flagged parts: every
 * subdivision appears, and every subdivision with a known capital gets a city
 * leaf — whether or not a flag exists for it. Where a flag IS bundled it renders
 * (national → country.flagSvg, subdivision → subdivisionFlagUrl, city → the
 * name-confirmed capital flag), and where none exists a neutral "—" placeholder
 * is shown. Nothing is fabricated: the capital NAME comes from the same
 * authoritative source as the map ★ (`subdivisionCapital`), and a subdivision no
 * source has a capital for simply gets no leaf.
 *
 * Clicking any flag node updates the parent selection (map highlight + widget):
 *  - root  → the country itself (clears the subdivision drill-down)
 *  - branch→ that subdivision
 *  - leaf  → that subdivision + its capital
 * The type labels are structural, not selectable entities, so they are not
 * interactive.
 */

type Props = {
  divisions: SubdivisionMeta[];
  countryName: string;
  /** ISO 3166-1 alpha-2 of the country — used to source its national capital(s). */
  countryCode: string;
  countryFlagUrl: string | null;
  /** Selected subdivision code (if any). */
  selectedCode: string | null;
  /** True when the "View capital" drill-down is open for the selected code. */
  capitalActive: boolean;
  /** Name of the selected standalone national capital (if any) — for its active
   *  highlight; these capitals head no subdivision so `selectedCode` can't mark them. */
  activeNationalCapital?: string | null;
  baseUrl: string;
  onSelectCountry: () => void;
  onSelectSubdivision: (code: string) => void;
  onSelectCapital: (code: string) => void;
  /** A national capital that heads no subdivision (Ottawa, Pretoria …) — selecting
   *  it populates its own panel in the widget above. */
  onSelectNationalCapital: (cap: { name: string; note: string | null; flagPath: string | null }) => void;
  /** id of the flag whose widget is open (if any) — used to highlight a selected
   *  group flag (e.g. the Flag of the Federal Territories). */
  selectedNationalFlagId?: string | null;
  /** A collective group flag (Malaysia's Federal Territories) — opens its own
   *  widget with its sourced meaning, like a national symbol. */
  onSelectGroupFlag: (flag: NationalFlag, meaning: FlagMeaning | null) => void;
};

export function SubdivisionHierarchyChart({
  divisions,
  countryName,
  countryCode,
  countryFlagUrl,
  selectedCode,
  capitalActive,
  activeNationalCapital,
  baseUrl,
  onSelectCountry,
  onSelectSubdivision,
  onSelectCapital,
  onSelectNationalCapital,
  selectedNationalFlagId,
  onSelectGroupFlag,
}: Props) {
  const { nodes, standaloneCaps, groups } = useHierarchyData(divisions, countryCode);

  if (nodes.length === 0) {
    return (
      <p className="flag-grid__no-match">
        No sub-national divisions are available for {countryName} yet.
      </p>
    );
  }

  const rootActive = !selectedCode;

  return (
    <div className="hierarchy" role="tree" aria-label={`${countryName} flag hierarchy`}>
      <div className="hierarchy__inner">
        <div className="hierarchy__root">
          <button
            type="button"
            className={`hierarchy__node hierarchy__node--national${rootActive ? " hierarchy__node--active" : ""}`}
            onClick={onSelectCountry}
            aria-pressed={rootActive}
            aria-label={`Select ${countryName}`}
          >
            <span className="hierarchy__thumb">
              {countryFlagUrl ? (
                <img
                  src={countryFlagUrl}
                  alt=""
                  loading="lazy"
                  draggable={false}
                  className="hierarchy__thumb-img"
                />
              ) : (
                <span className="flag-grid__thumb-empty" aria-hidden="true">—</span>
              )}
            </span>
            <AutoFitName className="hierarchy__name" text={countryName} />
            <span className="hierarchy__tier">Nation</span>
          </button>
        </div>

        <div className="hierarchy__branches">
          {standaloneCaps.length > 0 && (
            <div className="hierarchy__group" role="group" aria-label="National capital">
              <div className="hierarchy__group-label">
                <span className="hierarchy__group-type">National capital</span>
                {standaloneCaps.length > 1 && (
                  <span className="hierarchy__group-count">{standaloneCaps.length}</span>
                )}
              </div>

              <div className="hierarchy__subrow">
                {standaloneCaps.map((cap) => {
                  // A national capital that heads no subdivision (Ottawa, Belmopan)
                  // — its own sourced municipal flag if one is bundled, else "—".
                  const flagPath =
                    NATIONAL_CAPITAL_FLAGS[`${countryCode}|${normalizeForSearch(cap.name)}`] ?? null;
                  const active = activeNationalCapital === cap.name;
                  return (
                    <div key={cap.name} className="hierarchy__col">
                      <button
                        type="button"
                        className={`hierarchy__node hierarchy__node--capital${active ? " hierarchy__node--active" : ""}`}
                        onClick={() => onSelectNationalCapital({ name: cap.name, note: cap.note, flagPath })}
                        aria-pressed={active}
                        aria-label={`Select ${cap.name}, national capital of ${countryName}`}
                      >
                        <span className="hierarchy__thumb">
                          {flagPath ? (
                            <img
                              src={`${baseUrl}${flagPath}`}
                              alt=""
                              loading="lazy"
                              draggable={false}
                              className="hierarchy__thumb-img"
                              onError={(e) => { e.currentTarget.style.display = "none"; }}
                            />
                          ) : (
                            <span className="flag-grid__thumb-empty" aria-hidden="true">—</span>
                          )}
                        </span>
                        <AutoFitName className="hierarchy__name" text={cap.name} />
                        <AutoFitName
                          className="hierarchy__tier hierarchy__tier--capital"
                          text={`★ ${cap.note ?? "National capital"}`}
                        />
                      </button>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
          {groups.map((g) => (
            <div key={g.typeLabel} className="hierarchy__group" role="group" aria-label={pluralizeType(g.typeLabel)}>
              {g.groupFlag ? (
                // A collective flag for the WHOLE group (Malaysia's Flag of the
                // Federal Territories) — shown ON the group label so it reads as
                // the parent of the subdivision cards laddering up to it below.
                (() => {
                  const gf = g.groupFlag;
                  const active = gf.flag.id === selectedNationalFlagId;
                  return (
                    <button
                      type="button"
                      className={`hierarchy__group-label hierarchy__group-label--flag${active ? " hierarchy__group-label--active" : ""}`}
                      onClick={() => onSelectGroupFlag(gf.flag, gf.meaning ?? null)}
                      aria-pressed={active}
                      aria-label={`Select ${gf.flag.name}, flown for the ${pluralizeType(g.typeLabel)} together`}
                    >
                      <span className="hierarchy__group-flag-thumb">
                        {gf.flag.path ? (
                          <img
                            src={`${baseUrl}${gf.flag.path}`}
                            alt=""
                            loading="lazy"
                            draggable={false}
                            className="hierarchy__group-flag-img"
                            onError={(e) => { e.currentTarget.style.display = "none"; }}
                          />
                        ) : (
                          <span className="flag-grid__thumb-empty" aria-hidden="true">—</span>
                        )}
                      </span>
                      <span className="hierarchy__group-type">{pluralizeType(g.typeLabel)}</span>
                      <span className="hierarchy__group-count">{g.items.length}</span>
                    </button>
                  );
                })()
              ) : (
                <div className="hierarchy__group-label">
                  <span className="hierarchy__group-type">{pluralizeType(g.typeLabel)}</span>
                  <span className="hierarchy__group-count">{g.items.length}</span>
                </div>
              )}

              <div className="hierarchy__subrow">
                {g.items.map(({ div, subFlag, subCapitalRole, leaves }) => {
                  const subActive = !capitalActive && div.code === selectedCode;
                  return (
                    <div key={div.code} className="hierarchy__col">
                      <button
                        type="button"
                        className={`hierarchy__node${subCapitalRole ? " hierarchy__node--capital" : ""}${subActive ? " hierarchy__node--active" : ""}`}
                        onClick={() => onSelectSubdivision(div.code)}
                        aria-pressed={subActive}
                        aria-label={
                          subCapitalRole
                            ? `Select ${div.name} — national capital of ${countryName}`
                            : `Select ${div.name}`
                        }
                      >
                        <span className="hierarchy__thumb">
                          {subFlag ? (
                            <img
                              src={subFlag}
                              alt=""
                              loading="lazy"
                              draggable={false}
                              className="hierarchy__thumb-img"
                              onError={(e) => { e.currentTarget.style.display = "none"; }}
                            />
                          ) : (
                            <span className="flag-grid__thumb-empty" aria-hidden="true">—</span>
                          )}
                        </span>
                        <AutoFitName className="hierarchy__name" text={div.name} />
                        {subCapitalRole && (
                          <AutoFitName
                            className="hierarchy__tier hierarchy__tier--capital"
                            text={`★ ${subCapitalRole}`}
                          />
                        )}
                      </button>

                      {leaves.length > 0 && (
                        <div className="hierarchy__leafrow">
                          {leaves.map((leaf) => {
                            const active =
                              leaf.kind === "national"
                                ? activeNationalCapital === leaf.name
                                : capitalActive && div.code === selectedCode;
                            const label =
                              leaf.kind === "national"
                                ? `Select ${leaf.name}, national capital of ${countryName}`
                                : leaf.role
                                  ? `Select ${leaf.name}, capital of ${div.name} and national capital of ${countryName}`
                                  : `Select ${leaf.name}, capital of ${div.name}`;
                            const handleClick =
                              leaf.kind === "national"
                                ? () =>
                                    onSelectNationalCapital({
                                      name: leaf.name,
                                      note: leaf.note,
                                      flagPath: leaf.flagPath,
                                    })
                                : () => onSelectCapital(div.code);
                            return (
                              <div key={leaf.key} className="hierarchy__leaf">
                                <button
                                  type="button"
                                  className={`hierarchy__node hierarchy__node--city${leaf.role ? " hierarchy__node--capital" : ""}${active ? " hierarchy__node--active" : ""}`}
                                  onClick={handleClick}
                                  aria-pressed={active}
                                  aria-label={label}
                                >
                                  <span className="hierarchy__thumb">
                                    {leaf.flagPath ? (
                                      <img
                                        src={`${baseUrl}${leaf.flagPath}`}
                                        alt=""
                                        loading="lazy"
                                        draggable={false}
                                        className="hierarchy__thumb-img"
                                        onError={(e) => { e.currentTarget.style.display = "none"; }}
                                      />
                                    ) : (
                                      <span className="flag-grid__thumb-empty" aria-hidden="true">—</span>
                                    )}
                                  </span>
                                  <AutoFitName className="hierarchy__name" text={leaf.name} />
                                  {leaf.role && (
                                    <AutoFitName
                                      className="hierarchy__tier hierarchy__tier--capital"
                                      text={`★ ${leaf.role}`}
                                    />
                                  )}
                                </button>
                              </div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
