import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const dataFile = path.join(root, "src/data/nationalNewsAgencies.ts");

let content = fs.readFileSync(dataFile, "utf8");

const block5Entries = `
  // Costa Rica
  CR: [
    {
      id: "cr-la-nacion",
      countryCode: "CR",
      name: "La Nación",
      englishTranslation: "The Nation",
      founded: 1946,
      frequency: "Daily newspaper (Monday–Sunday)",
      format: "Tabloid & digital portal",
      language: "Spanish",
      headquarters: "San José",
      owner: {
        name: "Grupo Nación S.A.",
        type: "Independent commercial media",
      },
      editorialStance: "Costa Rica's historic newspaper of record; center-right liberal-conservative editorial stance focusing on governance, politics, and investigative reporting",
      readership: {
        metric: "Over 2.5 million monthly digital readers and Costa Rica's highest circulated print daily",
        source: "Grupo Nación Memoria Anual 2023",
      },
      revenueModel: "Digital paywall subscriptions, print sales, and corporate advertising",
      logo: "newspaper-logos/cr/la-nación.svg",
      logoExplainer:
        "Classic black serif masthead 'La Nación' on white canvas, symbolising democratic governance and public interest reporting in Costa Rica.",
      sources: ["https://www.nacion.com", "https://en.wikipedia.org/wiki/La_Naci%C3%B3n_(San_Jos%C3%A9)"],
    },
    {
      id: "cr-la-republica",
      countryCode: "CR",
      name: "La República",
      englishTranslation: "The Republic",
      founded: 1950,
      frequency: "Daily business newspaper (Monday–Friday)",
      format: "Tabloid & digital portal",
      language: "Spanish",
      headquarters: "San José",
      owner: {
        name: "Republicare Media Group",
        type: "Independent commercial media",
      },
      editorialStance: "Business, finance, and investment daily; focus on foreign direct investment, free trade zones, and macroeconomic policy",
      readership: {
        metric: "Leading specialized financial daily read across business chambers and executive suites in Costa Rica",
        source: "La República Media Profile 2024",
      },
      revenueModel: "Corporate subscriptions and financial sector advertising",
      logo: "newspaper-logos/cr/la-república.svg",
      logoExplainer:
        "Vibrant red banner with crisp white serif typography 'LA REPÚBLICA', representing business intelligence and commerce.",
      sources: ["https://www.larepublica.net", "https://es.wikipedia.org/wiki/La_Rep%C3%BAblica_(Costa_Rica)"],
    },
    {
      id: "cr-diario-extra",
      countryCode: "CR",
      name: "Diario Extra",
      englishTranslation: "Extra Daily",
      founded: 1978,
      frequency: "Daily newspaper",
      format: "Tabloid & digital portal",
      language: "Spanish",
      headquarters: "San José",
      owner: {
        name: "Grupo Extra / Transcomer Group",
        type: "Independent commercial media",
      },
      editorialStance: "Popular tabloid; crime reporting, labour union advocacy, sports, and working-class social issues",
      readership: {
        metric: "Historically Costa Rica's largest street-sale newspaper with 80,000+ daily copies",
        source: "Diario Extra Media Kit 2023",
      },
      revenueModel: "Retail print sales and classified advertising",
      logo: "newspaper-logos/cr/diario-extra.svg",
      logoExplainer:
        "Red and yellow title block with bold sans-serif lettering 'DIARIO EXTRA', iconic across Costa Rican kiosks.",
      sources: ["https://www.diarioextra.com", "https://es.wikipedia.org/wiki/Diario_Extra_(Costa_Rica)"],
    },
    {
      id: "cr-crhoy",
      countryCode: "CR",
      name: "CRHoy",
      founded: 2012,
      frequency: "Continuous 24/7 digital news service",
      format: "Digital-only news portal",
      language: "Spanish",
      headquarters: "San José",
      owner: {
        name: "Leonel Baruch / CRHoy Media",
        type: "Independent commercial media",
      },
      editorialStance: "Leading digital investigative portal; high-tempo breaking news, investigative exposés, and political accountability",
      readership: {
        metric: "Over 5.5 million monthly unique digital visitors; highest digital news traffic in Costa Rica",
        source: "Similarweb & CRHoy Media Review 2024",
      },
      revenueModel: "Digital programmatic advertising and sponsored content",
      logo: "newspaper-logos/cr/crhoy.svg",
      logoExplainer:
        "Bold blue and orange typography 'crhoy.com' representing rapid breaking digital journalism in Central America.",
      sources: ["https://www.crhoy.com", "https://es.wikipedia.org/wiki/CRHoy"],
    },
    {
      id: "cr-elfaro-cr",
      countryCode: "CR",
      name: "El Faro Costa Rica",
      englishTranslation: "The Lighthouse Costa Rica",
      founded: 2018,
      frequency: "Continuous digital news magazine",
      format: "Investigative digital portal",
      language: "Spanish",
      headquarters: "San José",
      owner: {
        name: "Fundación Trípode",
        type: "Non-profit independent foundation",
      },
      editorialStance: "In-depth investigative journalism; corruption investigations, judicial independence, and regional Central American democracy",
      readership: {
        metric: "Leading investigative regional journalism platform relocated to San José for press freedom protection",
        source: "Fundación Trípode Annual Report 2023",
      },
      revenueModel: "International journalistic grants and reader crowdfunding",
      logo: "newspaper-logos/cr/elfaro-cr.svg",
      logoExplainer:
        "Black emblem with golden lighthouse beam and stark typography 'elfaro', symbolising illumination of truth and investigative scrutiny.",
      sources: ["https://elfaro.net", "https://en.wikipedia.org/wiki/El_Faro_(digital_newspaper)"],
    },
  ],

  // Croatia
  HR: [
    {
      id: "hr-vecernji-list",
      countryCode: "HR",
      name: "Večernji list",
      englishTranslation: "Evening Paper",
      founded: 1959,
      frequency: "Daily newspaper",
      format: "Compact daily & digital portal",
      language: "Croatian",
      headquarters: "Zagreb",
      owner: {
        name: "Styria Media Group AG",
        type: "Independent commercial media",
      },
      editorialStance: "Center-right mainstream daily newspaper of record; national political commentary, European Union affairs, and cultural reviews",
      readership: {
        metric: "Over 2.2 million monthly unique digital visitors on vecernji.hr and leading print circulation in Zagreb",
        source: "Styria Media Group Croatia 2023",
      },
      revenueModel: "Digital subscriptions, print sales, and commercial advertising",
      logo: "newspaper-logos/hr/večernji-list.svg",
      logoExplainer:
        "Red and black logo with stylized bold text 'Večernji list', an iconic masthead across Croatia for over sixty years.",
      sources: ["https://www.vecernji.hr", "https://en.wikipedia.org/wiki/Ve%C4%8Dernji_list"],
    },
    {
      id: "hr-jutarnji-list",
      countryCode: "HR",
      name: "Jutarnji list",
      englishTranslation: "Morning Paper",
      founded: 1998,
      frequency: "Daily newspaper",
      format: "Berliner & digital portal",
      language: "Croatian",
      headquarters: "Zagreb",
      owner: {
        name: "Hanza Media",
        type: "Independent commercial media",
      },
      editorialStance: "Center-left liberal daily; investigative journalism, political reform, business analysis, and arts coverage",
      readership: {
        metric: "Over 2.4 million monthly unique digital visitors on jutarnji.hr; flagship publication of Hanza Media",
        source: "Hanza Media Audience Report 2024",
      },
      revenueModel: "Digital paywall subscriptions, print sales, and display advertising",
      logo: "newspaper-logos/hr/jutarnji-list.svg",
      logoExplainer:
        "Deep blue banner with modern bold white serif lettering 'JutarnjiLIST', symbolising contemporary liberal journalism.",
      sources: ["https://www.jutarnji.hr", "https://en.wikipedia.org/wiki/Jutarnji_list"],
    },
    {
      id: "hr-24sata",
      countryCode: "HR",
      name: "24sata",
      englishTranslation: "24 Hours",
      founded: 2005,
      frequency: "Daily newspaper",
      format: "Tabloid & multimedia portal",
      language: "Croatian",
      headquarters: "Zagreb",
      owner: {
        name: "Styria Media Group AG",
        type: "Independent commercial media",
      },
      editorialStance: "Popular tabloid; breaking news, visual reporting, social exposés, sports, and entertainment",
      readership: {
        metric: "Highest daily print circulation in Croatia and premier digital news website with 2.8M+ monthly unique users",
        source: "Styria Media Croatia Audience Review 2024",
      },
      revenueModel: "Retail print sales, programmatic digital advertising, and native video production",
      logo: "newspaper-logos/hr/24sata.svg",
      logoExplainer:
        "Orange rectangular badge featuring white numeral '24' and text 'sata', representing 24-hour fast-paced multimedia news.",
      sources: ["https://www.24sata.hr", "https://en.wikipedia.org/wiki/24sata_(Croatia)"],
    },
    {
      id: "hr-slobodna-dalmacija",
      countryCode: "HR",
      name: "Slobodna Dalmacija",
      englishTranslation: "Free Dalmatia",
      founded: 1943,
      frequency: "Daily newspaper",
      format: "Broadsheet & regional portal",
      language: "Croatian",
      headquarters: "Split, Dalmatia",
      owner: {
        name: "Hanza Media",
        type: "Independent commercial media",
      },
      editorialStance: "Historic regional daily newspaper founded as an anti-fascist partisan paper; voice of Dalmatia, maritime commerce, and Adriatic tourism",
      readership: {
        metric: "Leading daily newspaper in southern Croatia and the Adriatic coast with 1.8M monthly readers",
        source: "Hanza Media Regional Division 2023",
      },
      revenueModel: "Print circulation and regional corporate advertising",
      logo: "newspaper-logos/hr/slobodna-dalmacija.svg",
      logoExplainer:
        "Classic blue and white title banner with serif typography 'SLOBODNA DALMACIJA', evoking the Adriatic sea and Mediterranean tradition.",
      sources: ["https://slobodnadalmacija.hr", "https://en.wikipedia.org/wiki/Slobodna_Dalmacija"],
    },
    {
      id: "hr-novi-list",
      countryCode: "HR",
      name: "Novi list",
      englishTranslation: "New Paper",
      founded: 1900,
      frequency: "Daily newspaper",
      format: "Broadsheet & regional portal",
      language: "Croatian",
      headquarters: "Rijeka, Kvarner",
      owner: {
        name: "Media Solutions",
        type: "Independent commercial media",
      },
      editorialStance: "Centrist quality daily; primary voice of Rijeka, Istria, and Kvarner Bay focusing on local governance and industry",
      readership: {
        metric: "Oldest active daily newspaper in Croatia, dominating regional readership in western Croatia",
        source: "Novi List Nakladnik 2023",
      },
      revenueModel: "Print sales, subscriptions, and display advertising",
      logo: "newspaper-logos/hr/novi-list.svg",
      logoExplainer:
        "Red and black uppercase masthead 'NOVI LIST' on white ground, symbolising century-old civic journalism in Rijeka.",
      sources: ["https://www.novilist.hr", "https://en.wikipedia.org/wiki/Novi_list"],
    },
  ],

  // Cuba
  CU: [
    {
      id: "cu-granma",
      countryCode: "CU",
      name: "Granma",
      officialName: "Granma - Órgano Oficial del Comité Central del Partido Comunista de Cuba",
      nativeName: "Granma",
      englishTranslation: "Granma (named after the revolutionary yacht)",
      founded: 1965,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Official state broadsheet & international portal",
      language: "Spanish, with foreign language editions",
      headquarters: "Plaza de la Revolución, Havana",
      owner: {
        name: "Central Committee of the Communist Party of Cuba",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official newspaper of the Communist Party of Cuba; state decrees, socialist theory, economic reforms, and international anti-imperialist diplomacy",
      readership: {
        metric: "Largest print circulation in Cuba with 450,000 daily print copies and global digital reach across Granma.cu",
        source: "Editora Granma Informe de Gestión 2023",
      },
      revenueModel: "Direct state budget appropriation and institutional subscriptions",
      logo: "newspaper-logos/cu/granma.svg",
      logoExplainer:
        "Red banner with bold white lettering 'Granma' and stylized silhouette of the revolutionary yacht, the historic emblem of Cuban state journalism.",
      sources: ["https://www.granma.cu", "https://en.wikipedia.org/wiki/Granma_(newspaper)"],
    },
    {
      id: "cu-juventud-rebelde",
      countryCode: "CU",
      name: "Juventud Rebelde",
      englishTranslation: "Rebel Youth",
      founded: 1965,
      frequency: "Daily newspaper (Tuesday–Sunday)",
      format: "Tabloid & digital portal",
      language: "Spanish",
      headquarters: "Havana",
      owner: {
        name: "Union of Young Communists (UJC)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official newspaper of the Cuban youth organization; cultural development, youth sports, science, and university affairs",
      readership: {
        metric: "Second largest print circulation in Cuba with 250,000 daily copies and popular Sunday magazine edition",
        source: "Editora Juventud Rebelde 2023",
      },
      revenueModel: "State youth media subsidies and retail print distribution",
      logo: "newspaper-logos/cu/juventud-rebelde.svg",
      logoExplainer:
        "Blue and red badge with bold sans-serif text 'JUVENTUD REBELDE', symbolising revolutionary youth energy and education.",
      sources: ["https://www.juventudrebelde.cu", "https://en.wikipedia.org/wiki/Juventud_Rebelde"],
    },
    {
      id: "cu-prensa-latina",
      countryCode: "CU",
      name: "Prensa Latina",
      officialName: "Agencia Informativa Latinoamericana Prensa Latina S.A.",
      nativeName: "Prensa Latina",
      englishTranslation: "Latin American Press",
      founded: 1959,
      frequency: "Continuous 24/7 international newswire",
      format: "International news agency wire & multimedia service",
      language: "Spanish, English, French, Portuguese, Russian, Italian",
      headquarters: "Vedado, Havana",
      owner: {
        name: "Republic of Cuba",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Founded by Che Guevara and Jorge Ricardo Masetti; Latin American perspective on global affairs, Non-Aligned Movement, and anti-hegemonic coverage",
      readership: {
        metric: "Bureaus in over 40 countries; transmits more than 400 news dispatches daily to media partners worldwide",
        source: "Prensa Latina Memoria Institucional 2024",
      },
      annualPublicFunding: {
        total: "Central state foreign-press operational allocation",
        perCapita: "State international agency",
      },
      revenueModel: "State budget funding and international media syndication agreements",
      logo: "newspaper-logos/cu/prensa-latina.svg",
      logoExplainer:
        "Navy blue emblem with white calligraphy 'PL Prensa Latina' and globe meridians, symbolising non-aligned Latin American news distribution.",
      sources: ["https://www.prensa-latina.cu", "https://en.wikipedia.org/wiki/Prensa_Latina"],
    },
    {
      id: "cu-trabajadores",
      countryCode: "CU",
      name: "Trabajadores",
      englishTranslation: "Workers",
      founded: 1970,
      frequency: "Weekly newspaper (Monday)",
      format: "Tabloid publication & digital portal",
      language: "Spanish",
      headquarters: "Havana",
      owner: {
        name: "Central de Trabajadores de Cuba (CTC)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official organ of the Cuban Trade Union Confederation; labour legislation, worker productivity, industrial management, and cooperative agriculture",
      readership: {
        metric: "Distributed across all state enterprises, cooperative farms, and industrial unions nationwide",
        source: "CTC Departamento de Prensa 2023",
      },
      revenueModel: "Trade union dues and state publishing subsidy",
      logo: "newspaper-logos/cu/trabajadores.svg",
      logoExplainer:
        "Red and black title banner with bold uppercase typography 'TRABAJADORES', representing trade union solidarity.",
      sources: ["https://www.trabajadores.cu", "https://es.wikipedia.org/wiki/Trabajadores_(peri%C3%B3dico)"],
    },
    {
      id: "cu-cubadebate",
      countryCode: "CU",
      name: "Cubadebate",
      founded: 2003,
      frequency: "Continuous digital news service",
      format: "Digital multimedia portal",
      language: "Spanish, English, French, Portuguese",
      headquarters: "Havana",
      owner: {
        name: "Circle of Anti-Terrorist Journalists of Cuba",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Premier digital news and ideological debate portal; in-depth political essays, international sanctions analysis, and digital fact-checking",
      readership: {
        metric: "Most visited Cuban domestic website with over 3 million monthly web sessions",
        source: "Cubadebate Métricas Digitales 2024",
      },
      revenueModel: "State digital communication grant allocation",
      logo: "newspaper-logos/cu/cubadebate.svg",
      logoExplainer:
        "Red speech bubble emblem with clean white typography 'cubadebate', symbolising ideological discussion and digital news.",
      sources: ["http://www.cubadebate.cu", "https://en.wikipedia.org/wiki/Cubadebate"],
    },
  ],

  // Cyprus
  CY: [
    {
      id: "cy-cyprus-mail",
      countryCode: "CY",
      name: "Cyprus Mail",
      founded: 1945,
      frequency: "Daily newspaper & digital portal",
      format: "Broadsheet & English digital daily",
      language: "English",
      headquarters: "Nicosia",
      owner: {
        name: "CM Cyprus Mail Ltd",
        type: "Independent commercial media",
      },
      editorialStance: "Cyprus's oldest daily newspaper; authoritative English-language daily covering peace negotiations, EU diplomacy, energy, and business",
      readership: {
        metric: "Primary news source for English-speaking diplomats, expatriates, and international business leaders in Cyprus",
        source: "Cyprus Mail Circulation Review 2023",
      },
      revenueModel: "Digital subscriptions, print sales, and corporate advertising",
      logo: "newspaper-logos/cy/cyprus-mail.svg",
      logoExplainer:
        "Navy blue banner with classical white serif typography 'Cyprus Mail', representing eighty years of authoritative journalism.",
      sources: ["https://cyprus-mail.com", "https://en.wikipedia.org/wiki/Cyprus_Mail"],
    },
    {
      id: "cy-o-phileleftheros",
      countryCode: "CY",
      name: "O Phileleftheros",
      officialName: "O Fileleftheros",
      nativeName: "Ο Φιλελεύθερος",
      englishTranslation: "The Liberal",
      founded: 1955,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital network",
      language: "Greek",
      headquarters: "Nicosia",
      owner: {
        name: "Phileleftheros Public Company Ltd",
        type: "Independent commercial media",
      },
      editorialStance: "Cyprus's largest circulation newspaper of record; center-right stance focusing on the Cyprus problem, Hellenic affairs, and economic governance",
      readership: {
        metric: "Largest print circulation in Cyprus and leading web portal philnews.com reaching 3.5 million monthly unique visitors",
        source: "Phileleftheros Group Annual Review 2023",
      },
      revenueModel: "Print sales, corporate display advertising, and digital subscriptions",
      logo: "newspaper-logos/cy/o-phileleftheros.svg",
      logoExplainer:
        "Blue banner with classic white Greek typography 'Ο ΦΙΛΕΛΕΥΘΕΡΟΣ', the defining masthead of Cypriot print journalism.",
      sources: ["https://www.philenews.com", "https://en.wikipedia.org/wiki/Phileleftheros"],
    },
    {
      id: "cy-politis",
      countryCode: "CY",
      name: "Politis",
      nativeName: "Πολίτης",
      englishTranslation: "Citizen",
      founded: 1999,
      frequency: "Daily newspaper",
      format: "Compact tabloid & digital portal",
      language: "Greek",
      headquarters: "Nicosia",
      owner: {
        name: "Politis Media Group (Yiannis Papadopoulos)",
        type: "Independent commercial media",
      },
      editorialStance: "Independent progressive liberal newspaper; strong proponent of Cypriot reunification, anti-corruption investigations, and social reforms",
      readership: {
        metric: "Second largest Greek-language daily newspaper and highly influential digital portal politis.com.cy",
        source: "Politis Media Review 2024",
      },
      revenueModel: "Digital subscriptions, print sales, and commercial advertising",
      logo: "newspaper-logos/cy/politis.svg",
      logoExplainer:
        "Red and black logo with modern Greek sans-serif lettering 'ΠΟΛΙΤΗΣ', symbolising democratic citizenship and progressive civic debate.",
      sources: ["https://politis.com.cy", "https://en.wikipedia.org/wiki/Politis_(Cyprus)"],
    },
    {
      id: "cy-haravgi",
      countryCode: "CY",
      name: "Haravgi",
      nativeName: "Χαραυγή",
      englishTranslation: "Dawn",
      founded: 1956,
      frequency: "Daily newspaper",
      format: "Tabloid publication & digital portal",
      language: "Greek",
      headquarters: "Nicosia",
      owner: {
        name: "Tilegrafos Media (AKEL affiliated)",
        type: "Independent commercial media",
      },
      editorialStance: "Left-wing daily newspaper affiliated with the Progressive Party of Working People (AKEL); trade union rights, social welfare, and bi-communal peace",
      readership: {
        metric: "Dedicated nationwide readership across trade unions, cooperative movements, and left-wing civic organizations",
        source: "Haravgi Publishing Data 2023",
      },
      revenueModel: "Print sales, party subscriptions, and institutional advertisements",
      logo: "newspaper-logos/cy/haravgi.svg",
      logoExplainer:
        "Red title banner featuring golden sunrise symbol and white Greek lettering 'ΧΑΡΑΥΓΗ', representing a new socialist dawn.",
      sources: ["https://dialogos.com.cy/haravgi", "https://en.wikipedia.org/wiki/Haravgi"],
    },
    {
      id: "cy-simerini",
      countryCode: "CY",
      name: "Simerini",
      nativeName: "Σημερινή",
      englishTranslation: "Today",
      founded: 1976,
      frequency: "Weekly newspaper (Sunday) & daily portal",
      format: "Broadsheet & digital portal",
      language: "Greek",
      headquarters: "Nicosia",
      owner: {
        name: "Zeus Group / Dias Publishing",
        type: "Independent commercial media",
      },
      editorialStance: "Right-wing nationalist publication; defense of the Republic of Cyprus, Orthodox Christian cultural heritage, and sovereignty critique",
      readership: {
        metric: "Prominent Sunday print edition and active digital readership on sigmalive.com network",
        source: "Dias Publishing Group 2023",
      },
      revenueModel: "Print retail sales and network television-digital advertising",
      logo: "newspaper-logos/cy/simerini.svg",
      logoExplainer:
        "Deep blue title banner with white serif font 'ΣΗΜΕΡΙΝΗ', symbolising traditional Greek Cypriot conservative press heritage.",
      sources: ["https://simerini.sigmalive.com", "https://en.wikipedia.org/wiki/Simerini"],
    },
  ],

  // Czech Republic
  CZ: [
    {
      id: "cz-mfdnes",
      countryCode: "CZ",
      name: "Mladá fronta DNES",
      officialName: "MF DNES",
      nativeName: "Mladá fronta DNES",
      englishTranslation: "Youth Front Today",
      founded: 1945,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Broadsheet & digital portal",
      language: "Czech",
      headquarters: "Prague",
      owner: {
        name: "MAFRA a.s. (Kaprain Group)",
        type: "Independent commercial media",
      },
      editorialStance: "Czech Republic's largest quality broadsheet; center-right mainstream news focusing on national politics, European integration, and economics",
      readership: {
        metric: "Over 4.5 million monthly unique users across iDNES.cz and highest print circulation among Czech non-tabloid dailies",
        source: "NetMonitor Czech Republic & MAFRA 2024",
      },
      revenueModel: "Digital subscriptions (iDNES Premium), print retail sales, and corporate advertising",
      logo: "newspaper-logos/cz/mfdnes.svg",
      logoExplainer:
        "Red and blue emblem featuring bold uppercase text 'MF DNES', representing modern Czech national journalism.",
      sources: ["https://www.idnes.cz", "https://en.wikipedia.org/wiki/Mlad%C3%A1_fronta_DNES"],
    },
    {
      id: "cz-pravo",
      countryCode: "CZ",
      name: "Právo",
      nativeName: "Právo",
      englishTranslation: "Right / Justice",
      founded: 1991,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Broadsheet & digital portal",
      language: "Czech",
      headquarters: "Prague",
      owner: {
        name: "Borgis a.s.",
        type: "Independent commercial media",
      },
      editorialStance: "Center-left independent daily newspaper successor to Rudé právo; investigative journalism, legal commentary, and social affairs",
      readership: {
        metric: "Leading quality daily in print circulation and partner in Novinky.cz, the Czech Republic's top digital news site (5M+ monthly users)",
        source: "Borgis a.s. Annual Report 2023",
      },
      revenueModel: "Print sales, subscriptions, and web traffic partnership with Seznam.cz",
      logo: "newspaper-logos/cz/právo.svg",
      logoExplainer:
        "Classic black serif typography 'Právo' on clean white canvas, symbolising justice, legal rights, and democratic accountability.",
      sources: ["https://www.novinky.cz", "https://en.wikipedia.org/wiki/Pr%C3%A1vo"],
    },
    {
      id: "cz-hospodarske-noviny",
      countryCode: "CZ",
      name: "Hospodářské noviny",
      nativeName: "Hospodářské noviny",
      englishTranslation: "Economic Newspaper",
      founded: 1990,
      frequency: "Daily financial newspaper (Monday–Friday)",
      format: "Broadsheet & digital portal",
      language: "Czech",
      headquarters: "Prague",
      owner: {
        name: "Economia a.s. (Zdeněk Bakala)",
        type: "Independent commercial media",
      },
      editorialStance: "Premier financial and economic daily; Prague Stock Exchange, corporate strategy, European single market regulations, and macroeconomic policy",
      readership: {
        metric: "Benchmark business newspaper read by corporate leaders and policymakers with 1.8M monthly digital visitors",
        source: "Economia Media Kit 2024",
      },
      revenueModel: "Digital paywall subscriptions (HN.cz) and financial sector advertising",
      logo: "newspaper-logos/cz/hospodářské-noviny.svg",
      logoExplainer:
        "Navy blue banner with clean white typography 'Hospodářské noviny', reflecting market integrity and economic analysis.",
      sources: ["https://hn.cz", "https://en.wikipedia.org/wiki/Hospod%C3%A1%C5%99sk%C3%A9_noviny"],
    },
    {
      id: "cz-lidove-noviny",
      countryCode: "CZ",
      name: "Lidové noviny",
      nativeName: "Lidové noviny",
      englishTranslation: "The People's Newspaper",
      founded: 1893,
      frequency: "Daily newspaper (transitioned to digital daily)",
      format: "Digital daily & weekend print edition",
      language: "Czech",
      headquarters: "Prague",
      owner: {
        name: "MAFRA a.s. (Kaprain Group)",
        type: "Independent commercial media",
      },
      editorialStance: "Historic intellectual broadsheet associated with Karel Čapek and Václav Havel; conservative-liberal cultural commentary and public policy debate",
      readership: {
        metric: "Historic paper of record with strong cultural resonance and 1.5 million monthly digital visitors on Lidovky.cz",
        source: "MAFRA Publishing Report 2023",
      },
      revenueModel: "Digital subscriptions and specialized cultural advertising",
      logo: "newspaper-logos/cz/lidové-noviny.svg",
      logoExplainer:
        "Historic black serif masthead 'Lidové noviny' on white ground, symbolising 130 years of Czech intellectual journalism.",
      sources: ["https://www.lidovky.cz", "https://en.wikipedia.org/wiki/Lidov%C3%A9_noviny"],
    },
    {
      id: "cz-blesk",
      countryCode: "CZ",
      name: "Blesk",
      nativeName: "Blesk",
      englishTranslation: "Lightning",
      founded: 1992,
      frequency: "Daily newspaper",
      format: "Tabloid & digital portal",
      language: "Czech",
      headquarters: "Prague",
      owner: {
        name: "Czech News Center a.s.",
        type: "Independent commercial media",
      },
      editorialStance: "Mass-circulation popular tabloid; breaking news, consumer advocacy, celebrity profiles, and sports",
      readership: {
        metric: "Highest print circulation in the Czech Republic (~160,000 daily copies) and 4.2M monthly users on Blesk.cz",
        source: "Czech News Center Annual Review 2024",
      },
      revenueModel: "Retail print sales, digital display advertising, and consumer media services",
      logo: "newspaper-logos/cz/blesk.svg",
      logoExplainer:
        "Vivid red rectangular banner with bold yellow italic text 'BLESK', iconic across Czech newsstands.",
      sources: ["https://www.blesk.cz", "https://en.wikipedia.org/wiki/Blesk_(newspaper)"],
    },
  ],

  // Denmark
  DK: [
    {
      id: "dk-berlingske",
      countryCode: "DK",
      name: "Berlingske",
      officialName: "Berlingske Tidende",
      nativeName: "Berlingske",
      englishTranslation: "Berling's Times (named after founder Ernst Henrich Berling)",
      founded: 1749,
      frequency: "Daily newspaper",
      format: "Berliner & digital portal",
      language: "Danish",
      headquarters: "Copenhagen",
      owner: {
        name: "Berlingske Media (DPG Media)",
        type: "Independent commercial media",
      },
      editorialStance: "Denmark's oldest newspaper and one of the world's oldest continuously published dailies; conservative-liberal newspaper of record",
      readership: {
        metric: "Over 1.8 million monthly digital readers and premier quality daily in Copenhagen",
        source: "Kantar Gallup Denmark & Berlingske Media 2024",
      },
      revenueModel: "Digital paywall subscriptions, print circulation, and corporate advertising",
      logo: "newspaper-logos/dk/berlingske.svg",
      logoExplainer:
        "Classical black serif typography 'Berlingske' on clean white canvas, representing 275 years of Danish journalistic excellence.",
      sources: ["https://www.berlingske.dk", "https://en.wikipedia.org/wiki/Berlingske"],
    },
    {
      id: "dk-politiken",
      countryCode: "DK",
      name: "Politiken",
      nativeName: "Politiken",
      englishTranslation: "The Politics / Policy",
      founded: 1884,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Danish",
      headquarters: "Rådhuspladsen, Copenhagen",
      owner: {
        name: "JP/Politikens Hus",
        type: "Independent trust / foundation",
      },
      editorialStance: "Leading Danish social-liberal intellectual daily founded by Edvard Brandes; cultural critique, climate journalism, and international human rights",
      readership: {
        metric: "Over 2 million monthly digital visitors and largest quality subscription circulation in Denmark",
        source: "JP/Politikens Hus Annual Report 2023",
      },
      revenueModel: "Digital reader subscriptions, print sales, and cultural advertisements",
      logo: "newspaper-logos/dk/politiken.svg",
      logoExplainer:
        "Historic gothic and serif masthead 'POLITIKEN' anchored at Copenhagen's City Hall Square, symbolising progressive civic journalism.",
      sources: ["https://politiken.dk", "https://en.wikipedia.org/wiki/Politiken"],
    },
    {
      id: "dk-jyllands-posten",
      countryCode: "DK",
      name: "Jyllands-Posten",
      officialName: "Morgenavisen Jyllands-Posten",
      nativeName: "Jyllands-Posten",
      englishTranslation: "The Jutland Post",
      founded: 1871,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Danish",
      headquarters: "Aarhus & Copenhagen",
      owner: {
        name: "JP/Politikens Hus",
        type: "Independent trust / foundation",
      },
      editorialStance: "Center-right liberal-conservative broadsheet; voice of Jutland and national business, free-market economics, and investigative journalism",
      readership: {
        metric: "Over 1.7 million monthly digital users and historically Denmark's highest circulated broadsheet",
        source: "JP/Politikens Hus Media Review 2024",
      },
      revenueModel: "Print sales, digital subscriptions, and commercial advertising",
      logo: "newspaper-logos/dk/jyllands-posten.svg",
      logoExplainer:
        "Bold black serif title 'Jyllands-Posten' on white background, representing Jutland business resilience and national reporting.",
      sources: ["https://jyllands-posten.dk", "https://en.wikipedia.org/wiki/Jyllands-Posten"],
    },
    {
      id: "dk-borsen",
      countryCode: "DK",
      name: "Børsen",
      officialName: "Dagbladet Børsen",
      nativeName: "Børsen",
      englishTranslation: "The Exchange",
      founded: 1896,
      frequency: "Daily business newspaper (Monday–Friday)",
      format: "Salmon broadsheet & digital portal",
      language: "Danish",
      headquarters: "Copenhagen",
      owner: {
        name: "Bonnier Group (49.9%) & JP/Politikens Hus (49.9%)",
        type: "Independent commercial media",
      },
      editorialStance: "Denmark's preeminent financial and business daily; Copenhagen Stock Exchange, maritime shipping (Mærsk), green transition, and macroeconomic policy",
      readership: {
        metric: "Read by 85% of Danish top corporate executives and institutional investors",
        source: "Dagbladet Børsen Audience Report 2023",
      },
      revenueModel: "Corporate subscriptions and financial market advertising",
      logo: "newspaper-logos/dk/børsen.svg",
      logoExplainer:
        "Classic serif masthead 'BØRSEN' printed on signature salmon-pink paper, symbolising Nordic financial leadership.",
      sources: ["https://borsen.dk", "https://en.wikipedia.org/wiki/Dagbladet_B%C3%B8rsen"],
    },
    {
      id: "dk-ekstra-bladet",
      countryCode: "DK",
      name: "Ekstra Bladet",
      nativeName: "Ekstra Bladet",
      englishTranslation: "The Extra Sheet",
      founded: 1904,
      frequency: "Daily newspaper",
      format: "Tabloid & multimedia portal",
      language: "Danish",
      headquarters: "Copenhagen",
      owner: {
        name: "JP/Politikens Hus",
        type: "Independent trust / foundation",
      },
      editorialStance: "Iconic Danish investigative tabloid; aggressive political exposés, consumer advocacy, sports, and working-class watchdog journalism",
      readership: {
        metric: "Over 3.2 million monthly unique digital visitors on eb.dk, Denmark's most read online news brand",
        source: "Dansk Online Index & Kantar 2024",
      },
      revenueModel: "Digital subscriptions (+Ekstra), programmatic ads, and street print sales",
      logo: "newspaper-logos/dk/ekstra-bladet.svg",
      logoExplainer:
        "Stark black and yellow badge with bold typography 'EKSTRA BLADET', iconic for anti-authoritarian investigative reporting.",
      sources: ["https://ekstrabladet.dk", "https://en.wikipedia.org/wiki/Ekstra_Bladet"],
    },
  ],

  // Djibouti
  DJ: [
    {
      id: "dj-la-nation",
      countryCode: "DJ",
      name: "La Nation",
      englishTranslation: "The Nation",
      founded: 1980,
      frequency: "Daily newspaper (Monday–Thursday & Sunday)",
      format: "Official state broadsheet & digital portal",
      language: "French",
      headquarters: "Djibouti City",
      owner: {
        name: "Republic of Djibouti (Ministère de la Communication)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official national public daily newspaper; presidential decrees, port infrastructure developments (Doraleh), and Horn of Africa diplomacy",
      readership: {
        metric: "Only national daily French-language print newspaper in Djibouti, read throughout civil service and diplomatic missions",
        source: "La Nation Direction Générale 2023",
      },
      annualPublicFunding: {
        total: "DJF 90 million (~US$505,000) government operating budget",
        perCapita: "DJF 85 / person / year (~US$0.48)",
      },
      revenueModel: "Direct state budget appropriation, print sales, and official legal notices",
      logo: "newspaper-logos/dj/la-nation.svg",
      logoExplainer:
        "Emerald green title banner with crisp white typography 'LA NATION', embodying Djibouti's national identity and public communication.",
      sources: ["https://www.lanation.dj", "https://fr.wikipedia.org/wiki/La_Nation_(Djibouti)"],
    },
    {
      id: "dj-adi",
      countryCode: "DJ",
      name: "ADI",
      officialName: "Agence Djiboutienne d'Information",
      nativeName: "Agence Djiboutienne d'Information",
      englishTranslation: "Djiboutian Information Agency",
      founded: 1999,
      frequency: "Continuous 24/7 national newswire",
      format: "Official state wire service & digital portal",
      language: "French, Arabic",
      headquarters: "Djibouti City",
      owner: {
        name: "Republic of Djibouti (Ministère de la Communication)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Statutory national news agency; international diplomatic partnerships, IGAD regional affairs, and port logistics news",
      readership: {
        metric: "Primary news supplier to national television (RTD), radio networks, and regional Horn of Africa media",
        source: "ADI Rapport d'Activité 2023",
      },
      annualPublicFunding: {
        total: "DJF 65 million (~US$365,000) public wire grant",
        perCapita: "DJF 60 / person / year (~US$0.34)",
      },
      revenueModel: "State operating subsidy and commercial news syndication",
      logo: "newspaper-logos/dj/adi-agence-djiboutienne-d-information.svg",
      logoExplainer:
        "Blue and gold emblem displaying acronym 'ADI' and full French title, symbolising statutory news dissemination in the Horn of Africa.",
      sources: ["https://www.adi.dj", "https://fr.wikipedia.org/wiki/Agence_djiboutienne_d%27information"],
    },
    {
      id: "dj-al-qarn",
      countryCode: "DJ",
      name: "Al-Qarn",
      nativeName: "القرن",
      englishTranslation: "The Horn",
      founded: 1997,
      frequency: "Weekly newspaper (Thursday)",
      format: "Official state Arabic broadsheet & portal",
      language: "Arabic",
      headquarters: "Djibouti City",
      owner: {
        name: "Republic of Djibouti (Ministère de la Communication)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official state Arabic-language publication; Arab League relations, Islamic affairs, education, and Red Sea maritime commerce",
      readership: {
        metric: "Primary Arabic publication in Djibouti read by scholars, religious institutions, and Arab diplomatic missions",
        source: "Ministère de la Communication de Djibouti 2023",
      },
      revenueModel: "State budget funding and public notices",
      logo: "newspaper-logos/dj/al-qarn.svg",
      logoExplainer:
        "Green and white banner featuring elegant Arabic calligraphy 'القرن' (The Horn), reflecting Arab League heritage.",
      sources: ["https://www.alqarn.dj"],
    },
    {
      id: "dj-djib-post",
      countryCode: "DJ",
      name: "Djib-Post",
      founded: 2016,
      frequency: "Continuous digital news service",
      format: "Digital news portal",
      language: "French",
      headquarters: "Djibouti City",
      owner: {
        name: "Djib-Post Media Group",
        type: "Independent commercial media",
      },
      editorialStance: "Digital news platform; urban life, technological entrepreneurship, youth initiatives, and Horn of Africa economic news",
      readership: {
        metric: "Over 350,000 monthly digital visits across Djibouti and international diaspora in France and Canada",
        source: "Djib-Post Audience Analytics 2024",
      },
      revenueModel: "Digital display advertising and sponsored corporate media",
      logo: "newspaper-logos/dj/djib-post.svg",
      logoExplainer:
        "Modern navy blue and cyan banner featuring 'DJIB-POST', symbolising youth-driven digital journalism.",
      sources: ["https://djibpost.com"],
    },
    {
      id: "dj-human-village",
      countryCode: "DJ",
      name: "Human Village",
      founded: 2008,
      frequency: "Monthly cultural & economic journal",
      format: "Digital magazine & analytical portal",
      language: "French",
      headquarters: "Djibouti City",
      owner: {
        name: "Association Human Village",
        type: "Independent trust / foundation",
      },
      editorialStance: "Independent socio-cultural and economic journal; environmental conservation, architectural heritage, and historical research on Djibouti",
      readership: {
        metric: "Highly regarded journal read by researchers, historians, and educators throughout the Red Sea region",
        source: "Human Village Association 2023",
      },
      revenueModel: "Cultural foundation grants and publication subscriptions",
      logo: "newspaper-logos/dj/human-village.svg",
      logoExplainer:
        "Warm terracotta badge with white typography 'Human Village', symbolising humanism, culture, and environmental awareness.",
      sources: ["http://www.human-village.org", "https://fr.wikipedia.org/wiki/Culture_de_Djibouti"],
    },
  ],
`;

const closingIndex = content.lastIndexOf("};");
if (closingIndex === -1) {
  throw new Error("Could not find closing '};' in " + dataFile);
}

const updatedContent = content.slice(0, closingIndex) + block5Entries + "};\n";
fs.writeFileSync(dataFile, updatedContent, "utf8");
console.log("✓ Successfully added Block 5 entries to src/data/nationalNewsAgencies.ts");
