import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const dataFile = path.join(root, "src/data/nationalNewsAgencies.ts");

let content = fs.readFileSync(dataFile, "utf8");

const block4Entries = `
  // Canada
  CA: [
    {
      id: "ca-the-globe-and-mail",
      countryCode: "CA",
      name: "The Globe and Mail",
      founded: 1844,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Broadsheet & digital portal",
      language: "English",
      headquarters: "Toronto, Ontario",
      owner: {
        name: "The Woodbridge Company (Thomson family)",
        type: "Independent commercial media",
      },
      editorialStance: "National newspaper of record; center-right liberal-conservative editorial stance focusing on finance, politics, and investigative national reporting",
      readership: {
        metric: "Over 6.2 million weekly multiplatform readers across Canada",
        source: "News Media Canada & Vividata 2024",
      },
      revenueModel: "Digital subscriptions, print sales, and corporate advertising",
      logo: "newspaper-logos/ca/the-globe-and-mail.svg",
      logoExplainer:
        "White banner featuring the iconic serif typography 'The Globe and Mail' in black, representing Canada's historic newspaper of record.",
      sources: ["https://www.theglobeandmail.com", "https://en.wikipedia.org/wiki/The_Globe_and_Mail"],
    },
    {
      id: "ca-the-toronto-star",
      countryCode: "CA",
      name: "Toronto Star",
      founded: 1892,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "English",
      headquarters: "Toronto, Ontario",
      owner: {
        name: "NordStar Capital",
        type: "Independent commercial media",
      },
      editorialStance: "Social-democratic / liberal progressive editorial stance guided by the Atkinson Principles, focusing on social justice and civic affairs",
      readership: {
        metric: "Highest daily print circulation in Canada with 5.0+ million weekly readers",
        source: "Torstar Corporate Media Profile 2023",
      },
      revenueModel: "Digital paywall subscriptions, print sales, and display advertising",
      logo: "newspaper-logos/ca/the-toronto-star.svg",
      logoExplainer:
        "Deep blue banner featuring white serif typography 'TORONTO STAR', symbolizing progressive civic and investigative reporting.",
      sources: ["https://www.thestar.com", "https://en.wikipedia.org/wiki/Toronto_Star"],
    },
    {
      id: "ca-le-devoir",
      countryCode: "CA",
      name: "Le Devoir",
      englishTranslation: "The Duty",
      founded: 1910,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Compact broadsheet & digital portal",
      language: "French",
      headquarters: "Montreal, Quebec",
      owner: {
        name: "Le Devoir Trust",
        type: "Non-profit independent trust",
      },
      editorialStance: "Independent Quebec intellectual daily founded by Henri Bourassa; focus on culture, Quebec politics, and civic debate",
      readership: {
        metric: "Benchmark French-language quality daily reaching over 1.8 million monthly digital visitors",
        source: "Le Devoir Trust Annual Report 2023",
      },
      revenueModel: "Reader subscriptions, philanthropic donations, and targeted advertising",
      logo: "newspaper-logos/ca/le-devoir.svg",
      logoExplainer:
        "Minimalist white background with crisp black serif masthead 'LE DEVOIR', representing intellectual independence and journalistic duty.",
      sources: ["https://www.ledevoir.com", "https://en.wikipedia.org/wiki/Le_Devoir"],
    },
    {
      id: "ca-national-post",
      countryCode: "CA",
      name: "National Post",
      founded: 1998,
      frequency: "Daily newspaper (Tuesday–Saturday)",
      format: "Broadsheet & digital portal",
      language: "English",
      headquarters: "Toronto, Ontario",
      owner: {
        name: "Postmedia Network",
        type: "Independent commercial media",
      },
      editorialStance: "Conservative national broadsheet founded by Conrad Black; free-market advocacy, federal politics, and financial market analysis",
      readership: {
        metric: "Over 4.5 million weekly readers across print and digital Postmedia networks",
        source: "Postmedia Network Annual Report 2023",
      },
      revenueModel: "Print advertising, digital paywall, and sponsored content",
      logo: "newspaper-logos/ca/national-post.svg",
      logoExplainer:
        "Modern black uppercase sans-serif title 'NATIONAL POST' on white ground, reflecting contemporary business and national political journalism.",
      sources: ["https://nationalpost.com", "https://en.wikipedia.org/wiki/National_Post"],
    },
    {
      id: "ca-la-presse",
      countryCode: "CA",
      name: "La Presse",
      englishTranslation: "The Press",
      founded: 1884,
      frequency: "Continuous digital daily edition",
      format: "Digital-only news tablet app & portal",
      language: "French",
      headquarters: "Montreal, Quebec",
      owner: {
        name: "Fiducie La Presse",
        type: "Non-profit independent trust",
      },
      editorialStance: "Independent progressive francophone media; pioneer in digital-first journalism and comprehensive national coverage",
      readership: {
        metric: "Over 4 million monthly active digital readers on mobile, tablet, and web platforms",
        source: "Fiducie La Presse Financial Report 2023",
      },
      revenueModel: "Philanthropic donations, government journalism tax credits, and digital advertising",
      logo: "newspaper-logos/ca/la-presse.svg",
      logoExplainer:
        "Red rectangular emblem featuring clean white sans-serif letters 'LA PRESSE', symbolising modern Quebec digital news leadership.",
      sources: ["https://www.lapresse.ca", "https://en.wikipedia.org/wiki/La_Presse_(Canadian_newspaper)"],
    },
  ],

  // Cape Verde
  CV: [
    {
      id: "cv-inforpress",
      countryCode: "CV",
      name: "Inforpress",
      officialName: "Agência Cabo-Verdiana de Notícias",
      nativeName: "Agência Cabo-Verdiana de Notícias",
      englishTranslation: "Cape Verdean News Agency",
      founded: 1988,
      frequency: "Continuous 24/7 national newswire",
      format: "National state newswire & multimedia service",
      language: "Portuguese",
      headquarters: "Praia, Santiago Island",
      owner: {
        name: "State of Cape Verde",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "National public newswire agency; government decrees, parliamentary activity, and island archipelago news",
      readership: {
        metric: "Primary news supplier to all television, radio, and digital media across the nine inhabited islands of Cape Verde",
        source: "Inforpress Relatório e Contas 2023",
      },
      annualPublicFunding: {
        total: "CVE 95.0 million (~US$920,000) state budget appropriation",
        perCapita: "CVE 190 / person / year (~US$1.85)",
      },
      revenueModel: "State public service contract and wire subscription syndication",
      logo: "newspaper-logos/cv/inforpress.svg",
      logoExplainer:
        "White emblem with deep blue typography 'inforpress' and stylized connectivity waves, representing national archipelago communication.",
      sources: ["https://inforpress.cv", "https://pt.wikipedia.org/wiki/Inforpress"],
    },
    {
      id: "cv-a-semana",
      countryCode: "CV",
      name: "A Semana",
      englishTranslation: "The Week",
      founded: 1991,
      frequency: "Weekly newspaper & digital daily",
      format: "Tabloid & digital portal",
      language: "Portuguese",
      headquarters: "Praia",
      owner: {
        name: "Publi-Press Lda",
        type: "Independent commercial media",
      },
      editorialStance: "Historic independent weekly newspaper; investigative reporting, political analysis, and democratic accountability",
      readership: {
        metric: "Leading independent weekly publication in Cape Verde with widespread diaspora readership in Portugal and the US",
        source: "A Semana Online Profile 2023",
      },
      revenueModel: "Print sales and digital display advertising",
      logo: "newspaper-logos/cv/a-semana.svg",
      logoExplainer:
        "White canvas displaying bold black masthead 'A SEMANA', symbolising thirty years of independent democratic journalism.",
      sources: ["https://asemana.publ.cv", "https://pt.wikipedia.org/wiki/A_Semana"],
    },
    {
      id: "cv-expressodasilhas",
      countryCode: "CV",
      name: "Expresso das Ilhas",
      englishTranslation: "Islands Express",
      founded: 2001,
      frequency: "Weekly newspaper & daily web portal",
      format: "Tabloid & digital portal",
      language: "Portuguese",
      headquarters: "Praia & Mindelo",
      owner: {
        name: "Silves & Faria / Grupo Lena",
        type: "Independent commercial media",
      },
      editorialStance: "Center-liberal economic and political weekly; focus on archipelago development, business, and cultural heritage",
      readership: {
        metric: "Widely read weekly newspaper across São Vicente and Santiago islands",
        source: "Expresso das Ilhas Editorial Review 2023",
      },
      revenueModel: "Commercial advertising and newspaper circulation",
      logo: "newspaper-logos/cv/expressodasilhas.svg",
      logoExplainer:
        "Navy blue background with gold-yellow lettering 'Expresso das Ilhas', highlighting maritime connectivity and national reporting.",
      sources: ["https://expressodasilhas.cv", "https://pt.wikipedia.org/wiki/Expresso_das_Ilhas"],
    },
    {
      id: "cv-jornal-i",
      countryCode: "CV",
      name: "Jornal i",
      founded: 2010,
      frequency: "Weekly newspaper",
      format: "Tabloid & digital portal",
      language: "Portuguese",
      headquarters: "Praia",
      owner: {
        name: "Iniciativa Media Group",
        type: "Independent commercial media",
      },
      editorialStance: "Independent commercial paper; urban lifestyle, youth culture, culture, and social development in Cape Verde",
      readership: {
        metric: "Popular urban weekly paper read across youth and commercial sectors in Praia",
        source: "Jornal i Archive 2023",
      },
      revenueModel: "Print sales and local corporate advertising",
      logo: "newspaper-logos/cv/jornal-i.svg",
      logoExplainer:
        "Red title banner featuring crisp white letter 'i' and modern typography, symbolising innovative urban press.",
      sources: ["https://www.facebook.com/jornalicv", "https://pt.wikipedia.org/wiki/Cabo_Verde#Comunica%C3%A7%C3%A3o_social"],
    },
    {
      id: "cv-santiago-magazine",
      countryCode: "CV",
      name: "Santiago Magazine",
      founded: 2017,
      frequency: "Continuous digital news portal",
      format: "Digital news portal",
      language: "Portuguese",
      headquarters: "Praia, Santiago Island",
      owner: {
        name: "Santiago Magazine Lda",
        type: "Independent commercial media",
      },
      editorialStance: "Independent digital investigative journalism; in-depth political scandals, justice investigations, and governance oversight",
      readership: {
        metric: "Leading digital investigative daily portal in Cape Verde with 600,000+ monthly visits",
        source: "Santiago Magazine Analytics 2024",
      },
      revenueModel: "Digital banner advertising and sponsored opinion columns",
      logo: "newspaper-logos/cv/santiago-magazine.svg",
      logoExplainer:
        "Dark slate badge with clean white uppercase title 'SANTIAGO MAGAZINE', representing fearless modern digital investigative journalism.",
      sources: ["https://santiagomagazine.cv"],
    },
  ],

  // Central African Republic
  CF: [
    {
      id: "cf-acap",
      countryCode: "CF",
      name: "ACAP",
      officialName: "Agence Centrafricaine de Presse",
      nativeName: "Agence Centrafricaine de Presse",
      englishTranslation: "Central African Press Agency",
      founded: 1961,
      frequency: "Continuous daily state newswire",
      format: "Official state newswire & bulletin",
      language: "French, Sango",
      headquarters: "Bangui",
      owner: {
        name: "Republic of Central Africa (Ministère de la Communication)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official state news wire; presidential communications, ministerial decrees, and peace accord monitoring",
      readership: {
        metric: "Primary news supplier to Bangui national radio, television, and private print titles",
        source: "ACAP Bangui Annual Review 2023",
      },
      annualPublicFunding: {
        total: "XAF 120 million (~US$200,000) state budget operating grant",
        perCapita: "XAF 22 / person / year (~US$0.04)",
      },
      revenueModel: "Direct state budget subsidy and subscription bulletin sales",
      logo: "newspaper-logos/cf/acap.svg",
      logoExplainer:
        "Deep blue emblem with white serif letters 'ACAP', representing the official national news wire of the Central African Republic.",
      sources: ["https://acap.cf", "https://fr.wikipedia.org/wiki/Agence_centrafricaine_de_presse"],
    },
    {
      id: "cf-le-democrate",
      countryCode: "CF",
      name: "Le Démocrate",
      englishTranslation: "The Democrat",
      founded: 1992,
      frequency: "Daily newspaper",
      format: "Tabloid & digital portal",
      language: "French",
      headquarters: "Bangui",
      owner: {
        name: "Société Le Démocrate (Ferdinand Samba)",
        type: "Independent commercial media",
      },
      editorialStance: "Historic independent daily paper; democratic governance, civil society advocacy, and political reporting in Bangui",
      readership: {
        metric: "One of the longest-running private daily newspapers in Bangui",
        source: "Union des Journalistes de Centrafrique 2023",
      },
      revenueModel: "Street print sales and private advertising",
      logo: "newspaper-logos/cf/le-démocrate.svg",
      logoExplainer:
        "White banner with bold black masthead 'LE DÉMOCRATE', symbolising democratic transition and independent press history in CAR.",
      sources: ["https://www.le-democrate.com", "https://fr.wikipedia.org/wiki/M%C3%A9dias_en_R%C3%A9publique_centrafricaine"],
    },
    {
      id: "cf-le-potentiel-centrafricain",
      countryCode: "CF",
      name: "Le Potentiel Centrafricain",
      englishTranslation: "The Central African Potential",
      founded: 2000,
      frequency: "Daily newspaper",
      format: "Tabloid & digital portal",
      language: "French",
      headquarters: "Bangui",
      owner: {
        name: "Groupe Le Potentiel Centrafricain",
        type: "Independent commercial media",
      },
      editorialStance: "Independent commercial daily; national politics, economic reconstruction, and Central African mining/forestry sectors",
      readership: {
        metric: "Regular daily print circulation in Bangui commercial districts",
        source: "Haut Conseil de la Communication RCA 2023",
      },
      revenueModel: "Print sales and public legal notice advertising",
      logo: "newspaper-logos/cf/le-potentiel-centrafricain.svg",
      logoExplainer:
        "White banner with prominent green and black lettering 'Le Potentiel Centrafricain', representing national reconstruction.",
      sources: ["https://lepotentielcentrafricain.com", "https://fr.wikipedia.org/wiki/M%C3%A9dias_en_R%C3%A9publique_centrafricaine"],
    },
    {
      id: "cf-corbeau-news-centrafrique",
      countryCode: "CF",
      name: "Corbeau News Centrafrique",
      founded: 2014,
      frequency: "Continuous digital news portal",
      format: "Digital investigative news portal",
      language: "French, Sango",
      headquarters: "Bangui",
      owner: {
        name: "CNC Media Network (Gisèle Moloma)",
        type: "Independent commercial media",
      },
      editorialStance: "Independent digital investigative portal; security reporting, armed group movements, and political accountability",
      readership: {
        metric: "Over 850,000 monthly digital visitors across Central African Republic and international diaspora",
        source: "Corbeau News Analytics 2024",
      },
      revenueModel: "Digital web advertising and private reader donations",
      logo: "newspaper-logos/cf/corbeau-news-centrafrique.svg",
      logoExplainer:
        "Dark charcoal banner with bold white text 'CNC' and 'Corbeau News Centrafrique', symbolising independent investigative news.",
      sources: ["https://corbeaunews-centrafrique.org"],
    },
    {
      id: "cf-l-expansion",
      countryCode: "CF",
      name: "L'Expansion",
      englishTranslation: "The Expansion",
      founded: 1996,
      frequency: "Weekly newspaper",
      format: "Tabloid publication",
      language: "French",
      headquarters: "Bangui",
      owner: {
        name: "Éditions L'Expansion Centrafrique",
        type: "Independent commercial media",
      },
      editorialStance: "Weekly independent publication; macroeconomic developments, agricultural reform, and Central African trade",
      readership: {
        metric: "Read by business professionals, development agencies, and civil servants in Bangui",
        source: "Ministère de la Communication RCA 2023",
      },
      revenueModel: "Print sales and corporate sponsorships",
      logo: "newspaper-logos/cf/l-expansion.svg",
      logoExplainer:
        "Clean white masthead with blue serif title 'L'EXPANSION', representing economic focus and development journalism.",
      sources: ["https://fr.wikipedia.org/wiki/M%C3%A9dias_en_R%C3%A9publique_centrafricaine"],
    },
  ],

  // Chad
  TD: [
    {
      id: "td-tchadinfos",
      countryCode: "TD",
      name: "Tchadinfos",
      founded: 2012,
      frequency: "Continuous 24/7 digital news service",
      format: "Digital multimedia portal & web TV",
      language: "French, Arabic",
      headquarters: "N'Djamena",
      owner: {
        name: "Mamadou Djimtebaye / Tchadinfos Media Group",
        type: "Independent commercial media",
      },
      editorialStance: "Leading independent digital multimedia network in Chad; breaking national news, politics, and youth entrepreneurship",
      readership: {
        metric: "Over 2.2 million monthly page views; premier online news destination in Chad",
        source: "Tchadinfos Audience Review 2024",
      },
      revenueModel: "Digital advertising, video production, and corporate media partnerships",
      logo: "newspaper-logos/td/tchadinfos.svg",
      logoExplainer:
        "Teal green title banner with bold white lettering 'tchadinfos', symbolising modern Chadian digital news innovation.",
      sources: ["https://tchadinfos.com", "https://fr.wikipedia.org/wiki/Tchadinfos.com"],
    },
    {
      id: "td-alwihda-info",
      countryCode: "TD",
      name: "Alwihda Info",
      nativeName: "الوحدة انفو",
      englishTranslation: "Unity Info",
      founded: 1994,
      frequency: "Continuous digital newswire",
      format: "Digital news portal & web daily",
      language: "French, Arabic",
      headquarters: "N'Djamena",
      owner: {
        name: "Djamil Ahmat / Alwihda Media Group",
        type: "Independent commercial media",
      },
      editorialStance: "Independent news portal; Sahelian regional security, political transitions, and human rights advocacy",
      readership: {
        metric: "Widely read across the Lake Chad Basin, CEMAC region, and diaspora with 1.5M monthly visits",
        source: "Alwihda Info Analytics 2023",
      },
      revenueModel: "Online banner advertising and media consulting",
      logo: "newspaper-logos/td/alwihda-info.svg",
      logoExplainer:
        "White banner featuring red and black font 'ALWIHDA INFO', representing national unity and comprehensive Sahel coverage.",
      sources: ["https://www.alwihdainfo.com", "https://fr.wikipedia.org/wiki/Alwihda_Info"],
    },
    {
      id: "td-journal-le-pays",
      countryCode: "TD",
      name: "Le Pays",
      englishTranslation: "The Country",
      founded: 2011,
      frequency: "Weekly newspaper & daily web portal",
      format: "Tabloid & digital portal",
      language: "French",
      headquarters: "N'Djamena",
      owner: {
        name: "Madjiasra Nako / Le Pays Médias",
        type: "Independent commercial media",
      },
      editorialStance: "Independent investigative weekly; political governance, social inequalities, and environmental reporting in Chad",
      readership: {
        metric: "Leading investigative print weekly newspaper in N'Djamena",
        source: "Union des Journalistes Tchadiens 2023",
      },
      revenueModel: "Print retail sales and private advertisements",
      logo: "newspaper-logos/td/journal-le-pays.svg",
      logoExplainer:
        "Emerald green badge with white typography 'LE PAYS', reflecting agricultural resilience and independent public oversight.",
      sources: ["https://lepaystchad.com"],
    },
    {
      id: "td-le-progres",
      countryCode: "TD",
      name: "Le Progrès",
      englishTranslation: "The Progress",
      founded: 1993,
      frequency: "Daily newspaper",
      format: "Tabloid daily paper",
      language: "French",
      headquarters: "N'Djamena",
      owner: {
        name: "Éditions Le Progrès (Abderahmane Koulamallah)",
        type: "Independent commercial media",
      },
      editorialStance: "Historic private daily newspaper in Chad; national political developments, civil service news, and civic commentary",
      readership: {
        metric: "Pioneer private daily publication in Chad with wide institutional circulation in the capital",
        source: "Haute Autorité des Médias et de l'Audiovisuel (HAMA) 2023",
      },
      revenueModel: "Print sales and official notices",
      logo: "newspaper-logos/td/le-progrès.svg",
      logoExplainer:
        "Deep navy blue masthead with white serif font 'LE PROGRÈS', symbolising historic democratic press evolution in Chad.",
      sources: ["https://fr.wikipedia.org/wiki/Le_Progr%C3%A8s_(Tchad)"],
    },
    {
      id: "td-n-djamena-hebdo",
      countryCode: "TD",
      name: "N'Djaména Hebdo",
      englishTranslation: "N'Djamena Weekly",
      founded: 1989,
      frequency: "Weekly newspaper",
      format: "Tabloid publication",
      language: "French",
      headquarters: "N'Djamena",
      owner: {
        name: "Yaldet Bégoto Oulatar",
        type: "Independent commercial media",
      },
      editorialStance: "Historic pioneer of independent print journalism in Chad; courageous press freedom advocate and democratic commentary",
      readership: {
        metric: "Longest continuously operating independent weekly paper in Chad since 1989",
        source: "Reporters Without Borders & HAMA Chad 2023",
      },
      revenueModel: "Print retail sales and classified advertisements",
      logo: "newspaper-logos/td/n-djamena-hebdo.svg",
      logoExplainer:
        "White canvas displaying bold black masthead 'N'DJAMÉNA HEBDO', representing thirty-five years of independent Chadian press.",
      sources: ["https://fr.wikipedia.org/wiki/N%27Djam%C3%A9na_Hebdo"],
    },
  ],

  // Chile
  CL: [
    {
      id: "cl-el-mercurio",
      countryCode: "CL",
      name: "El Mercurio",
      englishTranslation: "The Mercury",
      founded: 1900,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Spanish",
      headquarters: "Santiago",
      owner: {
        name: "Empresa El Mercurio S.A.P. (Edwards family)",
        type: "Independent commercial media",
      },
      editorialStance: "Chile's historic conservative newspaper of record; business, legal affairs, national politics, and international diplomacy",
      readership: {
        metric: "Leading national newspaper of record with over 120,000 daily print circulation and Emol.com digital portal reaching 8M+ monthly readers",
        source: "El Mercurio SAP Memoria Anual 2023",
      },
      revenueModel: "Print sales, digital subscriptions, and display advertising",
      logo: "newspaper-logos/cl/el-mercurio.svg",
      logoExplainer:
        "White banner displaying the classic black gothic and serif masthead 'EL MERCURIO', representing Chile's oldest major news institution.",
      sources: ["https://www.elmercurio.com", "https://en.wikipedia.org/wiki/El_Mercurio"],
    },
    {
      id: "cl-la-tercera",
      countryCode: "CL",
      name: "La Tercera",
      englishTranslation: "The Third",
      founded: 1950,
      frequency: "Daily newspaper & continuous digital portal",
      format: "Berliner & digital portal",
      language: "Spanish",
      headquarters: "Santiago",
      owner: {
        name: "Copesa (Consorcio Periodístico de Chile S.A.)",
        type: "Independent commercial media",
      },
      editorialStance: "Center-right mainstream daily; national political analysis, investigative reports (La Tercera PM), and business coverage (Pulso)",
      readership: {
        metric: "Over 6.5 million monthly unique digital visitors across latercera.com and Pulso",
        source: "Copesa Audience Report 2024",
      },
      revenueModel: "Digital paywall subscriptions, print sales, and programmatic advertising",
      logo: "newspaper-logos/cl/la-tercera.svg",
      logoExplainer:
        "Vibrant red banner with bold white lowercase typography 'la tercera', reflecting modern investigative and dynamic daily reporting.",
      sources: ["https://www.latercera.com", "https://en.wikipedia.org/wiki/La_Tercera"],
    },
    {
      id: "cl-diario-financiero",
      countryCode: "CL",
      name: "Diario Financiero",
      englishTranslation: "Financial Daily",
      founded: 1988,
      frequency: "Daily business newspaper (Monday–Friday)",
      format: "Salmon broadsheet & digital portal",
      language: "Spanish",
      headquarters: "Santiago",
      owner: {
        name: "Grupo Claro",
        type: "Independent commercial media",
      },
      editorialStance: "Specialized financial and economic daily; Santiago Stock Exchange, mining industries, retail markets, and regulatory affairs",
      readership: {
        metric: "Primary business daily in Chile read by corporate executives and financial institutions (2.5M monthly visits)",
        source: "Diario Financiero Media Kit 2024",
      },
      revenueModel: "Corporate subscriptions and financial sector advertising",
      logo: "newspaper-logos/cl/diario-financiero.svg",
      logoExplainer:
        "White banner with distinctive navy blue lettering 'DF DIARIO FINANCIERO', symbolising market analysis and corporate integrity.",
      sources: ["https://www.df.cl", "https://es.wikipedia.org/wiki/Diario_Financiero"],
    },
    {
      id: "cl-las-ultimas-noticias",
      countryCode: "CL",
      name: "Las Últimas Noticias",
      englishTranslation: "The Latest News",
      founded: 1902,
      frequency: "Daily newspaper",
      format: "Tabloid & digital portal",
      language: "Spanish",
      headquarters: "Santiago",
      owner: {
        name: "Empresa El Mercurio S.A.P.",
        type: "Independent commercial media",
      },
      editorialStance: "Mass-circulation popular daily; sports, technology trends, popular culture, and human interest stories",
      readership: {
        metric: "Highest print retail circulation among popular tabloids in Chile with 100,000+ daily copies",
        source: "LUN Media Metrics 2023",
      },
      revenueModel: "Retail print sales and retail commercial advertising",
      logo: "newspaper-logos/cl/las-últimas-noticias.svg",
      logoExplainer:
        "Royal blue background with bright yellow and white typography 'LUN Las Últimas Noticias', iconic across Chilean newsstands.",
      sources: ["https://www.lun.com", "https://en.wikipedia.org/wiki/Las_%C3%9Altimas_Noticias"],
    },
    {
      id: "cl-the-clinic",
      countryCode: "CL",
      name: "The Clinic",
      founded: 1998,
      frequency: "Weekly publication & digital portal",
      format: "Satirical journal & digital portal",
      language: "Spanish",
      headquarters: "Santiago",
      owner: {
        name: "Ediciones The Clinic (Patricio Fernández)",
        type: "Independent commercial media",
      },
      editorialStance: "Left-leaning satirical and political investigative publication founded during Pinochet's London arrest; anti-establishment critique",
      readership: {
        metric: "Cult political publication reaching 1.2 million monthly readers across cultural and academic sectors",
        source: "The Clinic Audience Review 2023",
      },
      revenueModel: "Print sales, digital display advertising, and reader memberships",
      logo: "newspaper-logos/cl/the-clinic.svg",
      logoExplainer:
        "Dark black banner with bold white text 'THE CLINIC', symbolising sharp political satire and counter-cultural investigative journalism.",
      sources: ["https://www.theclinic.cl", "https://en.wikipedia.org/wiki/The_Clinic_(newspaper)"],
    },
  ],

  // China
  CN: [
    {
      id: "cn-people-s-daily",
      countryCode: "CN",
      name: "People's Daily",
      officialName: "People's Daily (Renmin Ribao)",
      nativeName: "人民日报",
      englishTranslation: "People's Daily",
      founded: 1948,
      frequency: "Daily newspaper",
      format: "Official state broadsheet & digital network",
      language: "Chinese (Simplified), with foreign language editions",
      headquarters: "Chaoyang District, Beijing",
      owner: {
        name: "Central Committee of the Chinese Communist Party",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official newspaper of the Central Committee of the CCP; authoritative voice on national policies, ideological guidelines, and central government affairs",
      readership: {
        metric: "Largest print circulation in China with 3.2 million daily copies and global online reach exceeding 100 million across People.cn",
        source: "People's Daily Annual Report 2023",
      },
      revenueModel: "State institutional subscriptions, official public notices, and digital media advertising",
      logo: "newspaper-logos/cn/people-s-daily.svg",
      logoExplainer:
        "Crimson red banner featuring golden-yellow calligraphic characters '人民日报' written by Mao Zedong, the defining insignia of China's principal state paper.",
      sources: ["http://en.people.cn", "https://en.wikipedia.org/wiki/People%27s_Daily"],
    },
    {
      id: "cn-china-daily",
      countryCode: "CN",
      name: "China Daily",
      nativeName: "中国日报",
      englishTranslation: "China Daily",
      founded: 1981,
      frequency: "Daily newspaper",
      format: "Broadsheet & international digital portal",
      language: "English",
      headquarters: "Beijing",
      owner: {
        name: "State Council Information Office",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "China's premier national English-language daily; international diplomacy, global business, trade, and cultural exchange",
      readership: {
        metric: "Over 900,000 daily global print distribution and 350+ million digital and social media followers worldwide",
        source: "China Daily Global Media Kit 2024",
      },
      annualPublicFunding: {
        total: "Direct central state foreign communication appropriation",
        perCapita: "National international communication remit",
      },
      revenueModel: "Central state foreign-press budget, global institutional subscriptions, and advertising",
      logo: "newspaper-logos/cn/china-daily.svg",
      logoExplainer:
        "Navy blue banner displaying the refined white serif masthead 'CHINA DAILY', representing China's primary international English voice.",
      sources: ["https://www.chinadaily.com.cn", "https://en.wikipedia.org/wiki/China_Daily"],
    },
    {
      id: "cn-reference-news",
      countryCode: "CN",
      name: "Reference News",
      officialName: "Cankao Xiaoxi",
      nativeName: "参考消息",
      englishTranslation: "Reference News",
      founded: 1931,
      frequency: "Daily newspaper",
      format: "Broadsheet digest",
      language: "Chinese",
      headquarters: "Beijing",
      owner: {
        name: "Xinhua News Agency",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Foreign affairs digest published by Xinhua; translating and reprinting international news coverage and commentary for domestic readership",
      readership: {
        metric: "Over 2.5 million daily print circulation; historically one of China's most widely read daily digests",
        source: "Xinhua Media Research 2023",
      },
      revenueModel: "Institutional and retail print subscriptions",
      logo: "newspaper-logos/cn/reference-news.svg",
      logoExplainer:
        "White canvas with black calligraphic Chinese characters '参考消息' penned by Lu Xun, symbolising curated international news insights.",
      sources: ["http://www.cankaoxiaoxi.com", "https://en.wikipedia.org/wiki/Reference_News"],
    },
    {
      id: "cn-huanqiu-shibao",
      countryCode: "CN",
      name: "Global Times",
      officialName: "Huanqiu Shibao",
      nativeName: "环球时报",
      englishTranslation: "Global Times",
      founded: 1993,
      frequency: "Daily newspaper (Chinese & English editions)",
      format: "Tabloid & international digital portal",
      language: "Chinese, English",
      headquarters: "Beijing",
      owner: {
        name: "People's Daily Press",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Nationalist international affairs daily affiliated with People's Daily; vocal coverage of foreign relations, geopolitics, and sovereignty",
      readership: {
        metric: "Over 1.5 million daily print circulation in Chinese plus extensive international web traffic on GlobalTimes.cn",
        source: "Global Times Audience Report 2023",
      },
      revenueModel: "Print sales, corporate advertising, and digital subscriptions",
      logo: "newspaper-logos/cn/huanqiu-shibao.svg",
      logoExplainer:
        "Burgundy red banner with white typography 'GLOBAL TIMES' and Chinese characters '环球时报', symbolising forthright geopolitical reporting.",
      sources: ["https://www.globaltimes.cn", "https://en.wikipedia.org/wiki/Global_Times"],
    },
    {
      id: "cn-nanfang-ribao",
      countryCode: "CN",
      name: "Nanfang Daily",
      officialName: "Southern Daily",
      nativeName: "南方日报",
      englishTranslation: "Southern Daily",
      founded: 1949,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital multimedia network",
      language: "Chinese",
      headquarters: "Guangzhou, Guangdong",
      owner: {
        name: "Nanfang Media Group",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official newspaper of the Guangdong Provincial Committee of the CCP; flagship of Nanfang Media Group covering the Greater Bay Area economy",
      readership: {
        metric: "Leading regional provincial broadsheet with 950,000+ daily copies across Guangdong, Hong Kong, and Macau",
        source: "Nanfang Media Group Annual Review 2023",
      },
      revenueModel: "Provincial institutional subscriptions and regional commercial advertising",
      logo: "newspaper-logos/cn/nanfang-ribao.svg",
      logoExplainer:
        "White banner displaying red calligraphic characters '南方日报', representing the dynamic Greater Bay Area and Guangdong journalism.",
      sources: ["https://www.nanfangdaily.com.cn", "https://en.wikipedia.org/wiki/Nanfang_Daily"],
    },
  ],

  // Colombia
  CO: [
    {
      id: "co-el-tiempo",
      countryCode: "CO",
      name: "El Tiempo",
      englishTranslation: "The Time",
      founded: 1911,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Spanish",
      headquarters: "Bogotá",
      owner: {
        name: "Grupo Aval (Luis Carlos Sarmiento Angulo)",
        type: "Independent commercial media",
      },
      editorialStance: "Historic centrist newspaper of record in Colombia; national politics, economic policy, peace process analysis, and cultural reporting",
      readership: {
        metric: "Largest print circulation in Colombia and premier digital portal reaching over 14 million monthly unique visitors",
        source: "Casa Editorial El Tiempo Media Profile 2024",
      },
      revenueModel: "Digital subscriptions, print sales, and cross-media advertising",
      logo: "newspaper-logos/co/el-tiempo.svg",
      logoExplainer:
        "Navy blue title banner with white serif masthead 'EL TIEMPO', representing Colombia's preeminent historic daily newspaper.",
      sources: ["https://www.eltiempo.com", "https://en.wikipedia.org/wiki/El_Tiempo_(Colombia)"],
    },
    {
      id: "co-el-espectador",
      countryCode: "CO",
      name: "El Espectador",
      englishTranslation: "The Spectator",
      founded: 1887,
      frequency: "Daily digital portal & weekly Sunday print edition",
      format: "Tabloid & digital portal",
      language: "Spanish",
      headquarters: "Bogotá",
      owner: {
        name: "Valorem S.A. (Santo Domingo family)",
        type: "Independent commercial media",
      },
      editorialStance: "Colombia's oldest newspaper; historic progressive liberal stance known for legendary courageous investigative journalism against drug cartels and corruption",
      readership: {
        metric: "Revered quality investigative outlet with over 9 million monthly digital visitors on elespectador.com",
        source: "Valorem Annual Report 2023",
      },
      revenueModel: "Digital subscriber paywall, print sales, and civic journalism grants",
      logo: "newspaper-logos/co/el-espectador.svg",
      logoExplainer:
        "White banner displaying the iconic black gothic masthead 'El Espectador', symbolising heroic defence of press freedom in Colombia.",
      sources: ["https://www.elespectador.com", "https://en.wikipedia.org/wiki/El_Espectador_(newspaper)"],
    },
    {
      id: "co-el-colombiano",
      countryCode: "CO",
      name: "El Colombiano",
      englishTranslation: "The Colombian",
      founded: 1912,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Spanish",
      headquarters: "Medellín, Antioquia",
      owner: {
        name: "Grupo Gilinski",
        type: "Independent commercial media",
      },
      editorialStance: "Conservative regional broadsheet; principal voice of Antioquia and western Colombia focusing on business, industry, and regional politics",
      readership: {
        metric: "Dominant daily newspaper in Medellín and the coffee-growing axis with 3.5 million monthly digital readers",
        source: "El Colombiano Media Kit 2024",
      },
      revenueModel: "Print subscriptions, digital access plans, and regional advertising",
      logo: "newspaper-logos/co/el-colombiano.svg",
      logoExplainer:
        "Red banner with clean white serif font 'EL COLOMBIANO', representing century-old journalistic tradition in Antioquia.",
      sources: ["https://www.elcolombiano.com", "https://en.wikipedia.org/wiki/El_Colombiano"],
    },
    {
      id: "co-portafolio",
      countryCode: "CO",
      name: "Portafolio",
      englishTranslation: "Portfolio",
      founded: 1993,
      frequency: "Daily financial newspaper (Monday–Friday)",
      format: "Compact tabloid & financial portal",
      language: "Spanish",
      headquarters: "Bogotá",
      owner: {
        name: "Casa Editorial El Tiempo",
        type: "Independent commercial media",
      },
      editorialStance: "Premier financial and economic daily; Bogota stock market, macroeconomic indicators, foreign investment, and corporate mergers",
      readership: {
        metric: "Leading specialized financial daily read across Colombian corporate boardrooms and government ministries",
        source: "Portafolio Corporate Profile 2023",
      },
      revenueModel: "Financial corporate subscriptions and business-to-business advertising",
      logo: "newspaper-logos/co/portafolio.svg",
      logoExplainer:
        "Dark slate badge with clean white title 'PORTAFOLIO', symbolising authoritative financial analysis and business intelligence.",
      sources: ["https://www.portafolio.co", "https://es.wikipedia.org/wiki/Portafolio_(peri%C3%B3dico)"],
    },
    {
      id: "co-la-republica",
      countryCode: "CO",
      name: "La República",
      englishTranslation: "The Republic",
      founded: 1954,
      frequency: "Daily financial newspaper (Monday–Saturday)",
      format: "Salmon broadsheet & digital portal",
      language: "Spanish",
      headquarters: "Bogotá",
      owner: {
        name: "Editorial La República / Grupo Ardila Lülle",
        type: "Independent commercial media",
      },
      editorialStance: "Historic specialized business and economic newspaper founded by former President Mariano Ospina Pérez; economic policy and market reporting",
      readership: {
        metric: "Over 2.8 million monthly digital visitors and widespread institutional print circulation",
        source: "Grupo Ardila Lülle Media Review 2023",
      },
      revenueModel: "Corporate subscriptions and commercial banking advertising",
      logo: "newspaper-logos/co/la-república.svg",
      logoExplainer:
        "White banner displaying red and black serif lettering 'La República', representing Colombia's first dedicated economic daily.",
      sources: ["https://www.larepublica.co", "https://es.wikipedia.org/wiki/La_Rep%C3%BAblica_(Colombia)"],
    },
  ],

  // Comoros
  KM: [
    {
      id: "km-al-watwan",
      countryCode: "KM",
      name: "Al-Watwan",
      nativeName: "Al-Watwan",
      englishTranslation: "The Homeland",
      founded: 1985,
      frequency: "Daily newspaper (Monday–Friday)",
      format: "Official state daily broadsheet & digital portal",
      language: "French, Arabic",
      headquarters: "Moroni, Grande Comore",
      owner: {
        name: "Union of the Comoros (Ministère des Télécommunications)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official national public daily newspaper; presidential decrees, inter-island development, parliamentary affairs, and Indian Ocean diplomacy",
      readership: {
        metric: "Only national daily print newspaper in the Comoros, distributed across Grande Comore, Anjouan, and Mohéli",
        source: "Al-Watwan Presse d'État Rapport 2023",
      },
      annualPublicFunding: {
        total: "KMF 85 million (~US$185,000) national operating allocation",
        perCapita: "KMF 95 / person / year (~US$0.21)",
      },
      revenueModel: "State operating subsidy, print sales, and official legal notices",
      logo: "newspaper-logos/km/al-watwan.svg",
      logoExplainer:
        "Green title banner with white serif font 'AL-WATWAN', embodying the national color of Comoros and state press heritage.",
      sources: ["https://alwatwan.net", "https://fr.wikipedia.org/wiki/Al-Watwan"],
    },
    {
      id: "km-la-gazette-des-comores",
      countryCode: "KM",
      name: "La Gazette des Comores",
      englishTranslation: "The Comoros Gazette",
      founded: 1999,
      frequency: "Daily newspaper",
      format: "Tabloid & digital portal",
      language: "French",
      headquarters: "Moroni",
      owner: {
        name: "Housseine Saïd / Groupe La Gazette",
        type: "Independent commercial media",
      },
      editorialStance: "Independent commercial daily; political debates, social issues, regional economy, and human rights coverage in Comoros",
      readership: {
        metric: "Leading independent print and digital daily in Moroni with widespread readership across the islands",
        source: "Groupe La Gazette Media Review 2023",
      },
      revenueModel: "Print sales and local business advertising",
      logo: "newspaper-logos/km/la-gazette-des-comores.svg",
      logoExplainer:
        "White canvas displaying bold black font 'La Gazette des Comores', representing independent civic journalism.",
      sources: ["https://lagazettedescomores.com"],
    },
    {
      id: "km-habari-za-comores",
      countryCode: "KM",
      name: "Habari Za Comores",
      nativeName: "Habari Za Comores",
      englishTranslation: "News of Comoros",
      founded: 2010,
      frequency: "Continuous digital news portal",
      format: "Digital news portal",
      language: "French, Comorian (Shikomori)",
      headquarters: "Moroni",
      owner: {
        name: "Habari Media Network",
        type: "Independent commercial media",
      },
      editorialStance: "Independent digital news outlet; community news, cultural preservation, diaspora connections, and civic affairs",
      readership: {
        metric: "Over 450,000 monthly digital visitors across Comoros, Mayotte, and the French diaspora",
        source: "Habari Za Comores Analytics 2024",
      },
      revenueModel: "Digital banner advertising and diaspora promotions",
      logo: "newspaper-logos/km/habari-za-comores.svg",
      logoExplainer:
        "White banner with bold green and navy typography 'HABARI ZA COMORES', symbolising community news and archipelago culture.",
      sources: ["https://habarizacomores.com"],
    },
    {
      id: "km-comores-infos",
      countryCode: "KM",
      name: "Comores-Infos",
      englishTranslation: "Comoros News",
      founded: 2012,
      frequency: "Continuous digital news service",
      format: "Digital multimedia portal",
      language: "French",
      headquarters: "Moroni",
      owner: {
        name: "Comores Infos Médias",
        type: "Independent commercial media",
      },
      editorialStance: "Digital news and multimedia portal; breaking national news, sports, youth initiatives, and social commentary",
      readership: {
        metric: "High engagement on mobile and social networks across the island archipelago",
        source: "Comores Infos Digital Review 2023",
      },
      revenueModel: "Digital display ads and multimedia sponsorships",
      logo: "newspaper-logos/km/comores-infos.svg",
      logoExplainer:
        "Red title banner with modern white typography 'COMORES INFOS', symbolising dynamic digital breaking news.",
      sources: ["https://www.comoresinfos.net"],
    },
    {
      id: "km-mwali-info",
      countryCode: "KM",
      name: "Mwali Info",
      englishTranslation: "Mohéli News",
      founded: 2014,
      frequency: "Digital portal",
      format: "Regional digital news service",
      language: "French, Shikomori",
      headquarters: "Fomboni, Mohéli",
      owner: {
        name: "Collectif des Journalistes de Mohéli",
        type: "Independent commercial media",
      },
      editorialStance: "Regional media voice of Mohéli Island; biosphere reserve conservation, local governance, and island agricultural affairs",
      readership: {
        metric: "Primary news portal dedicated to Mohéli island affairs and ecological tourism",
        source: "Mohéli Media Collective 2023",
      },
      revenueModel: "Community sponsorships and tourism advertising",
      logo: "newspaper-logos/km/mwali-info.svg",
      logoExplainer:
        "Yellow title block with bold blue font 'MWALI INFO', reflecting the vibrant biodiversity and island heritage of Mohéli.",
      sources: ["https://fr.wikipedia.org/wiki/Moh%C3%A9li"],
    },
  ],

  // Republic of the Congo
  CG: [
    {
      id: "cg-aci",
      countryCode: "CG",
      name: "ACI",
      officialName: "Agence Congolaise d'Information",
      nativeName: "Agence Congolaise d'Information",
      englishTranslation: "Congolese Information Agency",
      founded: 1961,
      frequency: "Continuous 24/7 national newswire",
      format: "Official state newswire & bulletin",
      language: "French",
      headquarters: "Brazzaville",
      owner: {
        name: "Republic of the Congo (Ministère de la Communication)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official national public newswire; executive decisions, legislative proceedings, diplomatic cooperation, and forestry development",
      readership: {
        metric: "Primary news supplier to all domestic broadcast networks and print titles across Brazzaville and Pointe-Noire",
        source: "ACI Brazzaville Rapport Annuel 2023",
      },
      annualPublicFunding: {
        total: "XAF 180 million (~US$295,000) state operating subsidy",
        perCapita: "XAF 30 / person / year (~US$0.05)",
      },
      revenueModel: "State budget allocation and wire syndication fees",
      logo: "newspaper-logos/cg/aci-agence-congolaise-d-information.svg",
      logoExplainer:
        "Deep blue banner with crisp white letters 'ACI Agence Congolaise d'Information', representing the statutory news agency of Congo-Brazzaville.",
      sources: ["https://www.aci.cg", "https://fr.wikipedia.org/wiki/Agence_congolaise_d%27information"],
    },
    {
      id: "cg-les-depeches-de-brazzaville",
      countryCode: "CG",
      name: "Les Dépêches de Brazzaville",
      englishTranslation: "Brazzaville Dispatches",
      founded: 1998,
      frequency: "Daily newspaper (Monday–Friday)",
      format: "Berliner & international portal",
      language: "French",
      headquarters: "Brazzaville",
      owner: {
        name: "Agence d'Information d'Afrique Centrale (ADIAC)",
        type: "Independent commercial media",
      },
      editorialStance: "Leading national daily newspaper; Central African geopolitics, cultural festivals, public infrastructure, and pan-African diplomacy",
      readership: {
        metric: "Largest print daily circulation in the Republic of the Congo with 15,000 daily print copies",
        source: "ADIAC Corporate Review 2023",
      },
      revenueModel: "Print sales, cultural sponsorships, and institutional subscriptions",
      logo: "newspaper-logos/cg/les-dépêches-de-brazzaville.svg",
      logoExplainer:
        "Black background with white serif title 'Les Dépêches de Brazzaville', the most prominent daily masthead in the Congo Basin.",
      sources: ["https://www.lesdepechesdebrazzaville.fr", "https://fr.wikipedia.org/wiki/Les_D%C3%A9p%C3%AAches_de_Brazzaville"],
    },
    {
      id: "cg-la-semaine-africaine",
      countryCode: "CG",
      name: "La Semaine Africaine",
      englishTranslation: "The African Week",
      founded: 1952,
      frequency: "Bi-weekly publication (Tuesday & Friday)",
      format: "Tabloid publication & digital portal",
      language: "French",
      headquarters: "Brazzaville",
      owner: {
        name: "Episcopal Conference of the Congo (Catholic Church)",
        type: "Independent trust / foundation",
      },
      editorialStance: "Historic independent bi-weekly; social justice, pastoral advocacy, ethical governance, and civil society reflection",
      readership: {
        metric: "Over 70 years of continuous publishing; highly respected independent moral authority in Congolese media",
        source: "La Semaine Africaine Archive 2023",
      },
      revenueModel: "Print circulation, church subscriptions, and civic announcements",
      logo: "newspaper-logos/cg/la-semaine-africaine.svg",
      logoExplainer:
        "White banner with bold green and black lettering 'La Semaine Africaine', symbolising historic moral and civic journalism.",
      sources: ["https://lasemaineafricaine.info", "https://fr.wikipedia.org/wiki/La_Semaine_africaine"],
    },
    {
      id: "cg-le-patriote",
      countryCode: "CG",
      name: "Le Patriote",
      englishTranslation: "The Patriot",
      founded: 2000,
      frequency: "Weekly newspaper",
      format: "Tabloid publication",
      language: "French",
      headquarters: "Brazzaville",
      owner: {
        name: "Groupe Le Patriote",
        type: "Independent commercial media",
      },
      editorialStance: "Weekly independent newspaper; national political debates, regional economic corridors, and social development",
      readership: {
        metric: "Popular weekly print edition in administrative centers of Brazzaville and Pointe-Noire",
        source: "Conseil Supérieur de la Liberté de Communication 2023",
      },
      revenueModel: "Print retail sales and local advertising",
      logo: "newspaper-logos/cg/le-patriote.svg",
      logoExplainer:
        "Red title banner with bold white lettering 'LE PATRIOTE', representing national civic engagement and public debate.",
      sources: ["https://fr.wikipedia.org/wiki/M%C3%A9dias_en_R%C3%A9publique_du_Congo"],
    },
    {
      id: "cg-vox-congo",
      countryCode: "CG",
      name: "Vox Congo",
      founded: 2017,
      frequency: "Continuous digital multimedia service",
      format: "Digital multimedia portal & Web TV",
      language: "French",
      headquarters: "Brazzaville",
      owner: {
        name: "Vox Médias Group",
        type: "Independent commercial media",
      },
      editorialStance: "Modern multimedia and digital TV platform; youth culture, sports, technological entrepreneurship, and urban lifestyle",
      readership: {
        metric: "Leading digital native video and news platform in Brazzaville with 500,000+ monthly engagements",
        source: "Vox Congo Audience Review 2024",
      },
      revenueModel: "Digital video advertising and sponsored corporate media",
      logo: "newspaper-logos/cg/vox-congo.svg",
      logoExplainer:
        "White banner with vibrant red and black logo 'VOX', representing modern digital television and youth-oriented journalism.",
      sources: ["https://www.vox.cg"],
    },
  ],

  // Democratic Republic of the Congo
  CD: [
    {
      id: "cd-acp",
      countryCode: "CD",
      name: "ACP",
      officialName: "Agence Congolaise de Presse",
      nativeName: "Agence Congolaise de Presse",
      englishTranslation: "Congolese Press Agency",
      founded: 1960,
      frequency: "Continuous 24/7 national newswire",
      format: "Official public wire service & daily bulletin",
      language: "French",
      headquarters: "Gombe, Kinshasa",
      owner: {
        name: "Democratic Republic of the Congo (Ministère de la Communication et Médias)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official public newswire of the DRC; presidential activity, national assembly decrees, provincial governors, and MONUSCO peace initiatives",
      readership: {
        metric: "Primary news supplier to over 500 radio, television, and print outlets across all 26 provinces of the DRC",
        source: "ACP Rapport de Gestion et Performance 2023",
      },
      annualPublicFunding: {
        total: "CDF 4.5 billion (~US$1.65 million) state budget allocation",
        perCapita: "CDF 45 / person / year (~US$0.016)",
      },
      revenueModel: "Direct state budget subsidy and institutional subscriber feeds",
      logo: "newspaper-logos/cd/acp-agence-congolaise-de-presse.svg",
      logoExplainer:
        "Navy blue background with bold white lettering 'ACP' and full title, symbolising the official state wire service of the DRC.",
      sources: ["https://acp.cd", "https://fr.wikipedia.org/wiki/Agence_congolaise_de_presse"],
    },
    {
      id: "cd-le-potentiel",
      countryCode: "CD",
      name: "Le Potentiel",
      englishTranslation: "The Potential",
      founded: 1982,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Tabloid & digital portal",
      language: "French",
      headquarters: "Kinshasa",
      owner: {
        name: "Modeste Mutinga Mutuishayi / Groupe Le Potentiel",
        type: "Independent commercial media",
      },
      editorialStance: "DRC's benchmark independent daily newspaper; recognized for in-depth economic analysis, governance monitoring, and constitutional reform debate",
      readership: {
        metric: "Most influential intellectual daily in Kinshasa and Lubumbashi with 1.2 million monthly web readers on lepotentiel.cd",
        source: "Groupe Le Potentiel Profile 2023",
      },
      revenueModel: "Print sales, institutional advertising, and online sponsorships",
      logo: "newspaper-logos/cd/le-potentiel.svg",
      logoExplainer:
        "Deep blue banner with white serif font 'Le Potentiel', representing decades of independent investigative journalism in Central Africa.",
      sources: ["https://lepotentiel.cd", "https://fr.wikipedia.org/wiki/Le_Potentiel"],
    },
    {
      id: "cd-actualite-cd",
      countryCode: "CD",
      name: "ACTUALITE.CD",
      founded: 2016,
      frequency: "Continuous 24/7 digital news service",
      format: "Digital multimedia portal & podcasts",
      language: "French",
      headquarters: "Kinshasa",
      owner: {
        name: "Next Corp (Patient Ligodi)",
        type: "Independent commercial media",
      },
      editorialStance: "Leading independent digital news portal in the DRC; high-tempo breaking news, eastern DRC security coverage, electoral tracking, and podcast journalism",
      readership: {
        metric: "Over 3.5 million monthly pageviews; premier digital news reference for Congolese youth and civil society",
        source: "Actualite.cd Audience Review 2024",
      },
      revenueModel: "Digital display advertising, international donor media grants, and syndicated reporting",
      logo: "newspaper-logos/cd/actualite-cd.svg",
      logoExplainer:
        "Dark charcoal banner with bold white text 'ACTUALITE.CD' and vivid red dot, symbolising real-time breaking news.",
      sources: ["https://actualite.cd"],
    },
    {
      id: "cd-l-avenir",
      countryCode: "CD",
      name: "L'Avenir",
      englishTranslation: "The Future",
      founded: 1996,
      frequency: "Daily newspaper",
      format: "Tabloid & digital portal",
      language: "French",
      headquarters: "Kinshasa",
      owner: {
        name: "Groupe L'Avenir (Pius Muabilu)",
        type: "Independent commercial media",
      },
      editorialStance: "Major Kinshasa commercial daily; national politics, parliamentary debates, infrastructure modernization, and cultural commentary",
      readership: {
        metric: "Prominent daily circulation in Kinshasa and central provinces with active digital platform groupelavenir.cd",
        source: "Groupe L'Avenir Media Review 2023",
      },
      revenueModel: "Print newspaper sales and commercial advertising",
      logo: "newspaper-logos/cd/l-avenir.svg",
      logoExplainer:
        "White banner featuring blue and red font 'L'AVENIR', representing optimistic national development and daily news.",
      sources: ["https://groupelavenir.cd", "https://fr.wikipedia.org/wiki/L%27Avenir_(journal_congolais)"],
    },
    {
      id: "cd-la-prosperite",
      countryCode: "CD",
      name: "La Prospérité",
      englishTranslation: "The Prosperity",
      founded: 1999,
      frequency: "Daily newspaper (Monday–Friday)",
      format: "Tabloid publication & digital portal",
      language: "French",
      headquarters: "Kinshasa",
      owner: {
        name: "Marcel Ngoyi Ngoyi / Éditions La Prospérité",
        type: "Independent commercial media",
      },
      editorialStance: "Independent commercial daily newspaper; detailed parliamentary reporting, judicial proceedings, and public policy debate",
      readership: {
        metric: "Widely read by legal practitioners, parliamentarians, and civil servants in Kinshasa",
        source: "CSAC RDC Media Registry 2023",
      },
      revenueModel: "Print sales and official legal publication notices",
      logo: "newspaper-logos/cd/la-prospérité.svg",
      logoExplainer:
        "Emerald green title banner with bold white typography 'La Prospérité', reflecting economic growth and national progress.",
      sources: ["https://laprosperite.online"],
    },
  ],
`;

const closingIndex = content.lastIndexOf("};");
if (closingIndex === -1) {
  throw new Error("Could not find closing '};' in " + dataFile);
}

const updatedContent = content.slice(0, closingIndex) + block4Entries + "};\n";
fs.writeFileSync(dataFile, updatedContent, "utf8");
console.log("✓ Successfully added Block 4 entries to src/data/nationalNewsAgencies.ts");
