import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const dataFile = path.join(root, "src/data/nationalNewsAgencies.ts");

let content = fs.readFileSync(dataFile, "utf8");

const block7Entries = `
  // Fiji
  FJ: [
    {
      id: "fj-fiji-times",
      countryCode: "FJ",
      name: "The Fiji Times",
      founded: 1869,
      frequency: "Daily newspaper (Monday–Sunday)",
      format: "Broadsheet & digital portal",
      language: "English",
      headquarters: "Suva, Viti Levu",
      owner: {
        name: "Motibhai Group",
        type: "Independent commercial media",
      },
      editorialStance: "Fiji's oldest newspaper and historic newspaper of record; independent, courageous reporting through military coups and constitutional crises, championing democracy and rule of law",
      readership: {
        metric: "Over 155 years of publishing; largest print circulation daily in Fiji and leading South Pacific news reference",
        source: "The Fiji Times Annual Review 2023",
      },
      revenueModel: "Print newsstand sales, commercial advertising, and digital subscriptions",
      logo: "newspaper-logos/fj/fiji-times.svg",
      logoExplainer:
        "Classic black gothic masthead 'The Fiji Times' on white canvas, symbolising the Pacific's longest running independent press institution.",
      sources: ["https://www.fijitimes.com.fj", "https://en.wikipedia.org/wiki/The_Fiji_Times"],
    },
    {
      id: "fj-fiji-sun",
      countryCode: "FJ",
      name: "Fiji Sun",
      founded: 2001,
      frequency: "Daily newspaper",
      format: "Tabloid & digital portal",
      language: "English",
      headquarters: "Walubay, Suva",
      owner: {
        name: "Sun (Fiji) News Limited (CJ Patel Group)",
        type: "Independent commercial media",
      },
      editorialStance: "Major national daily; focus on tourism, business developments, provincial news, and sports (rugby sevens)",
      readership: {
        metric: "Major daily circulation with widespread distribution across Viti Levu and Vanua Levu",
        source: "Fiji Sun Corporate Profile 2023",
      },
      revenueModel: "Print sales and corporate commercial advertising",
      logo: "newspaper-logos/fj/fiji-sun.svg",
      logoExplainer:
        "Vibrant golden-orange sunburst and bold blue lettering 'FIJI SUN', reflecting tropical energy and island daily news.",
      sources: ["https://fijisun.com.fj", "https://en.wikipedia.org/wiki/Fiji_Sun"],
    },
    {
      id: "fj-fiji-village",
      countryCode: "FJ",
      name: "FijiVillage",
      founded: 1998,
      frequency: "Continuous 24/7 digital news service",
      format: "Digital-only news portal & radio network",
      language: "English, Fijian, Hindi",
      headquarters: "Suva",
      owner: {
        name: "Communications Fiji Limited (CFL)",
        type: "Independent commercial media",
      },
      editorialStance: "Fiji's premier digital breaking news portal; multi-lingual coverage spanning five commercial radio stations (FM96, Legend FM, Radio Sargam, Navtarang, Viti FM)",
      readership: {
        metric: "Over 1.8 million monthly digital visitors across Fiji and the Pacific diaspora in Australia and New Zealand",
        source: "CFL Audience Analytics 2024",
      },
      revenueModel: "Digital display advertising, cross-media radio promotions, and sponsorships",
      logo: "newspaper-logos/fj/fiji-village.svg",
      logoExplainer:
        "Red and blue emblem with clean white typography 'FIJIVILLAGE', representing real-time breaking digital news.",
      sources: ["https://www.fijivillage.com", "https://en.wikipedia.org/wiki/Communications_Fiji_Limited"],
    },
    {
      id: "fj-fiji-report",
      countryCode: "FJ",
      name: "Fiji Report",
      founded: 2015,
      frequency: "Digital portal",
      format: "Digital business portal",
      language: "English",
      headquarters: "Suva",
      owner: {
        name: "Pacific Media Reports",
        type: "Independent commercial media",
      },
      editorialStance: "Business and financial reporting; Pacific Islands trade, sugar and kava exports, renewable energy, and climate adaptation financing",
      readership: {
        metric: "Read by business professionals, foreign investors, and regional development agencies",
        source: "Pacific Media Reports 2023",
      },
      revenueModel: "Corporate partnerships and digital subscriptions",
      logo: "newspaper-logos/fj/fiji-report.svg",
      logoExplainer:
        "Dark teal banner with white sans-serif text 'FIJI REPORT', symbolising economic analysis and sustainable island trade.",
      sources: ["https://fijireport.com"],
    },
    {
      id: "fj-maiviti",
      countryCode: "FJ",
      name: "Mai TV",
      officialName: "MaiViti",
      founded: 2008,
      frequency: "Continuous digital & television broadcasting",
      format: "Digital news portal & commercial TV",
      language: "English, Fijian",
      headquarters: "Suva",
      owner: {
        name: "Mai TV Ltd",
        type: "Independent commercial media",
      },
      editorialStance: "Independent commercial television network; community grassroots journalism, cultural storytelling, sports tournaments, and parliamentary coverage",
      readership: {
        metric: "Universal terrestrial and digital streaming reach across the Fiji archipelago",
        source: "Mai TV Broadcast Overview 2023",
      },
      revenueModel: "Television broadcast advertising and commercial production",
      logo: "newspaper-logos/fj/maiviti.svg",
      logoExplainer:
        "Bright blue and orange logo featuring the stylized Pacific wave 'mai tv', symbolising modern television broadcasting in Oceania.",
      sources: ["https://www.maitv.com.fj", "https://en.wikipedia.org/wiki/Mai_TV"],
    },
  ],

  // Finland
  FI: [
    {
      id: "fi-helsingin-sanomat",
      countryCode: "FI",
      name: "Helsingin Sanomat",
      officialName: "HS",
      nativeName: "Helsingin Sanomat",
      englishTranslation: "Helsinki News",
      founded: 1889,
      frequency: "Daily newspaper (Monday–Sunday)",
      format: "Tabloid format broadsheet & digital network",
      language: "Finnish",
      headquarters: "Sanomatalo, Töölönlahti, Helsinki",
      owner: {
        name: "Sanoma Media Finland",
        type: "Independent commercial media",
      },
      editorialStance: "Finland's preeminent newspaper of record and the largest subscription daily in the Nordic countries; independent liberal stance focusing on Nordic welfare, European security, technology, and arts",
      readership: {
        metric: "Over 2.2 million weekly readers across print and digital, with more than 450,000 paid digital subscribers on hs.fi",
        source: "Sanoma Corporation Annual Report 2023",
      },
      revenueModel: "Digital paywall subscriptions, print circulation, and corporate display advertising",
      logo: "newspaper-logos/fi/helsingin-sanomat.svg",
      logoExplainer:
        "Iconic black square emblem with white interlocking initials 'HS' and classic serif typography, the benchmark insignia of Finnish journalism.",
      sources: ["https://www.hs.fi", "https://en.wikipedia.org/wiki/Helsingin_Sanomat"],
    },
    {
      id: "fi-iltalehti",
      countryCode: "FI",
      name: "Iltalehti",
      nativeName: "Iltalehti",
      englishTranslation: "Evening Newspaper",
      founded: 1980,
      frequency: "Continuous digital news service & daily print",
      format: "Digital-first portal & daily tabloid",
      language: "Finnish",
      headquarters: "Helsinki",
      owner: {
        name: "Alma Media Corporation",
        type: "Independent commercial media",
      },
      editorialStance: "Finland's premier digital news brand; breaking news, visual investigative reporting, consumer guides, political scoops, and lifestyle",
      readership: {
        metric: "Over 3.1 million weekly digital users on iltalehti.fi; highest weekly digital reach in Finland",
        source: "FIAM (Finnish Internet Audience Measurement) 2024",
      },
      revenueModel: "Digital subscriptions (IL Plus), programmatic ads, and print newsstand sales",
      logo: "newspaper-logos/fi/iltalehti.svg",
      logoExplainer:
        "Vibrant red banner with clean white typography 'ILTALEHTI', symbolising fast-paced breaking digital news across Finland.",
      sources: ["https://www.iltalehti.fi", "https://en.wikipedia.org/wiki/Iltalehti"],
    },
    {
      id: "fi-ilta-sanomat",
      countryCode: "FI",
      name: "Ilta-Sanomat",
      officialName: "IS",
      nativeName: "Ilta-Sanomat",
      englishTranslation: "Evening News",
      founded: 1932,
      frequency: "Daily newspaper & continuous digital portal",
      format: "Tabloid publication & digital network",
      language: "Finnish",
      headquarters: "Helsinki",
      owner: {
        name: "Sanoma Media Finland",
        type: "Independent commercial media",
      },
      editorialStance: "Major commercial daily founded during the Mäntsälä rebellion; breaking news, sports (ice hockey / SM-liiga), entertainment, and consumer investigative journalism",
      readership: {
        metric: "Over 2.9 million weekly digital visitors on is.fi and leading street print newspaper",
        source: "Sanoma Media Audience Review 2024",
      },
      revenueModel: "Digital advertising, premium digital packages (IS Extra), and retail sales",
      logo: "newspaper-logos/fi/ilta-sanomat.svg",
      logoExplainer:
        "Red and blue emblem featuring bold letters 'IS' and full title, iconic on Finnish newsstands since the 1930s.",
      sources: ["https://www.is.fi", "https://en.wikipedia.org/wiki/Ilta-Sanomat"],
    },
    {
      id: "fi-kauppalehti",
      countryCode: "FI",
      name: "Kauppalehti",
      nativeName: "Kauppalehti",
      englishTranslation: "Commerce Paper",
      founded: 1898,
      frequency: "Daily business newspaper (Monday–Friday)",
      format: "Salmon broadsheet & digital financial portal",
      language: "Finnish",
      headquarters: "Helsinki",
      owner: {
        name: "Alma Media Corporation",
        type: "Independent commercial media",
      },
      editorialStance: "Finland's preeminent financial and business daily; Helsinki Stock Exchange (Nasdaq Helsinki), corporate innovations, forestry, clean tech, and macroeconomic policy",
      readership: {
        metric: "Over 150,000 paid business subscribers; primary information source for Finnish business executives and investors",
        source: "Alma Media Corporate Review 2023",
      },
      revenueModel: "Corporate subscriptions and B2B financial advertising",
      logo: "newspaper-logos/fi/kauppalehti.svg",
      logoExplainer:
        "Dark green and black banner with bold sans-serif text 'Kauppalehti', representing Finnish corporate leadership and market analysis.",
      sources: ["https://www.kauppalehti.fi", "https://en.wikipedia.org/wiki/Kauppalehti"],
    },
    {
      id: "fi-hufvudstadsbladet",
      countryCode: "FI",
      name: "Hufvudstadsbladet",
      officialName: "HBL",
      nativeName: "Hufvudstadsbladet",
      englishTranslation: "Capital City Paper",
      founded: 1864,
      frequency: "Daily newspaper",
      format: "Tabloid & digital portal",
      language: "Swedish",
      headquarters: "Mannerheimintie, Helsinki",
      owner: {
        name: "Bonnier News (51%) & KSF Media / Konstsamfundet (49%)",
        type: "Independent commercial media",
      },
      editorialStance: "The flagship Swedish-language daily newspaper in Finland; cultural commentary, Nordic cooperation, minority language rights, and international diplomacy",
      readership: {
        metric: "Largest Swedish-language daily newspaper in Finland with over 40,000 paid subscribers and 250,000 monthly digital readers on hbl.fi",
        source: "KSF Media & Bonnier News 2024",
      },
      revenueModel: "Digital subscriptions, print sales, and cultural foundation support",
      logo: "newspaper-logos/fi/hufvudstadsbladet.svg",
      logoExplainer:
        "Historic black serif masthead 'Hufvudstadsbladet' with blue accent 'HBL', representing 160 years of Swedish-Finnish press tradition.",
      sources: ["https://www.hbl.fi", "https://en.wikipedia.org/wiki/Hufvudstadsbladet"],
    },
  ],

  // France
  FR: [
    {
      id: "fr-le-monde",
      countryCode: "FR",
      name: "Le Monde",
      englishTranslation: "The World",
      founded: 1944,
      frequency: "Daily newspaper (Monday–Saturday afternoon)",
      format: "Berliner format & global digital network",
      language: "French, English (Le Monde in English)",
      headquarters: "Boulevard Auguste-Blanqui, Paris",
      owner: {
        name: "Groupe Le Monde (Fonds pour l'Indépendance de la Presse / Xavier Niel)",
        type: "Independent trust / foundation",
      },
      editorialStance: "France's preeminent newspaper of record founded at the Liberation by Hubert Beuve-Méry; center-left independent intellectual stance with world-renowned investigative journalism and international analysis",
      readership: {
        metric: "Over 550,000 paid digital subscribers and more than 20 million monthly digital readers across French and English editions worldwide",
        source: "Groupe Le Monde Bilan Annuel 2023",
      },
      revenueModel: "Digital subscriptions, print circulation, and corporate advertising",
      logo: "newspaper-logos/fr/le-monde.svg",
      logoExplainer:
        "Iconic black gothic masthead 'Le Monde' designed in 1944, representing moral independence and authoritative intellectual journalism.",
      sources: ["https://www.lemonde.fr", "https://en.wikipedia.org/wiki/Le_Monde"],
    },
    {
      id: "fr-le-figaro",
      countryCode: "FR",
      name: "Le Figaro",
      englishTranslation: "The Figaro (named after Beaumarchais' character)",
      founded: 1826,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Broadsheet & digital portal",
      language: "French",
      headquarters: "Boulevard Haussmann, Paris",
      owner: {
        name: "Groupe Figaro (Dassault Group)",
        type: "Independent commercial media",
      },
      editorialStance: "Oldest national daily newspaper in France; center-right liberal-conservative newspaper of record known for literary culture, economic liberalism, and constitutional politics",
      readership: {
        metric: "Over 350,000 paid broadsheet and digital subscribers; top-ranking French digital news destination with 22M+ monthly visitors on lefigaro.fr",
        source: "ACPM (Alliance pour les Chiffres de la Presse et des Médias) 2024",
      },
      revenueModel: "Digital subscriptions, print sales, luxury advertising, and magazine supplements",
      logo: "newspaper-logos/fr/le-figaro.svg",
      logoExplainer:
        "Classic blue and black serif masthead 'LE FIGARO' accompanied by Beaumarchais' motto 'Sans la liberté de blâmer, il n'est point d'éloge flatteur'.",
      sources: ["https://www.lefigaro.fr", "https://en.wikipedia.org/wiki/Le_Figaro"],
    },
    {
      id: "fr-les-echos",
      countryCode: "FR",
      name: "Les Échos",
      englishTranslation: "The Echoes",
      founded: 1908,
      frequency: "Daily business newspaper (Monday–Friday)",
      format: "Berliner & digital financial network",
      language: "French",
      headquarters: "Paris",
      owner: {
        name: "Groupe Les Échos-Le Parisien (LVMH)",
        type: "Independent commercial media",
      },
      editorialStance: "France's leading financial and economic daily; CAC 40 market analysis, European Union fiscal policy, industrial innovation, and corporate strategy",
      readership: {
        metric: "Over 100,000 paid digital subscribers; mandatory daily reading for senior French executives and policymakers",
        source: "Groupe Les Échos-Le Parisien 2024",
      },
      revenueModel: "Corporate subscriptions and financial market advertising",
      logo: "newspaper-logos/fr/les-echos.svg",
      logoExplainer:
        "Red and black title banner with bold modern typography 'Les Echos', symbolising authoritative market intelligence.",
      sources: ["https://www.lesechos.fr", "https://en.wikipedia.org/wiki/Les_%C3%89chos_(France)"],
    },
    {
      id: "fr-liberation",
      countryCode: "FR",
      name: "Libération",
      englishTranslation: "Liberation",
      founded: 1973,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Tabloid publication & digital portal",
      language: "French",
      headquarters: "Paris",
      owner: {
        name: "Fonds de Dotation pour une Presse Indépendante (FDPI)",
        type: "Independent trust / foundation",
      },
      editorialStance: "Left-wing daily newspaper founded by Jean-Paul Sartre and Serge July; renowned for creative visual front pages, social justice, cultural critique, and civil liberties",
      readership: {
        metric: "Over 110,000 paid subscribers across print and digital platforms on liberation.fr",
        source: "Libération Rapport Financier 2023",
      },
      revenueModel: "Reader subscriptions, philanthropic endowment support, and advertising",
      logo: "newspaper-logos/fr/libération.svg",
      logoExplainer:
        "Iconic red rectangular emblem with bold white typography 'Libération', the visual hallmark of French progressive intellectual journalism.",
      sources: ["https://www.liberation.fr", "https://en.wikipedia.org/wiki/Lib%C3%A9ration"],
    },
    {
      id: "fr-ouest-france",
      countryCode: "FR",
      name: "Ouest-France",
      englishTranslation: "West France",
      founded: 1944,
      frequency: "Daily newspaper (Monday–Sunday)",
      format: "Berliner & comprehensive regional network",
      language: "French",
      headquarters: "Rennes, Brittany",
      owner: {
        name: "Association pour le Soutien des Principes de la Démocratie Humaniste",
        type: "Non-profit independent trust",
      },
      editorialStance: "Most read French-language newspaper in the world; non-profit Christian-humanist and pro-European democratic values, focusing on decentralised regional life and social cohesion",
      readership: {
        metric: "Over 630,000 daily print copies; highest circulation newspaper in France with over 2.5 million daily readers across 53 regional editions",
        source: "ACPM Chiffres de Diffusion 2024",
      },
      revenueModel: "Print subscriptions, retail kiosk sales, and local display advertising",
      logo: "newspaper-logos/fr/ouest-france.svg",
      logoExplainer:
        "Red and blue emblem with bold sans-serif lettering 'ouest france', representing grassroots democratic humanism in regional France.",
      sources: ["https://www.ouest-france.fr", "https://en.wikipedia.org/wiki/Ouest-France"],
    },
  ],

  // Gabon
  GA: [
    {
      id: "ga-l-union",
      countryCode: "GA",
      name: "L'Union",
      englishTranslation: "The Union",
      founded: 1974,
      frequency: "Daily newspaper (Monday–Friday)",
      format: "Broadsheet & digital portal",
      language: "French",
      headquarters: "Libreville",
      owner: {
        name: "Société Gabonaise d'Édition et de Presse (SONAPRESSE)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Gabon's historic national newspaper of record; government decrees, transition governance, extractive oil and mining industries, and environmental conservation",
      readership: {
        metric: "Largest print daily circulation in Gabon (~20,000 daily print copies) with universal institutional reach",
        source: "SONAPRESSE Rapport d'Activité 2023",
      },
      annualPublicFunding: {
        total: "XAF 350 million (~US$575,000) state public press subsidy",
        perCapita: "XAF 150 / person / year (~US$0.25)",
      },
      revenueModel: "State operating subsidies, retail print sales, and official legal notices",
      logo: "newspaper-logos/ga/l-union.svg",
      logoExplainer:
        "Deep blue title banner with white serif font 'L'UNION', symbolising national unity and public press heritage.",
      sources: ["https://www.union.sonapresse.com", "https://fr.wikipedia.org/wiki/L%27Union_(journal_gabonais)"],
    },
    {
      id: "ga-agp",
      countryCode: "GA",
      name: "AGP",
      officialName: "Agence Gabonaise de Presse",
      nativeName: "Agence Gabonaise de Presse",
      englishTranslation: "Gabonese Press Agency",
      founded: 1961,
      frequency: "Continuous 24/7 national newswire",
      format: "Official state wire service & daily bulletin",
      language: "French",
      headquarters: "Libreville",
      owner: {
        name: "Republic of Gabon (Ministère de la Communication)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Statutory national news agency; presidential activity, national transition council resolutions, provincial governors, and ECCAS diplomacy",
      readership: {
        metric: "Primary news supplier to national television (Gabon Télévisions), radio stations, and regional media",
        source: "AGP Direction Générale 2023",
      },
      annualPublicFunding: {
        total: "XAF 220 million (~US$360,000) state budget allocation",
        perCapita: "XAF 95 / person / year (~US$0.16)",
      },
      revenueModel: "State budget funding and wire subscription services",
      logo: "newspaper-logos/ga/agp-agence-gabonaise-de-presse.svg",
      logoExplainer:
        "Green, yellow, and blue emblem representing the national colors of Gabon with clean typography 'AGP'.",
      sources: ["https://agpgabon.ga", "https://fr.wikipedia.org/wiki/Agence_gabonaise_de_presse"],
    },
    {
      id: "ga-gabon-review",
      countryCode: "GA",
      name: "Gabon Review",
      founded: 2011,
      frequency: "Continuous digital news service",
      format: "Digital-only analytical portal",
      language: "French",
      headquarters: "Libreville",
      owner: {
        name: "BDP Gabao Media",
        type: "Independent commercial media",
      },
      editorialStance: "Leading independent digital news and analytical portal; critical political commentary, anti-corruption investigations, forestry governance, and civil society debate",
      readership: {
        metric: "Over 1.5 million monthly digital visitors across Gabon and the international diaspora",
        source: "Gabon Review Audience Report 2024",
      },
      revenueModel: "Digital display advertising, sponsored columns, and consulting",
      logo: "newspaper-logos/ga/gabon-review.svg",
      logoExplainer:
        "Red and black title banner with modern font 'GabonReview', symbolising fearless independent investigative journalism.",
      sources: ["https://www.gabonreview.com", "https://fr.wikipedia.org/wiki/Gabon_Review"],
    },
    {
      id: "ga-gabon-actu",
      countryCode: "GA",
      name: "Gabonactu.com",
      founded: 2012,
      frequency: "Continuous 24/7 digital news service",
      format: "Digital news portal & web TV",
      language: "French",
      headquarters: "Libreville",
      owner: {
        name: "Groupe Gabonactu (Yves-Laurent Goma)",
        type: "Independent commercial media",
      },
      editorialStance: "Real-time digital breaking news; politics, social movements, judicial affairs, and community reporting across Gabon's 9 provinces",
      readership: {
        metric: "Over 1.2 million monthly digital page views; top-ranked digital breaking news destination in Libreville",
        source: "Gabonactu Analytics 2023",
      },
      revenueModel: "Digital advertising and sponsored corporate communication",
      logo: "newspaper-logos/ga/gabon-actu.svg",
      logoExplainer:
        "Navy blue and orange badge with bold text 'GABONACTU.COM', representing rapid breaking digital news.",
      sources: ["https://gabonactu.com"],
    },
    {
      id: "ga-gabon-medias-time",
      countryCode: "GA",
      name: "Gabon Media Time",
      founded: 2016,
      frequency: "Continuous digital multimedia service",
      format: "Digital multimedia portal & podcasts",
      language: "French",
      headquarters: "Libreville",
      owner: {
        name: "GMT Media Group (Harold Leckat)",
        type: "Independent commercial media",
      },
      editorialStance: "Modern multimedia news platform; investigative reporting, economic analysis, youth entrepreneurship, and cultural lifestyle",
      readership: {
        metric: "Rapidly grown to over 800,000 monthly digital visits with high engagement on mobile and social channels",
        source: "GMT Audience Review 2024",
      },
      revenueModel: "Digital programmatic advertising and brand content production",
      logo: "newspaper-logos/ga/gabon-medias-time.svg",
      logoExplainer:
        "Clean white background with elegant black and gold lettering 'GABON MEDIA TIME', symbolising contemporary media innovation.",
      sources: ["https://gabonmediatime.com"],
    },
  ],

  // Gambia
  GM: [
    {
      id: "gm-the-point",
      countryCode: "GM",
      name: "The Point",
      founded: 1991,
      frequency: "Daily newspaper (Monday–Friday)",
      format: "Tabloid publication & digital portal",
      language: "English",
      headquarters: "Fajara, Kanifing / Banjul",
      owner: {
        name: "The Point Newspaper Ltd (Pap Saine)",
        type: "Independent commercial media",
      },
      editorialStance: "Gambia's internationally acclaimed independent newspaper co-founded by Deyda Hydara; courageous press freedom pioneer, anti-corruption investigation, and democratic transition reporting",
      readership: {
        metric: "Winner of the IPI Free Media Pioneer Award; leading independent daily newspaper in the Gambia",
        source: "The Point Newspaper Review 2023",
      },
      revenueModel: "Print newsstand sales, legal notices, and commercial display advertising",
      logo: "newspaper-logos/gm/the-point.svg",
      logoExplainer:
        "Bold black and red serif masthead 'THE POINT' on white canvas, symbolising decades of brave journalistic integrity in West Africa.",
      sources: ["https://thepoint.gm", "https://en.wikipedia.org/wiki/The_Point_(Gambia)"],
    },
    {
      id: "gm-foroyaa",
      countryCode: "GM",
      name: "Foroyaa",
      nativeName: "Foroyaa",
      englishTranslation: "Freedom / Emancipation",
      founded: 1987,
      frequency: "Daily newspaper",
      format: "Tabloid publication & digital portal",
      language: "English",
      headquarters: "Serrekunda",
      owner: {
        name: "Foroyaa Publishing Co. (Halifa Sallah & Sam Sarr)",
        type: "Independent commercial media",
      },
      editorialStance: "Historic socio-political daily newspaper; in-depth constitutional law, agricultural reform, human rights monitoring, and Truth, Reconciliation and Reparations Commission (TRRC) documentation",
      readership: {
        metric: "Highly respected analytical publication widely read across legal, academic, and parliamentary communities",
        source: "Foroyaa Media Profile 2023",
      },
      revenueModel: "Print sales, subscriptions, and civic society notices",
      logo: "newspaper-logos/gm/foroyaa.svg",
      logoExplainer:
        "Red and green title banner with bold uppercase typography 'FOROYAA', representing thirty-seven years of civic freedom struggle.",
      sources: ["https://foroyaa.net", "https://en.wikipedia.org/wiki/Foroyaa"],
    },
    {
      id: "gm-kerr-fatou",
      countryCode: "GM",
      name: "Kerr Fatou",
      englishTranslation: "Fatou's Home",
      founded: 2016,
      frequency: "Continuous digital news & live talk show",
      format: "Digital multimedia portal & Web TV",
      language: "English, Wolof, Mandinka",
      headquarters: "Kanifing",
      owner: {
        name: "Kerr Fatou Media (Fatou Touray)",
        type: "Independent commercial media",
      },
      editorialStance: "Leading digital multimedia news and talk-show platform; national political debates, investigative human interest stories, women's empowerment, and electoral analysis",
      readership: {
        metric: "Over 1.5 million monthly digital interactions across Facebook, YouTube, and kerrfatou.com; most watched digital political show in Gambia",
        source: "Kerr Fatou Media Analytics 2024",
      },
      revenueModel: "Digital video monetization, corporate sponsorships, and diaspora advertising",
      logo: "newspaper-logos/gm/kerr-fatou.svg",
      logoExplainer:
        "Vibrant pink and dark purple emblem featuring stylized typography 'KERR FATOU', symbolising women-led multimedia innovation.",
      sources: ["https://www.kerrfatou.com"],
    },
    {
      id: "gm-the-chronicle-gambia",
      countryCode: "GM",
      name: "The Chronicle",
      officialName: "The Gambia Chronicle",
      founded: 2019,
      frequency: "Continuous digital news service",
      format: "Digital-only news portal & podcasts",
      language: "English",
      headquarters: "Banjul",
      owner: {
        name: "The Chronicle Media Co.",
        type: "Independent commercial media",
      },
      editorialStance: "Youth-led investigative digital outlet; investigative scoops, public expenditure tracking, environmental journalism, and migration reporting",
      readership: {
        metric: "Over 450,000 monthly digital readers among youth, students, and international development analysts",
        source: "The Chronicle Audience Review 2024",
      },
      revenueModel: "Digital banner advertising and philanthropic investigative grants",
      logo: "newspaper-logos/gm/the-chronicle-gambia.svg",
      logoExplainer:
        "Dark navy banner with crisp white serif typography 'THE CHRONICLE', reflecting analytical investigative journalism.",
      sources: ["https://www.chronicle.gm"],
    },
    {
      id: "gm-daily-observer-gambia",
      countryCode: "GM",
      name: "Daily Observer",
      founded: 1992,
      frequency: "Daily newspaper (historic national daily)",
      format: "Broadsheet & digital archive",
      language: "English",
      headquarters: "Bakau / Banjul",
      owner: {
        name: "Observer Company Ltd (Kenneth Best founded)",
        type: "Independent commercial media",
      },
      editorialStance: "Historically Gambia's first and largest daily broadsheet newspaper; chronicled national politics, sporting events, and cultural heritage",
      readership: {
        metric: "Historically the highest circulation print daily in the Gambia throughout the 1990s and 2000s",
        source: "Gambia Press Union Historical Archive 2023",
      },
      revenueModel: "Print sales and historical archives licensing",
      logo: "newspaper-logos/gm/daily-observer-gambia.svg",
      logoExplainer:
        "Classic serif masthead 'DAILY OBSERVER' in green and black, symbolising the foundation of daily print journalism in the Gambia.",
      sources: ["https://en.wikipedia.org/wiki/Daily_Observer_(The_Gambia)"],
    },
  ],

  // Georgia
  GE: [
    {
      id: "ge-interpressnews",
      countryCode: "GE",
      name: "Interpressnews",
      officialName: "IPN",
      nativeName: "ინტერპრესნიუსი",
      englishTranslation: "Interpressnews",
      founded: 2001,
      frequency: "Continuous 24/7 national newswire",
      format: "National news agency wire & online portal",
      language: "Georgian, English, Russian",
      headquarters: "Tbilisi",
      owner: {
        name: "Palitra Media Holding",
        type: "Independent commercial media",
      },
      editorialStance: "Georgia's primary independent news agency; real-time breaking news wire supplying parliamentary proceedings, judicial trials, regional South Caucasus news, and geopolitics",
      readership: {
        metric: "Over 4.5 million monthly digital visits; primary wire source for all Georgian television networks, radio stations, and print media",
        source: "Palitra Media Audience Report 2024",
      },
      revenueModel: "Newswire subscription syndication, digital display advertising, and SMS breaking news alerts",
      logo: "newspaper-logos/ge/interpressnews.svg",
      logoExplainer:
        "Red and blue emblem featuring stylized globe and bold typography 'IPN Interpressnews', the benchmark wire agency of Georgia.",
      sources: ["https://www.interpressnews.ge", "https://en.wikipedia.org/wiki/Interpressnews"],
    },
    {
      id: "ge-civil-ge",
      countryCode: "GE",
      name: "Civil.ge",
      officialName: "Civil Georgia",
      founded: 2001,
      frequency: "Continuous digital news service",
      format: "Digital investigative portal & multilingual daily",
      language: "Georgian, English, Russian",
      headquarters: "Tbilisi",
      owner: {
        name: "United Nations Association of Georgia (UNAG)",
        type: "Non-profit independent foundation",
      },
      editorialStance: "Non-partisan daily news portal dedicated to democratic consolidation; authoritative tracking of electoral processes, occupied territories (Abkhazia/South Ossetia), and European integration",
      readership: {
        metric: "Primary news source on Georgia for foreign embassies, international organizations, Western think tanks, and scholars",
        source: "Civil.ge / UNAG Annual Review 2023",
      },
      revenueModel: "International democratic governance grants and philanthropic donations",
      logo: "newspaper-logos/ge/civil-ge.svg",
      logoExplainer:
        "Clean white background with modern blue typography 'Civil.ge', representing objective, non-partisan analytical journalism.",
      sources: ["https://civil.ge", "https://en.wikipedia.org/wiki/Civil_Georgia"],
    },
    {
      id: "ge-sakartvelos-respublika",
      countryCode: "GE",
      name: "Sakartvelos Respublika",
      nativeName: "საქართველოს რესპუბლიკა",
      englishTranslation: "Republic of Georgia",
      founded: 1918,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Georgian",
      headquarters: "Tbilisi",
      owner: {
        name: "Sakartvelos Respublika Publishing",
        type: "Independent commercial media",
      },
      editorialStance: "Historic newspaper founded during the Democratic Republic of Georgia in 1918; constitutional history, academic essays, national culture, and public governance",
      readership: {
        metric: "Historic paper of record read widely by historians, civil servants, and the cultural intelligentsia",
        source: "Georgian National Parliamentary Library 2023",
      },
      revenueModel: "Print subscriptions, retail sales, and official announcements",
      logo: "newspaper-logos/ge/sakartvelos-respublika.svg",
      logoExplainer:
        "Historic Georgian Asomtavruli and Mkhedruli script calligraphy 'საქართველოს რესპუბლიკა' with the national coat of arms motif.",
      sources: ["https://sakresh.ge", "https://ka.wikipedia.org/wiki/%E1%83%A1%E1%83%90%E1%83%A5%E1%83%90%E1%83%A0%E1%83%97%E1%83%95%E1%83%94%E1%83%9A%E1%83%9D%E1%83%A1_%E1%83%A0%E1%83%94%E1%83%A1%E1%83%A0%E1%83%A3%E1%83%91%E1%83%9A%E1%83%98%E1%83%99%E1%83%90_(%E1%83%92%E1%83%90%E1%83%96%E1%83%94%E1%83%97%E1%83%98)"],
    },
    {
      id: "ge-kviris-palitra",
      countryCode: "GE",
      name: "Kviris Palitra",
      nativeName: "კვირის პალიტრა",
      englishTranslation: "Weekly Palette",
      founded: 1995,
      frequency: "Weekly newspaper (Monday)",
      format: "Broadsheet & digital network",
      language: "Georgian",
      headquarters: "Tbilisi",
      owner: {
        name: "Palitra Media Holding",
        type: "Independent commercial media",
      },
      editorialStance: "Georgia's largest circulation weekly newspaper; comprehensive political interviews, investigative exposés, military commentary, and cultural essays",
      readership: {
        metric: "Highest print circulation weekly in Georgia (~40,000 weekly copies) and 2.5 million monthly digital readers on kvirispalitra.ge",
        source: "Palitra Media Holding 2024",
      },
      revenueModel: "Print sales, digital subscriptions, and display advertising",
      logo: "newspaper-logos/ge/kviris-palitra.svg",
      logoExplainer:
        "Palette of colors and bold Georgian font 'კვირის პალიტრა', symbolising a diverse spectrum of national perspectives.",
      sources: ["https://kvirispalitra.ge", "https://ka.wikipedia.org/wiki/%E1%83%99%E1%83%95%E1%83%98%E1%83%A0%E1%83%98%E1%83%A1_%E1%83%A0%E1%83%90%E1%83%9A%E1%83%98%E1%83%A2%E1%83%A0%E1%83%90"],
    },
    {
      id: "ge-rezo-nansi",
      countryCode: "GE",
      name: "Rezonansi",
      nativeName: "რეზონანსი",
      englishTranslation: "Resonance",
      founded: 1990,
      frequency: "Daily newspaper (Monday–Friday)",
      format: "Tabloid & digital portal",
      language: "Georgian",
      headquarters: "Tbilisi",
      owner: {
        name: "Rezonansi Media (Malkhaz Rambashidze)",
        type: "Independent commercial media",
      },
      editorialStance: "Independent daily newspaper founded during the national liberation movement; political analytics, economic reform, and investigative reporting",
      readership: {
        metric: "Longstanding daily read by political analysts, civil society leaders, and university students across Tbilisi",
        source: "Rezonansi Media Archive 2023",
      },
      revenueModel: "Print retail sales and digital display advertising",
      logo: "newspaper-logos/ge/rezo-nansi.svg",
      logoExplainer:
        "Red and black title banner with bold Georgian lettering 'რეზონანსი', representing public resonance and civic debate.",
      sources: ["https://resonancedaily.com"],
    },
  ],

  // Germany
  DE: [
    {
      id: "de-frankfurter-allgemeine-zeitung",
      countryCode: "DE",
      name: "Frankfurter Allgemeine Zeitung",
      officialName: "FAZ",
      nativeName: "Frankfurter Allgemeine Zeitung",
      englishTranslation: "Frankfurt General Newspaper",
      founded: 1949,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Broadsheet & digital network",
      language: "German",
      headquarters: "Hellerhofstraße, Frankfurt am Main, Hesse",
      owner: {
        name: "FAZIT-Stiftung (Non-profit Foundation)",
        type: "Independent trust / foundation",
      },
      editorialStance: "Germany's preeminent conservative-liberal newspaper of record; owned by an independent foundation to ensure total editorial freedom; internationally renowned for deep political analysis, economic theory (ordoliberalism), cultural Feuilleton, and global foreign correspondence",
      readership: {
        metric: "Over 200,000 daily print circulation and more than 300,000 paid digital subscribers (F+ / FAZ.NET) reaching 12+ million monthly unique users",
        source: "IVW (Informationsgemeinschaft zur Feststellung der Verbreitung von Werbeträgern) 2024",
      },
      revenueModel: "Digital paywall subscriptions, print circulation, and corporate display advertising",
      logo: "newspaper-logos/de/frankfurter-allgemeine-zeitung.svg",
      logoExplainer:
        "Historic Fraktur blackletter masthead 'Frankfurter Allgemeine' on white canvas, the definitive typographic symbol of German quality journalism.",
      sources: ["https://www.faz.net", "https://en.wikipedia.org/wiki/Frankfurter_Allgemeine_Zeitung"],
    },
    {
      id: "de-sueddeutsche-zeitung",
      countryCode: "DE",
      name: "Süddeutsche Zeitung",
      officialName: "SZ",
      nativeName: "Süddeutsche Zeitung",
      englishTranslation: "South German Newspaper",
      founded: 1945,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Broadsheet & digital network",
      language: "German",
      headquarters: "Hultschiner Straße, Munich, Bavaria",
      owner: {
        name: "Südwestdeutsche Medienholding (SWMH)",
        type: "Independent commercial media",
      },
      editorialStance: "Germany's largest quality subscription daily; center-left progressive liberal stance; world-famous investigative journalism department that broke the Panama Papers and Paradise Papers",
      readership: {
        metric: "Over 310,000 paid circulation including 260,000+ digital subscribers (SZ Plus) and 14 million monthly digital readers on sz.de",
        source: "IVW Deutschland Q1 2024",
      },
      revenueModel: "Digital paywall subscriptions, print sales, and commercial display advertising",
      logo: "newspaper-logos/de/süddeutsche-zeitung.svg",
      logoExplainer:
        "Gothic serif masthead 'Süddeutsche Zeitung' featuring the historic Munich cathedral (Frauenturm) silhouette, symbolising investigative authority.",
      sources: ["https://www.sueddeutsche.de", "https://en.wikipedia.org/wiki/S%C3%BCddeutsche_Zeitung"],
    },
    {
      id: "de-die-welt",
      countryCode: "DE",
      name: "Die Welt",
      nativeName: "Die Welt",
      englishTranslation: "The World",
      founded: 1946,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital network (WELT)",
      language: "German",
      headquarters: "Axel-Springer-Straße, Berlin",
      owner: {
        name: "Axel Springer SE",
        type: "Independent commercial media",
      },
      editorialStance: "National conservative broadsheet founded in Hamburg by British occupation authorities; free-market advocacy, transatlantic partnership, defense policy, and 24-hour TV news integration (WELT TV)",
      readership: {
        metric: "Over 200,000 digital subscribers (WELTplus) and top-tier digital news destination with 18 million monthly unique visitors",
        source: "Axel Springer Financial Results 2024",
      },
      revenueModel: "Digital subscriptions, television broadcasting revenue, and programmatic advertising",
      logo: "newspaper-logos/de/die-welt.svg",
      logoExplainer:
        "Deep blue rectangular banner with bold white capital typography 'WELT', representing transatlantic conservatism and 24-hour news.",
      sources: ["https://www.welt.de", "https://en.wikipedia.org/wiki/Die_Welt"],
    },
    {
      id: "de-handelsblatt",
      countryCode: "DE",
      name: "Handelsblatt",
      nativeName: "Handelsblatt",
      englishTranslation: "Commerce Sheet",
      founded: 1946,
      frequency: "Daily business newspaper (Monday–Friday)",
      format: "Tabloid format broadsheet & financial network",
      language: "German",
      headquarters: "Toulouser Allee, Düsseldorf, North Rhine-Westphalia",
      owner: {
        name: "Handelsblatt Media Group (Dieter von Holtzbrinck Medien)",
        type: "Independent commercial media",
      },
      editorialStance: "Germany's preeminent financial and economic daily newspaper; DAX stock exchange analysis, German Mittelstand industrial engineering, automotive transition, and fiscal discipline",
      readership: {
        metric: "Over 140,000 daily paid circulation including 100,000+ digital subscribers; primary business paper for the German industrial executive suite",
        source: "Handelsblatt Media Group Review 2024",
      },
      revenueModel: "Corporate subscriptions, specialized economic research, and B2B financial advertising",
      logo: "newspaper-logos/de/handelsblatt.svg",
      logoExplainer:
        "Signature orange and black title banner with bold uppercase typography 'Handelsblatt', iconic across German corporate boardrooms.",
      sources: ["https://www.handelsblatt.com", "https://en.wikipedia.org/wiki/Handelsblatt"],
    },
    {
      id: "de-bild",
      countryCode: "DE",
      name: "Bild",
      officialName: "Bild-Zeitung",
      nativeName: "Bild",
      englishTranslation: "Picture",
      founded: 1952,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Tabloid publication & digital network",
      language: "German",
      headquarters: "Berlin",
      owner: {
        name: "Axel Springer SE",
        type: "Independent commercial media",
      },
      editorialStance: "Europe's largest circulation daily newspaper; sensationalist populist reporting, celebrity exposés, consumer campaigns, politics, and Bundesliga sports",
      readership: {
        metric: "Over 1.1 million daily print copies and more than 680,000 paid digital subscribers on BILDplus; highest reach daily news brand in Europe",
        source: "IVW Deutschland & Axel Springer 2024",
      },
      revenueModel: "Street print sales, BILDplus digital paywall, and high-volume commercial advertising",
      logo: "newspaper-logos/de/bild.svg",
      logoExplainer:
        "Iconic red square emblem with white bold uppercase lettering 'BILD', the most recognizable tabloid logo across Europe.",
      sources: ["https://www.bild.de", "https://en.wikipedia.org/wiki/Bild"],
    },
  ],

  // Ghana
  GH: [
    {
      id: "gh-daily-graphic",
      countryCode: "GH",
      name: "Daily Graphic",
      founded: 1950,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Official public broadsheet & digital network",
      language: "English",
      headquarters: "Accra",
      owner: {
        name: "Graphic Communications Group Limited (GCGL)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Ghana's national newspaper of record; government policy announcements, parliamentary debates, cocoa and gold mining economics, and educational notices",
      readership: {
        metric: "Largest print circulation newspaper in Ghana (~100,000 daily print copies) and leading digital portal Graphic Online with 4M+ monthly visits",
        source: "Graphic Communications Group Annual Report 2023",
      },
      revenueModel: "Commercial print circulation, state legal advertising, and digital display revenue",
      logo: "newspaper-logos/gh/daily-graphic.svg",
      logoExplainer:
        "Red and blue title banner with bold serif lettering 'Daily Graphic', symbolising over seventy years of authoritative Ghanaian journalism.",
      sources: ["https://www.graphic.com.gh", "https://en.wikipedia.org/wiki/Daily_Graphic_(Ghana)"],
    },
    {
      id: "gh-the-ghanaian-times",
      countryCode: "GH",
      name: "The Ghanaian Times",
      founded: 1958,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Official state broadsheet & digital portal",
      language: "English",
      headquarters: "Accra",
      owner: {
        name: "New Times Corporation (NTC)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Founded by Ghana's first President Kwame Nkrumah; national development reporting, pan-African diplomacy, civil service affairs, and public healthcare",
      readership: {
        metric: "Second largest state-owned newspaper with universal distribution across all 16 regions of Ghana",
        source: "New Times Corporation Ghana 2023",
      },
      revenueModel: "State budget subsidies, print sales, and official government advertising",
      logo: "newspaper-logos/gh/the-ghanaian-times.svg",
      logoExplainer:
        "Classic black serif masthead 'THE GHANAIAN TIMES' on white ground, representing foundational post-independence national press.",
      sources: ["https://ghanaiantimes.com.gh", "https://en.wikipedia.org/wiki/The_Ghanaian_Times"],
    },
    {
      id: "gh-myjoyonline",
      countryCode: "GH",
      name: "MyJoyOnline",
      founded: 2003,
      frequency: "Continuous 24/7 digital news service",
      format: "Digital multimedia portal & radio/TV network",
      language: "English",
      headquarters: "Kokomlemle, Accra",
      owner: {
        name: "The Multimedia Group (Kwasi Twum)",
        type: "Independent commercial media",
      },
      editorialStance: "Ghana's premier independent digital news network; investigative journalism (Manasseh Azure Awuni projects), Joy FM radio synergy, and live election coverage",
      readership: {
        metric: "Over 8 million monthly unique digital visitors; highest digital news reach in Ghana",
        source: "Similarweb & Multimedia Group Ghana 2024",
      },
      revenueModel: "Digital programmatic advertising, cross-broadcast sponsorships, and video production",
      logo: "newspaper-logos/gh/myjoyonline.svg",
      logoExplainer:
        "Vibrant yellow and black emblem 'MyJoyOnline.com', representing independent multimedia innovation in West Africa.",
      sources: ["https://www.myjoyonline.com"],
    },
    {
      id: "gh-citinewsroom",
      countryCode: "GH",
      name: "Citi Newsroom",
      founded: 2018,
      frequency: "Continuous 24/7 digital news service",
      format: "Digital news portal & broadcast network",
      language: "English",
      headquarters: "Adabraka, Accra",
      owner: {
        name: "Omni Media Limited / Citi TV & Citi FM (Samuel Attah-Mensah)",
        type: "Independent commercial media",
      },
      editorialStance: "Urban quality news network; consumer rights advocacy, anti-illegal mining (Galamsey) campaigns, fiscal policy oversight, and business news",
      readership: {
        metric: "Over 5 million monthly digital readers; widely recognized for urban professional engagement and broadcast excellence",
        source: "Omni Media Audience Review 2024",
      },
      revenueModel: "Digital display advertising, broadcast commercial revenue, and event sponsorships",
      logo: "newspaper-logos/gh/citinewsroom.svg",
      logoExplainer:
        "Red and blue modern typography 'citinewsroom', symbolising progressive urban broadcast and digital journalism.",
      sources: ["https://citinewsroom.com"],
    },
    {
      id: "gh-daily-guide",
      countryCode: "GH",
      name: "Daily Guide",
      founded: 1984,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Tabloid publication & digital portal",
      language: "English",
      headquarters: "Nima, Accra",
      owner: {
        name: "Western Publications Limited (Freddie Blay family)",
        type: "Independent commercial media",
      },
      editorialStance: "Ghana's largest circulation private newspaper; center-right political stance; aggressive political scoops, crime investigations, and popular culture",
      readership: {
        metric: "Highest print circulation among private newspapers in Ghana (~50,000 daily copies) and popular dailyguideonline.com portal",
        source: "Western Publications Media Kit 2023",
      },
      revenueModel: "Print newsstand sales and private corporate advertising",
      logo: "newspaper-logos/gh/daily-guide.svg",
      logoExplainer:
        "Red banner with bold white serif font 'DAILY GUIDE', iconic across Ghanaian newsstands for over four decades.",
      sources: ["https://dailyguidenetwork.com", "https://en.wikipedia.org/wiki/Daily_Guide"],
    },
  ],

  // Greece
  GR: [
    {
      id: "gr-kathimerini",
      countryCode: "GR",
      name: "Kathimerini",
      nativeName: "Η Καθημερινή",
      englishTranslation: "The Daily",
      founded: 1919,
      frequency: "Daily newspaper (Tuesday–Sunday)",
      format: "Broadsheet & international digital portal",
      language: "Greek, English (Kathimerini English Edition / NYT)",
      headquarters: "Neo Faliro, Athens",
      owner: {
        name: "Kathimerini Publishing (Alafouzos family)",
        type: "Independent commercial media",
      },
      editorialStance: "Greece's historic center-right newspaper of record; distinguished for serious political commentary, European Union policy, Aegean maritime affairs, and arts",
      readership: {
        metric: "Largest subscription broadsheet in Greece and leading digital network with 6+ million monthly unique visitors on kathimerini.gr",
        source: "Kathimerini Publishing Annual Review 2023",
      },
      revenueModel: "Digital paywall subscriptions, print sales, and corporate advertising",
      logo: "newspaper-logos/gr/kathimerini.svg",
      logoExplainer:
        "Classical black Greek serif typography 'Η ΚΑΘΗΜΕΡΙΝΗ' on white canvas, the benchmark masthead of Greek quality journalism.",
      sources: ["https://www.kathimerini.gr", "https://en.wikipedia.org/wiki/Kathimerini"],
    },
    {
      id: "gr-ta-nea",
      countryCode: "GR",
      name: "Ta Nea",
      nativeName: "Τα Νέα",
      englishTranslation: "The News",
      founded: 1931,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Berliner format & digital portal",
      language: "Greek",
      headquarters: "Kallithea, Athens",
      owner: {
        name: "Alter Ego Media (Vangelis Marinakis)",
        type: "Independent commercial media",
      },
      editorialStance: "Historically Greece's highest circulated daily newspaper; center-left social-liberal editorial stance; national politics, parliamentary debates, and social welfare",
      readership: {
        metric: "Consistently among the top two daily print newspapers in Greece with 4.5 million monthly digital readers on tanea.gr",
        source: "Alter Ego Media Audience Report 2024",
      },
      revenueModel: "Print newsstand sales, digital subscriptions, and commercial advertising",
      logo: "newspaper-logos/gr/ta-nea.svg",
      logoExplainer:
        "Red and blue emblem with bold white Greek lettering 'ΤΑ ΝΕΑ', iconic across Greek kiosks for almost a century.",
      sources: ["https://www.tanea.gr", "https://en.wikipedia.org/wiki/Ta_Nea"],
    },
    {
      id: "gr-to-vima",
      countryCode: "GR",
      name: "To Vima",
      nativeName: "Το Βήμα",
      englishTranslation: "The Tribune / Rostrum",
      founded: 1922,
      frequency: "Weekly newspaper (Sunday) & continuous digital portal",
      format: "Broadsheet & digital portal",
      language: "Greek",
      headquarters: "Athens",
      owner: {
        name: "Alter Ego Media",
        type: "Independent commercial media",
      },
      editorialStance: "Historic intellectual Sunday newspaper; in-depth political investigations, foreign policy diplomacy, economic reforms, and literary reviews",
      readership: {
        metric: "Dominant Sunday print circulation in Greece and influential digital readership on tovima.gr",
        source: "Alter Ego Media Review 2023",
      },
      revenueModel: "Sunday print sales, premium book/magazine bundle sales, and digital advertising",
      logo: "newspaper-logos/gr/to-vima.svg",
      logoExplainer:
        "Blue banner with classical white Greek serif font 'ΤΟ ΒΗΜΑ', symbolising over a century of political authority.",
      sources: ["https://www.tovima.gr", "https://en.wikipedia.org/wiki/To_Vima"],
    },
    {
      id: "gr-naftemporiki",
      countryCode: "GR",
      name: "Naftemporiki",
      nativeName: "Η Ναυτεμπορική",
      englishTranslation: "The Shipping and Commercial",
      founded: 1924,
      frequency: "Daily financial newspaper (Monday–Friday)",
      format: "Salmon broadsheet & digital financial portal",
      language: "Greek",
      headquarters: "Athens",
      owner: {
        name: "Aegean Media (Dimitris Melissanidis)",
        type: "Independent commercial media",
      },
      editorialStance: "Greece's premier shipping, financial, and economic daily; Athens Exchange, Greek merchant shipping fleet (world's largest commercial fleet), tourism economics, and European fiscal policy",
      readership: {
        metric: "Over 100 years of financial reporting; mandatory daily reading for Greek shipowners, banking executives, and industrial leaders",
        source: "Naftemporiki Centennial Review 2024",
      },
      revenueModel: "Corporate subscriptions and financial market advertising",
      logo: "newspaper-logos/gr/naftemporiki.svg",
      logoExplainer:
        "Navy blue banner with classical white Greek typography 'Η ΝΑΥΤΕΜΠΟΡΙΚΗ', embodying maritime shipping and commerce excellence.",
      sources: ["https://www.naftemporiki.gr", "https://en.wikipedia.org/wiki/Naftemporiki"],
    },
    {
      id: "gr-efimerida-ton-syntakton",
      countryCode: "GR",
      name: "Efimerida ton Syntakton",
      officialName: "EFSYN",
      nativeName: "Η Εφημερίδα των Συντακτών",
      englishTranslation: "The Journalists' Newspaper",
      founded: 2012,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Tabloid publication & digital portal",
      language: "Greek",
      headquarters: "Kolokotroni Street, Athens",
      owner: {
        name: "Cooperative of Journalists and Employees (Worker Cooperative)",
        type: "Non-profit independent trust",
      },
      editorialStance: "Unique cooperative daily owned entirely by its journalists; left-wing progressive stance championing human rights, refugee solidarity, labor rights, and anti-austerity analysis",
      readership: {
        metric: "Over 2 million monthly digital visitors on efsyn.gr and dedicated nationwide print subscriber base",
        source: "EFSYN Cooperative Annual Report 2023",
      },
      revenueModel: "Reader cooperative subscriptions, print sales, and community advertising",
      logo: "newspaper-logos/gr/efimerida-ton-syntakton.svg",
      logoExplainer:
        "Red and black badge with stylized Greek typography 'ΕΦ.ΣΥΝ.', representing cooperative worker-owned journalism in Greece.",
      sources: ["https://www.efsyn.gr", "https://en.wikipedia.org/wiki/Efimerida_ton_Syntakton"],
    },
  ],

  // Grenada
  GD: [
    {
      id: "gd-now-grenada",
      countryCode: "GD",
      name: "Now Grenada",
      founded: 2013,
      frequency: "Continuous 24/7 digital news service",
      format: "Digital-only news portal",
      language: "English",
      headquarters: "St. George's",
      owner: {
        name: "Now Grenada Media",
        type: "Independent commercial media",
      },
      editorialStance: "Grenada's leading digital breaking news portal; parliamentary affairs, spice island agriculture (nutmeg/cocoa), tourism developments, and community reporting",
      readership: {
        metric: "Over 650,000 monthly digital visits; primary online news source for Grenada, Carriacou, and Petite Martinique",
        source: "Now Grenada Analytics 2024",
      },
      revenueModel: "Digital display advertising and local corporate sponsorships",
      logo: "newspaper-logos/gd/now-grenada.svg",
      logoExplainer:
        "Green, red, and yellow badge featuring bold typography 'NOW Grenada', reflecting the national colors of the Spice Isle.",
      sources: ["https://nowgrenada.com"],
    },
    {
      id: "gd-the-barnacle",
      countryCode: "GD",
      name: "The Barnacle",
      founded: 1990,
      frequency: "Monthly newspaper & daily portal",
      format: "Tabloid publication & digital portal",
      language: "English",
      headquarters: "St. George's",
      owner: {
        name: "Barnacle Publishing Ltd",
        type: "Independent commercial media",
      },
      editorialStance: "Independent print monthly paper; in-depth cultural analysis, community developments, educational features, and environmental news",
      readership: {
        metric: "Widely read community publication across parish schools, local councils, and businesses in St. George's",
        source: "The Barnacle Media Review 2023",
      },
      revenueModel: "Print advertising and local business listings",
      logo: "newspaper-logos/gd/the-barnacle.svg",
      logoExplainer:
        "Navy blue banner with classical white serif masthead 'The Barnacle', representing over thirty years of community journalism.",
      sources: ["https://thebarnaclenews.com"],
    },
    {
      id: "gd-grenada-informer",
      countryCode: "GD",
      name: "The Grenada Informer",
      founded: 1985,
      frequency: "Weekly newspaper (Friday)",
      format: "Tabloid publication & digital portal",
      language: "English",
      headquarters: "St. George's",
      owner: {
        name: "Informer Publishing Co.",
        type: "Independent commercial media",
      },
      editorialStance: "Historic independent weekly newspaper; investigative scoops, court reporting, political commentary, and sports (cricket)",
      readership: {
        metric: "One of the longest-running print weekly papers in Grenada with widespread newsstand circulation",
        source: "Grenada Informer Publishing 2023",
      },
      revenueModel: "Print sales, legal notices, and commercial advertising",
      logo: "newspaper-logos/gd/grenada-informer.svg",
      logoExplainer:
        "Bold red and yellow title banner 'THE GRENADA INFORMER', iconic across island kiosks.",
      sources: ["https://thegrenadainformer.com"],
    },
    {
      id: "gd-the-grenada-guardian",
      countryCode: "GD",
      name: "The Grenada Guardian",
      founded: 1953,
      frequency: "Weekly newspaper",
      format: "Tabloid publication",
      language: "English",
      headquarters: "St. George's",
      owner: {
        name: "Guardian Publishing Ltd",
        type: "Independent commercial media",
      },
      editorialStance: "Historic political weekly founded by Eric Gairy; agricultural workers' rights, constitutional debates, and historical commentary",
      readership: {
        metric: "Historic paper read by political historians and community leaders throughout Grenada",
        source: "Grenada National Archives 2023",
      },
      revenueModel: "Print sales and community notices",
      logo: "newspaper-logos/gd/the-grenada-guardian.svg",
      logoExplainer:
        "Classic black serif title 'THE GRENADA GUARDIAN' on white ground, symbolising foundational post-war political press history.",
      sources: ["https://en.wikipedia.org/wiki/Eric_Gairy"],
    },
    {
      id: "gd-pure-grenada-news",
      countryCode: "GD",
      name: "Pure Grenada News",
      founded: 2018,
      frequency: "Continuous digital news service",
      format: "Digital multimedia portal",
      language: "English",
      headquarters: "St. George's",
      owner: {
        name: "Spice Isle Digital Media",
        type: "Independent commercial media",
      },
      editorialStance: "Digital news and tourism portal; eco-tourism promotions, marine conservation, cultural festivals (Spicemas), and diaspora affairs",
      readership: {
        metric: "Popular digital news channel engaging the Grenadian diaspora in the US, Canada, and the UK",
        source: "Pure Grenada Digital Analytics 2024",
      },
      revenueModel: "Digital display advertising and international tourism partnerships",
      logo: "newspaper-logos/gd/pure-grenada-news.svg",
      logoExplainer:
        "Golden-yellow and green emblem with nutmeg spice motif and clean typography 'Pure Grenada News', evoking the Spice Isle.",
      sources: ["https://www.puregrenada.com"],
    },
  ],
`;

const closingIndex = content.lastIndexOf("};");
if (closingIndex === -1) {
  throw new Error("Could not find closing '};' in " + dataFile);
}

const updatedContent = content.slice(0, closingIndex) + block7Entries + "};\n";
fs.writeFileSync(dataFile, updatedContent, "utf8");
console.log("✓ Successfully added Block 7 entries to src/data/nationalNewsAgencies.ts");
