import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const dataFile = path.join(root, "src/data/nationalNewsAgencies.ts");

let content = fs.readFileSync(dataFile, "utf8");

const block6Entries = `
  // Dominica
  DM: [
    {
      id: "dm-the-chronicle",
      countryCode: "DM",
      name: "The Chronicle",
      founded: 1909,
      frequency: "Weekly newspaper (Friday)",
      format: "Tabloid publication & digital portal",
      language: "English",
      headquarters: "Roseau",
      owner: {
        name: "Chronicle Newspaper Ltd",
        type: "Independent commercial media",
      },
      editorialStance: "Dominica's historic newspaper of record; comprehensive coverage of parliamentary debates, island agriculture, regional CARICOM news, and civic life",
      readership: {
        metric: "Over 110 years of continuous publishing; leading historic print newspaper in Dominica",
        source: "Dominica Chronicle Media Profile 2023",
      },
      revenueModel: "Print sales, legal notices, and commercial display advertising",
      logo: "newspaper-logos/dm/the-chronicle.svg",
      logoExplainer:
        "Classic black serif masthead 'The Chronicle' on white canvas, symbolising over a century of print journalism in Dominica.",
      sources: ["https://thechronicle.dm", "https://en.wikipedia.org/wiki/The_Chronicle_(Dominica)"],
    },
    {
      id: "dm-dominica-news-online",
      countryCode: "DM",
      name: "Dominica News Online",
      officialName: "Dominica News Online (DNO)",
      founded: 2007,
      frequency: "Continuous 24/7 digital news service",
      format: "Digital-only news portal",
      language: "English",
      headquarters: "Roseau",
      owner: {
        name: "Duravision Inc.",
        type: "Independent commercial media",
      },
      editorialStance: "Dominica's premier digital breaking news portal; high-tempo reporting, community updates, weather monitoring, and national politics",
      readership: {
        metric: "Over 800,000 monthly digital visits across Dominica and extensive diaspora readership in the UK and North America",
        source: "Dominica News Online Audience Report 2024",
      },
      revenueModel: "Digital banner advertising and diaspora community promotions",
      logo: "newspaper-logos/dm/dominica-news-online.svg",
      logoExplainer:
        "Cyan and navy banner with white lettering 'DOMINICA NEWS ONLINE', representing modern real-time island reporting.",
      sources: ["https://dominicanewsonline.com"],
    },
    {
      id: "dm-the-sun-dominica",
      countryCode: "DM",
      name: "The Sun",
      founded: 1999,
      frequency: "Weekly newspaper",
      format: "Tabloid publication",
      language: "English",
      headquarters: "Roseau",
      owner: {
        name: "Sun Printing & Publishing Ltd",
        type: "Independent commercial media",
      },
      editorialStance: "Independent investigative weekly; political commentary, environmental conservation, and social accountability",
      readership: {
        metric: "Widely read independent weekly print paper in Roseau and Portsmouth",
        source: "Sun Publishing Review 2023",
      },
      revenueModel: "Print sales and local business advertising",
      logo: "newspaper-logos/dm/the-sun-dominica.svg",
      logoExplainer:
        "Bright golden sunburst icon with bold black typography 'The Sun', symbolising vibrant truth and community journalism.",
      sources: ["https://sundominica.com"],
    },
    {
      id: "dm-dominica-vibes",
      countryCode: "DM",
      name: "Dominica Vibes News",
      founded: 2010,
      frequency: "Continuous digital news portal",
      format: "Digital multimedia portal",
      language: "English",
      headquarters: "Roseau",
      owner: {
        name: "Vibes Media Group",
        type: "Independent commercial media",
      },
      editorialStance: "Digital news and lifestyle portal; cultural events, World Creole Music Festival coverage, sports, and youth news",
      readership: {
        metric: "Popular digital platform engaging youth and cultural sectors in Dominica",
        source: "Dominica Vibes Audience Review 2023",
      },
      revenueModel: "Digital display ads and festival event promotions",
      logo: "newspaper-logos/dm/dominica-vibes.svg",
      logoExplainer:
        "Green and yellow banner with modern typography 'DOMINICA VIBES', reflecting the nature island's cultural vitality.",
      sources: ["https://www.dominicavibes.dm"],
    },
    {
      id: "dm-ebean-news",
      countryCode: "DM",
      name: "EmoNews",
      founded: 2018,
      frequency: "Continuous digital news & live streaming",
      format: "Digital video news & portal",
      language: "English",
      headquarters: "Roseau",
      owner: {
        name: "EmoNews Media Network",
        type: "Independent commercial media",
      },
      editorialStance: "Rapidly growing digital native news channel; live on-the-scene broadcasts, community interviews, and disaster response reporting",
      readership: {
        metric: "High social media engagement with over 150,000 active community followers across the Caribbean",
        source: "EmoNews Media Analytics 2024",
      },
      revenueModel: "Social media monetization, local sponsorships, and live stream advertising",
      logo: "newspaper-logos/dm/ebean-news.svg",
      logoExplainer:
        "Red and black badge with bold white lettering 'EMONEWS', representing dynamic mobile-first island reporting.",
      sources: ["https://emonewsdm.com"],
    },
  ],

  // Dominican Republic
  DO: [
    {
      id: "do-listin-diario",
      countryCode: "DO",
      name: "Listín Diario",
      englishTranslation: "Daily List",
      founded: 1889,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Spanish",
      headquarters: "Santo Domingo",
      owner: {
        name: "Grupo de Comunicaciones Corripio",
        type: "Independent commercial media",
      },
      editorialStance: "Dominican Republic's dean of national journalism and historic newspaper of record; national politics, economic policy, legal affairs, and arts",
      readership: {
        metric: "Over 8 million monthly unique digital visitors on listindiario.com and highest broadsheet print circulation in the nation",
        source: "Grupo Corripio Informe Anual 2023",
      },
      revenueModel: "Digital subscriptions, print circulation, and corporate display advertising",
      logo: "newspaper-logos/do/listín-diario.svg",
      logoExplainer:
        "Classic black gothic masthead 'Listín Diario' on white canvas, symbolising over 135 years of Dominican press heritage.",
      sources: ["https://listindiario.com", "https://en.wikipedia.org/wiki/List%C3%ADn_Diario"],
    },
    {
      id: "do-diario-libre",
      countryCode: "DO",
      name: "Diario Libre",
      englishTranslation: "Free Daily",
      founded: 2001,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Berliner free daily & premium digital portal",
      language: "Spanish",
      headquarters: "Santo Domingo",
      owner: {
        name: "Grupo Puntacana (Rainieri family)",
        type: "Independent commercial media",
      },
      editorialStance: "Pioneering free daily newspaper; modern design, investigative journalism, tourism economics, and transparent public governance",
      readership: {
        metric: "Largest daily print circulation in the Caribbean (~150,000 daily copies) and 9+ million monthly digital visitors",
        source: "Diario Libre Media Kit 2024",
      },
      revenueModel: "Commercial print display advertising and digital programmatic revenue",
      logo: "newspaper-logos/do/diario-libre.svg",
      logoExplainer:
        "Deep blue banner with clean white sans-serif typography 'Diario Libre', reflecting modern investigative and independent reporting.",
      sources: ["https://www.diariolibre.com", "https://en.wikipedia.org/wiki/Diario_Libre"],
    },
    {
      id: "do-hoy",
      countryCode: "DO",
      name: "Hoy",
      englishTranslation: "Today",
      founded: 1981,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Spanish",
      headquarters: "Santo Domingo",
      owner: {
        name: "Grupo de Comunicaciones Corripio",
        type: "Independent commercial media",
      },
      editorialStance: "Mainstream quality daily; national political analysis, investigative reports, economic development, and cultural essays",
      readership: {
        metric: "Widely circulated across institutional and commercial sectors with over 4.5 million monthly digital readers",
        source: "Periódico Hoy Memoria 2023",
      },
      revenueModel: "Print sales, official legal notices, and advertising",
      logo: "newspaper-logos/do/hoy.svg",
      logoExplainer:
        "Vibrant red title banner with bold white lettering 'HOY', representing immediate daily news and editorial vitality.",
      sources: ["https://hoy.com.do", "https://es.wikipedia.org/wiki/Hoy_(Rep%C3%BAblica_Dominicana)"],
    },
    {
      id: "do-el-caribe",
      countryCode: "DO",
      name: "El Caribe",
      englishTranslation: "The Caribbean",
      founded: 1948,
      frequency: "Daily newspaper",
      format: "Tabloid & digital portal",
      language: "Spanish",
      headquarters: "Santo Domingo",
      owner: {
        name: "Multimedios del Caribe",
        type: "Independent commercial media",
      },
      editorialStance: "Historic daily newspaper founded in 1948; political commentary, regional Caribbean affairs, sports (baseball), and judiciary reporting",
      readership: {
        metric: "Key national morning newspaper paired with CDN Canal 37 television network for cross-media reach",
        source: "Multimedios del Caribe 2023",
      },
      revenueModel: "Print circulation and multimedia broadcast-digital advertising",
      logo: "newspaper-logos/do/el-caribe.svg",
      logoExplainer:
        "Navy blue background with bold serif typography 'elCaribe', symbolising Caribbean identity and journalistic integrity.",
      sources: ["https://www.elcaribe.com.do", "https://en.wikipedia.org/wiki/El_Caribe_(newspaper)"],
    },
    {
      id: "do-el-dia",
      countryCode: "DO",
      name: "El Día",
      englishTranslation: "The Day",
      founded: 2002,
      frequency: "Daily newspaper (Monday–Friday)",
      format: "Compact free daily & digital portal",
      language: "Spanish",
      headquarters: "Santo Domingo",
      owner: {
        name: "Grupo de Comunicaciones Corripio",
        type: "Independent commercial media",
      },
      editorialStance: "Morning commuter newspaper; concise national news, urban affairs, health, education, and entertainment",
      readership: {
        metric: "Distributed freely to commuters across Santo Domingo and Santiago with 120,000+ daily copies",
        source: "El Día Media Distribution 2024",
      },
      revenueModel: "Commercial print advertising and digital web sponsorships",
      logo: "newspaper-logos/do/el-día.svg",
      logoExplainer:
        "Yellow and red masthead featuring bold typography 'El Día', iconic for morning urban commuter news in the capital.",
      sources: ["https://eldia.com.do", "https://es.wikipedia.org/wiki/El_D%C3%ADa_(Rep%C3%BAblica_Dominicana)"],
    },
  ],

  // Timor-Leste
  TL: [
    {
      id: "tl-tatoli",
      countryCode: "TL",
      name: "Tatoli",
      officialName: "Agência Noticiosa de Timor-Leste",
      nativeName: "Tatoli - Agência Noticiosa de Timor-Leste",
      englishTranslation: "Tatoli (Tetum: To deliver / communicate)",
      founded: 2016,
      frequency: "Continuous 24/7 national newswire",
      format: "Official state newswire & multimedia portal",
      language: "Tetum, Portuguese, English, Indonesian",
      headquarters: "Farol, Dili",
      owner: {
        name: "Democratic Republic of Timor-Leste (SECOMS)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official national news agency of Timor-Leste; government decisions, parliamentary legislation, ASEAN accession, and petroleum fund management",
      readership: {
        metric: "Primary news agency supplying wire dispatches to all domestic radio, television, and print media across all 14 municipalities",
        source: "Tatoli I.P. Relatório Anual 2023",
      },
      annualPublicFunding: {
        total: "US$1.2 million annual state budget allocation",
        perCapita: "US$0.89 / person / year",
      },
      revenueModel: "Direct state budget appropriation and news syndication services",
      logo: "newspaper-logos/tl/tatoli.svg",
      logoExplainer:
        "Vibrant red and black emblem inspired by the Timor-Leste national flag with clean white lettering 'TATOLI', representing national state news.",
      sources: ["https://tatoli.tl", "https://pt.wikipedia.org/wiki/Tatoli"],
    },
    {
      id: "tl-suara-timor-lorosae",
      countryCode: "TL",
      name: "Suara Timor Lorosa'e",
      officialName: "STL Media Group",
      nativeName: "Suara Timor Lorosa'e",
      englishTranslation: "Voice of the Eastern Sun",
      founded: 1993,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Broadsheet & digital network",
      language: "Tetum, Portuguese, Indonesian",
      headquarters: "Bairo Pite, Dili",
      owner: {
        name: "Salvador Ximenes Soares / STL Group",
        type: "Independent commercial media",
      },
      editorialStance: "Oldest continuously operating newspaper in Timor-Leste; historic voice during the independence struggle; parliamentary affairs, justice, and community news",
      readership: {
        metric: "Largest print circulation daily in Timor-Leste and multi-platform network with STL TV and STL Radio FM",
        source: "STL Media Group Overview 2023",
      },
      revenueModel: "Print sales, official advertisements, and commercial broadcast sponsorships",
      logo: "newspaper-logos/tl/suara-timor-lorosae.svg",
      logoExplainer:
        "Red and blue emblem displaying traditional sunrise motif and bold typography 'STL', symbolising the Voice of East Timor.",
      sources: ["https://suara-timor-lorosae.com", "https://en.wikipedia.org/wiki/Suara_Timor_Lorosae"],
    },
    {
      id: "tl-timor-post",
      countryCode: "TL",
      name: "Timor Post",
      nativeName: "Jornal Diário Timor Post",
      englishTranslation: "Timor Post Daily",
      founded: 2000,
      frequency: "Daily newspaper",
      format: "Tabloid publication & digital portal",
      language: "Tetum, Portuguese",
      headquarters: "Rua Bispo de Medeiros, Dili",
      owner: {
        name: "Timor Post Media Group",
        type: "Independent commercial media",
      },
      editorialStance: "Independent commercial daily newspaper; political commentary, civil society debates, anti-corruption reporting, and youth employment",
      readership: {
        metric: "Key daily newspaper in Dili read by civil servants, students, and diplomatic staff",
        source: "Timor Post Corporate Kit 2024",
      },
      revenueModel: "Print newspaper circulation, institutional advertising, and web banners",
      logo: "newspaper-logos/tl/timor-post.svg",
      logoExplainer:
        "Red and yellow title block with bold sans-serif lettering 'TIMOR POST', representing independent national journalism.",
      sources: ["https://diariutimorpost.com", "https://en.wikipedia.org/wiki/Timor_Post"],
    },
    {
      id: "tl-jornal-independente",
      countryCode: "TL",
      name: "Jornal Independente",
      englishTranslation: "Independent Newspaper",
      founded: 2011,
      frequency: "Daily newspaper",
      format: "Tabloid & digital portal",
      language: "Tetum, Portuguese",
      headquarters: "Dili",
      owner: {
        name: "Grupo Independente Media",
        type: "Independent commercial media",
      },
      editorialStance: "Independent daily newspaper; investigative reporting, rural development, judicial accountability, and community human rights",
      readership: {
        metric: "Widely distributed daily newspaper across educational institutions and government ministries in Dili",
        source: "Conselho de Imprensa de Timor-Leste 2023",
      },
      revenueModel: "Print sales and local corporate advertisements",
      logo: "newspaper-logos/tl/jornal-independente.svg",
      logoExplainer:
        "Blue banner with white typography 'INDEPENDENTE', symbolising democratic transparency and press freedom in Timor-Leste.",
      sources: ["https://independente.tl"],
    },
    {
      id: "tl-dilivox",
      countryCode: "TL",
      name: "Dili Vox",
      englishTranslation: "Dili Voice",
      founded: 2019,
      frequency: "Continuous digital news service",
      format: "Digital youth portal & Web TV",
      language: "Tetum, English",
      headquarters: "Dili",
      owner: {
        name: "Dili Vox Media",
        type: "Independent commercial media",
      },
      editorialStance: "Youth-oriented multimedia news platform; creative economy, environmental activism, technology startups, and civic education",
      readership: {
        metric: "Fastest-growing digital native outlet engaging Timorese youth with 300,000+ monthly digital interactions",
        source: "Dili Vox Audience Metrics 2024",
      },
      revenueModel: "Digital video advertising and non-governmental organization partnerships",
      logo: "newspaper-logos/tl/dilivox.svg",
      logoExplainer:
        "Modern neon green and dark slate icon 'DILI VOX', representing the voice of the young Timorese generation.",
      sources: ["https://dilivox.com"],
    },
  ],

  // Ecuador
  EC: [
    {
      id: "ec-el-comercio",
      countryCode: "EC",
      name: "El Comercio",
      englishTranslation: "The Commerce",
      founded: 1906,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Spanish",
      headquarters: "Quito, Pichincha",
      owner: {
        name: "Grupo El Comercio",
        type: "Independent commercial media",
      },
      editorialStance: "Ecuador's historic capital newspaper of record founded by the Mantilla brothers; national politics, Andean economics, and judicial affairs",
      readership: {
        metric: "Over 6 million monthly unique digital visitors on elcomercio.com; primary quality paper in Quito and the sierra region",
        source: "Grupo El Comercio Memoria Anual 2023",
      },
      revenueModel: "Digital subscriptions, print sales, and corporate advertising",
      logo: "newspaper-logos/ec/el-comercio.svg",
      logoExplainer:
        "Classic black serif typography 'EL COMERCIO' on clean white canvas, representing over 118 years of Ecuadorian journalism.",
      sources: ["https://www.elcomercio.com", "https://en.wikipedia.org/wiki/El_Comercio_(Ecuador)"],
    },
    {
      id: "ec-el-universo",
      countryCode: "EC",
      name: "El Universo",
      englishTranslation: "The Universe",
      founded: 1921,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Spanish",
      headquarters: "Guayaquil, Guayas",
      owner: {
        name: "Grupo El Universo (Pérez family)",
        type: "Independent commercial media",
      },
      editorialStance: "Ecuador's largest circulation daily; voice of the coastal Pacific commercial hub Guayaquil; free-market advocacy, investigative reporting, and constitutional democracy",
      readership: {
        metric: "Highest print circulation in Ecuador and premier online news destination with 8+ million monthly visitors",
        source: "El Universo Audience Review 2024",
      },
      revenueModel: "Digital subscriptions, print sales, and commercial display advertising",
      logo: "newspaper-logos/ec/el-universo.svg",
      logoExplainer:
        "Deep blue banner with white serif masthead 'EL UNIVERSO', the most recognized newspaper emblem in the Pacific coast of Ecuador.",
      sources: ["https://www.eluniverso.com", "https://en.wikipedia.org/wiki/El_Universo"],
    },
    {
      id: "ec-expreso",
      countryCode: "EC",
      name: "Expreso",
      englishTranslation: "Express",
      founded: 1973,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Spanish",
      headquarters: "Guayaquil",
      owner: {
        name: "Gráficos Nacionales S.A. (Granasa)",
        type: "Independent commercial media",
      },
      editorialStance: "Influential national daily; in-depth investigative political reporting, macroeconomic analysis, agribusiness, and coastal economic affairs",
      readership: {
        metric: "Over 3.5 million monthly digital readers on expreso.ec and major institutional readership across Guayas and Pichincha",
        source: "Granasa Media Kit 2024",
      },
      revenueModel: "Print circulation, digital paywall, and business advertising",
      logo: "newspaper-logos/ec/expreso.svg",
      logoExplainer:
        "Vibrant red banner with crisp white serif typography 'EXPRESO', symbolising energetic independent daily journalism.",
      sources: ["https://www.expreso.ec", "https://es.wikipedia.org/wiki/Expreso_(Ecuador)"],
    },
    {
      id: "ec-primicias",
      countryCode: "EC",
      name: "Primicias",
      englishTranslation: "Scoops / First News",
      founded: 2019,
      frequency: "Continuous 24/7 digital news service",
      format: "Digital-only investigative portal",
      language: "Spanish",
      headquarters: "Quito",
      owner: {
        name: "Primicias Periodismo Digital S.A.",
        type: "Independent commercial media",
      },
      editorialStance: "Modern digital investigative media; high-impact investigative scoops, security coverage, energy policy, and visual data journalism",
      readership: {
        metric: "Rapidly grown to over 5 million monthly unique users, becoming one of Ecuador's top digital news references",
        source: "Similarweb & Primicias Analytics 2024",
      },
      revenueModel: "Digital advertising, corporate brand partnerships, and investigative grants",
      logo: "newspaper-logos/ec/primicias.svg",
      logoExplainer:
        "Minimalist navy and yellow badge with modern lowercase typography 'primicias', representing data-driven digital scoops.",
      sources: ["https://www.primicias.ec"],
    },
    {
      id: "ec-lideres",
      countryCode: "EC",
      name: "Revista Líderes",
      englishTranslation: "Leaders Magazine",
      founded: 1998,
      frequency: "Weekly business publication (Monday)",
      format: "Tabloid publication & business portal",
      language: "Spanish",
      headquarters: "Quito",
      owner: {
        name: "Grupo El Comercio",
        type: "Independent commercial media",
      },
      editorialStance: "Ecuador's premier specialized business weekly; corporate profiles, entrepreneurship, fintech, and economic competitiveness",
      readership: {
        metric: "Essential reading for senior executives, entrepreneurs, and finance professionals across Ecuador",
        source: "Grupo El Comercio Business Division 2023",
      },
      revenueModel: "Corporate subscriptions and business-to-business advertising",
      logo: "newspaper-logos/ec/lideres.svg",
      logoExplainer:
        "Deep emerald green banner with white typography 'LÍDERES', symbolising corporate excellence and economic leadership.",
      sources: ["https://www.revistalideres.ec"],
    },
  ],

  // Egypt
  EG: [
    {
      id: "eg-al-ahram",
      countryCode: "EG",
      name: "Al-Ahram",
      officialName: "Al-Ahram Establishment",
      nativeName: "الأهرام",
      englishTranslation: "The Pyramids",
      founded: 1875,
      frequency: "Daily newspaper",
      format: "Broadsheet & international news network",
      language: "Arabic, with English (Al-Ahram Weekly) and French editions",
      headquarters: "Al-Galaa Street, Cairo",
      owner: {
        name: "National Press Authority of Egypt",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Egypt's historic newspaper of record and the most famous newspaper in the Arab world; official government policy, Arab diplomacy, regional security, and cultural literature",
      readership: {
        metric: "Largest print circulation in the Middle East with over 900,000 daily copies and global digital reach exceeding 20 million across Ahram Online",
        source: "Al-Ahram Publishing House Report 2023",
      },
      annualPublicFunding: {
        total: "Central state publishing allocation through National Press Authority",
        perCapita: "State newspaper of record",
      },
      revenueModel: "State budget appropriation, print subscriptions, book publishing, and advertising",
      logo: "newspaper-logos/eg/al-ahram.svg",
      logoExplainer:
        "Classic Arabic calligraphy 'الأهرام' in black and gold, representing over 150 years of foundational Arab journalism.",
      sources: ["https://gate.ahram.org.eg", "https://en.wikipedia.org/wiki/Al-Ahram"],
    },
    {
      id: "eg-al-masry-al-youm",
      countryCode: "EG",
      name: "Al-Masry Al-Youm",
      nativeName: "المصري اليوم",
      englishTranslation: "The Egyptian Today",
      founded: 2004,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Arabic",
      headquarters: "Cairo",
      owner: {
        name: "Al-Masry Media Corp (Salah Diab)",
        type: "Independent commercial media",
      },
      editorialStance: "Egypt's leading independent private broadsheet; in-depth political investigations, critical economic commentary, culture, and pluralistic opinion columns",
      readership: {
        metric: "Largest print circulation among private Egyptian dailies and top digital portal with over 15 million monthly visits",
        source: "Al-Masry Media Audience Report 2024",
      },
      revenueModel: "Print sales, digital display advertising, and corporate sponsorships",
      logo: "newspaper-logos/eg/al-masry-al-youm.svg",
      logoExplainer:
        "Blue and red title badge featuring modern Arabic typography 'المصري اليوم', symbolising independent pluralistic Egyptian news.",
      sources: ["https://www.almasryalyoum.com", "https://en.wikipedia.org/wiki/Al-Masry_Al-Youm"],
    },
    {
      id: "eg-youm7",
      countryCode: "EG",
      name: "Youm7",
      officialName: "The Seventh Day",
      nativeName: "اليوم السابع",
      englishTranslation: "The Seventh Day",
      founded: 2008,
      frequency: "Continuous digital news service & daily print",
      format: "Digital-first portal & daily tabloid",
      language: "Arabic",
      headquarters: "Mohandessin, Giza / Cairo",
      owner: {
        name: "United Media Services (UMS)",
        type: "Independent commercial media",
      },
      editorialStance: "Egypt's largest digital news network; breaking real-time multimedia news, video journalism, sports (Egyptian Premier League), and entertainment",
      readership: {
        metric: "Most visited news website in Egypt and the Arab world with over 45 million monthly unique digital visitors",
        source: "Similarweb & UMS Group 2024",
      },
      revenueModel: "Digital programmatic advertising, video monetization, and commercial partnerships",
      logo: "newspaper-logos/eg/youm7.svg",
      logoExplainer:
        "Vivid red and black badge with stylized Arabic numeral '7' and typography 'اليوم السابع', iconic across Middle Eastern mobile news.",
      sources: ["https://www.youm7.com", "https://en.wikipedia.org/wiki/Youm7"],
    },
    {
      id: "eg-al-wafd",
      countryCode: "EG",
      name: "Al-Wafd",
      nativeName: "الوفد",
      englishTranslation: "The Delegation",
      founded: 1984,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Arabic",
      headquarters: "Dokki, Giza",
      owner: {
        name: "New Wafd Party",
        type: "Independent commercial media",
      },
      editorialStance: "Official daily newspaper of the liberal-nationalist New Wafd Party; political opposition commentary, constitutional law, and democratic governance",
      readership: {
        metric: "Pioneer partisan newspaper in Egypt with widespread historical readership among jurists and academics",
        source: "Al-Wafd Media Center 2023",
      },
      revenueModel: "Print sales, party subscriptions, and commercial advertising",
      logo: "newspaper-logos/eg/al-wafd.svg",
      logoExplainer:
        "Classic green title banner with white Arabic lettering 'جريدة الوفد', representing liberal nationalist democratic heritage.",
      sources: ["https://alwafd.news", "https://en.wikipedia.org/wiki/Al-Wafd_(newspaper)"],
    },
    {
      id: "eg-egypt-today",
      countryCode: "EG",
      name: "Egypt Today",
      founded: 1979,
      frequency: "Monthly magazine & daily digital portal",
      format: "English news magazine & digital portal",
      language: "English",
      headquarters: "Cairo",
      owner: {
        name: "United Media Services (UMS)",
        type: "Independent commercial media",
      },
      editorialStance: "Egypt's premier English-language current affairs magazine and news portal; international diplomacy, archaeological discoveries, Grand Egyptian Museum, and tourism",
      readership: {
        metric: "Primary news source for English-speaking diplomats, expatriates, and foreign investors in Egypt",
        source: "UMS International Division 2024",
      },
      revenueModel: "Print magazine circulation, international subscriptions, and tourism advertising",
      logo: "newspaper-logos/eg/egypt-today.svg",
      logoExplainer:
        "Gold and black emblem with refined serif typography 'EGYPT TODAY', evoking Egyptian antiquities and international diplomacy.",
      sources: ["https://www.egypttoday.com", "https://en.wikipedia.org/wiki/Egypt_Today"],
    },
  ],

  // El Salvador
  SV: [
    {
      id: "sv-la-prensa-grafica",
      countryCode: "SV",
      name: "La Prensa Gráfica",
      officialName: "La Prensa Gráfica (LPG)",
      englishTranslation: "The Graphic Press",
      founded: 1915,
      frequency: "Daily newspaper",
      format: "Berliner & digital portal",
      language: "Spanish",
      headquarters: "Antiguo Cuscatlán, San Salvador",
      owner: {
        name: "Grupo Dutriz",
        type: "Independent commercial media",
      },
      editorialStance: "El Salvador's historic newspaper of record; center-right liberal editorial stance focusing on judicial independence, national security, macroeconomics, and human rights",
      readership: {
        metric: "Highest print circulation in El Salvador and leading digital portal laprensagrafica.com reaching 4.5 million monthly visitors",
        source: "Grupo Dutriz Memoria Anual 2023",
      },
      revenueModel: "Digital paywall subscriptions, print sales, and corporate advertising",
      logo: "newspaper-logos/sv/la-pensa-gráfica.svg",
      logoExplainer:
        "Navy blue banner with classical white serif masthead 'LA PRENSA GRÁFICA', symbolising over a century of Salvadoran news leadership.",
      sources: ["https://www.laprensagrafica.com", "https://en.wikipedia.org/wiki/La_Prensa_Gr%C3%A1fica"],
    },
    {
      id: "sv-el-diario-de-hoy",
      countryCode: "SV",
      name: "El Diario de Hoy",
      officialName: "El Diario de Hoy (EDH)",
      englishTranslation: "Today's Daily",
      founded: 1936,
      frequency: "Daily newspaper",
      format: "Broadsheet & digital portal",
      language: "Spanish",
      headquarters: "San Salvador",
      owner: {
        name: "Editorial Altamirano Madriz S.A.",
        type: "Independent commercial media",
      },
      editorialStance: "Conservative quality daily newspaper; free-market advocacy, rule of law, anti-corruption investigations, and regional Central American commerce",
      readership: {
        metric: "Over 4 million monthly digital readers on elsalvador.com and strong institutional print circulation",
        source: "Editorial Altamirano Madriz 2024",
      },
      revenueModel: "Print sales, digital subscriptions, and display advertising",
      logo: "newspaper-logos/sv/el-diario-de-hoy.svg",
      logoExplainer:
        "Red and black logo with bold serif text 'elsalvador.com / El Diario de Hoy', iconic in Salvadoran conservative journalism.",
      sources: ["https://www.elsalvador.com", "https://en.wikipedia.org/wiki/El_Diario_de_Hoy"],
    },
    {
      id: "sv-el-faro",
      countryCode: "SV",
      name: "El Faro",
      englishTranslation: "The Lighthouse",
      founded: 1998,
      frequency: "Continuous digital investigative magazine",
      format: "Investigative digital portal",
      language: "Spanish, English",
      headquarters: "San Salvador",
      owner: {
        name: "Fundación Trípode (Carlos Dada & Jorge Simán)",
        type: "Non-profit independent foundation",
      },
      editorialStance: "Pioneer of independent digital investigative journalism in Latin America; internationally acclaimed for investigations into state corruption, gangs, and democratic backsliding",
      readership: {
        metric: "Winner of the Maria Moors Cabot Prize and Columbia Journalism Award; globally recognized voice on Central American democracy",
        source: "Fundación Trípode Impact Report 2023",
      },
      revenueModel: "Philanthropic journalism grants, reader crowdfunding, and syndicated investigations",
      logo: "newspaper-logos/sv/el-faro.svg",
      logoExplainer:
        "Stark black and gold emblem featuring a glowing lighthouse beam and lowercase text 'elfaro', symbolising courage and transparency.",
      sources: ["https://elfaro.net", "https://en.wikipedia.org/wiki/El_Faro_(digital_newspaper)"],
    },
    {
      id: "sv-diario-el-salvador",
      countryCode: "SV",
      name: "Diario El Salvador",
      englishTranslation: "El Salvador Daily",
      founded: 2020,
      frequency: "Daily newspaper",
      format: "Compact daily & digital portal",
      language: "Spanish",
      headquarters: "San Salvador",
      owner: {
        name: "State of El Salvador",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "State-owned daily newspaper established under President Nayib Bukele; government infrastructure projects, public safety policies, Bitcoin adoption, and social programs",
      readership: {
        metric: "Over 60,000 daily print distribution nationwide with heavily trafficked digital portal diarioelsalvador.com",
        source: "Diario El Salvador Informe Institucional 2023",
      },
      revenueModel: "State institutional advertising and low-cost retail print sales",
      logo: "newspaper-logos/sv/diario-el-salvador.svg",
      logoExplainer:
        "Cyan blue and white badge with clean modern typography 'DIARIO EL SALVADOR', representing contemporary state public communication.",
      sources: ["https://diarioelsalvador.com", "https://es.wikipedia.org/wiki/Diario_El_Salvador"],
    },
    {
      id: "sv-el-mundo",
      countryCode: "SV",
      name: "Diario El Mundo",
      englishTranslation: "The World Daily",
      founded: 1967,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Tabloid publication & digital portal",
      language: "Spanish",
      headquarters: "San Salvador",
      owner: {
        name: "Editorial Chinchontepec (Borja family)",
        type: "Independent commercial media",
      },
      editorialStance: "Centrist afternoon and morning daily; balanced coverage of parliamentary politics, business developments, community issues, and sports",
      readership: {
        metric: "Over 2.2 million monthly unique digital visitors on elmundo.sv and regular daily print readership in the capital",
        source: "Diario El Mundo Media Kit 2024",
      },
      revenueModel: "Print sales and commercial advertising",
      logo: "newspaper-logos/sv/el-mundo.svg",
      logoExplainer:
        "Red and blue title banner with white serif font 'EL MUNDO', symbolising reliable daily news coverage in El Salvador.",
      sources: ["https://diario.elmundo.sv", "https://es.wikipedia.org/wiki/El_Mundo_(El_Salvador)"],
    },
  ],

  // Equatorial Guinea
  GQ: [
    {
      id: "gq-guinea-ecuatorial-press",
      countryCode: "GQ",
      name: "Guinea Ecuatorial Press",
      officialName: "Oficina de Información y Prensa de Guinea Ecuatorial",
      englishTranslation: "Equatorial Guinea Press",
      founded: 2010,
      frequency: "Continuous 24/7 official state newswire",
      format: "Official state wire service & digital portal",
      language: "Spanish, French, English",
      headquarters: "Malabo, Bioko Norte",
      owner: {
        name: "Republic of Equatorial Guinea (Dirección General de Prensa Presidencial)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official national information wire; presidential decrees, hydrocarbons sector developments, infrastructure projects, and CEMAC regional diplomacy",
      readership: {
        metric: "Primary source of official government information for domestic media, foreign diplomatic missions, and international oil sector operators",
        source: "Oficina de Información y Prensa 2023",
      },
      annualPublicFunding: {
        total: "Central state operational budget via Ministry of Information",
        perCapita: "State information agency",
      },
      revenueModel: "Direct state budget funding",
      logo: "newspaper-logos/gq/guinea-ecuatorial-press.svg",
      logoExplainer:
        "Official national emblem featuring the silk cotton tree (Ceiba pentandra) and blue text 'GUINEA ECUATORIAL PRESS', symbolising state authority.",
      sources: ["https://guineaecuatorialpress.com", "https://es.wikipedia.org/wiki/Guinea_Ecuatorial"],
    },
    {
      id: "gq-ahora-eg",
      countryCode: "GQ",
      name: "AhoraEG",
      englishTranslation: "Now Equatorial Guinea",
      founded: 2018,
      frequency: "Continuous digital news service",
      format: "Digital multimedia portal",
      language: "Spanish",
      headquarters: "Malabo & Bata",
      owner: {
        name: "AhoraEG Media Group",
        type: "Independent commercial media",
      },
      editorialStance: "Digital news and lifestyle portal; national economics, sports (Nzalang Nacional), youth initiatives, and cultural festivals in Malabo and Bata",
      readership: {
        metric: "Over 350,000 monthly digital visits; leading private online news destination inside Equatorial Guinea",
        source: "AhoraEG Audience Analytics 2024",
      },
      revenueModel: "Digital display advertising and sponsored corporate media",
      logo: "newspaper-logos/gq/ahora-eg.svg",
      logoExplainer:
        "Modern red and navy blue banner with bold typography 'AhoraEG', representing dynamic digital journalism.",
      sources: ["https://ahoraeg.com"],
    },
    {
      id: "gq-real-equatorial-guinea",
      countryCode: "GQ",
      name: "Real Equatorial Guinea",
      founded: 2019,
      frequency: "Continuous digital news magazine",
      format: "Digital magazine & portal",
      language: "Spanish, English",
      headquarters: "Malabo",
      owner: {
        name: "Real EG Media Network",
        type: "Independent commercial media",
      },
      editorialStance: "Bilingual digital magazine; entrepreneurship, tourism potential, arts, and positive development narratives from Equatorial Guinea",
      readership: {
        metric: "Widely read by young professionals, university students, and international expatriates in Malabo",
        source: "Real EG Media Kit 2023",
      },
      revenueModel: "Corporate partnerships and digital branding campaigns",
      logo: "newspaper-logos/gq/real-equatorial-guinea.svg",
      logoExplainer:
        "Gold and dark slate emblem featuring 'Real Equatorial Guinea', symbolising cultural pride and modern economic progress.",
      sources: ["https://realequatorialguinea.com"],
    },
    {
      id: "gq-ebano",
      countryCode: "GQ",
      name: "Ébano",
      englishTranslation: "Ebony",
      founded: 1939,
      frequency: "Weekly newspaper",
      format: "Official state print tabloid",
      language: "Spanish",
      headquarters: "Malabo",
      owner: {
        name: "State of Equatorial Guinea (Ministerio de Información)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Historic state-owned print publication in Malabo; government announcements, ministerial resolutions, and cultural events",
      readership: {
        metric: "Historic print newspaper distributed in government ministries and public administrative centers",
        source: "Ministerio de Información, Prensa y Radio 2023",
      },
      revenueModel: "State publishing subsidy",
      logo: "newspaper-logos/gq/ébano.svg",
      logoExplainer:
        "Classic black typography 'ÉBANO' on white ground, symbolising the historic print press of Bioko Island.",
      sources: ["https://es.wikipedia.org/wiki/%C3%89bano_(peri%C3%B3dico)"],
    },
    {
      id: "gq-diario-rombe",
      countryCode: "GQ",
      name: "Diario Rombe",
      founded: 2012,
      frequency: "Continuous digital investigative portal",
      format: "Investigative digital portal",
      language: "Spanish",
      headquarters: "Malabo / Spain (Diaspora)",
      owner: {
        name: "Rombe Media Group (Delfin Mocache Massoko)",
        type: "Independent commercial media",
      },
      editorialStance: "Independent investigative news outlet operating primarily from the diaspora; human rights reporting, offshore financial transparency, and political accountability",
      readership: {
        metric: "Widely followed investigative outlet among civil society activists and the Equatorial Guinean diaspora worldwide",
        source: "Diario Rombe Audience Report 2023",
      },
      revenueModel: "Reader donations and investigative journalism grants",
      logo: "newspaper-logos/gq/diario-rombe.svg",
      logoExplainer:
        "Black and red emblem with stylized bold text 'DIARIO ROMBE', representing independent investigative journalism in exile.",
      sources: ["https://diariorombe.es", "https://es.wikipedia.org/wiki/Diario_Rombe"],
    },
  ],

  // Eritrea
  ER: [
    {
      id: "er-shabait",
      countryCode: "ER",
      name: "Shabait",
      officialName: "Ministry of Information News Portal",
      englishTranslation: "Shabait (named after the historic popular front)",
      founded: 2000,
      frequency: "Continuous 24/7 official state newswire",
      format: "Official state wire service & digital portal",
      language: "Tigrinya, Arabic, English, French",
      headquarters: "Asmara",
      owner: {
        name: "State of Eritrea (Ministry of Information)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official state information portal of Eritrea; presidential statements, national service development projects, agricultural dams, and diplomatic relations",
      readership: {
        metric: "Primary official news source inside Eritrea and for the worldwide Eritrean diaspora",
        source: "Ministry of Information Eritrea 2023",
      },
      annualPublicFunding: {
        total: "Central state operational budget via Ministry of Information",
        perCapita: "State information service",
      },
      revenueModel: "Direct state budget funding",
      logo: "newspaper-logos/er/shabait.svg",
      logoExplainer:
        "Red and green banner inspired by the Eritrean flag with bold white typography 'SHABAIT', representing official state communication.",
      sources: ["https://shabait.com", "https://en.wikipedia.org/wiki/Ministry_of_Information_(Eritrea)"],
    },
    {
      id: "er-haddas-eritrea",
      countryCode: "ER",
      name: "Haddas Eritrea",
      nativeName: "ሓዳስ ኤርትራ",
      englishTranslation: "New Eritrea",
      founded: 1991,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Official state broadsheet",
      language: "Tigrinya",
      headquarters: "Asmara",
      owner: {
        name: "Ministry of Information",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official national public Tigrinya-language daily; national development campaigns, regional zoba administration news, literature, and educational notices",
      readership: {
        metric: "Sole daily print newspaper in Tigrinya with universal distribution across government and community kiosks in Asmara",
        source: "Eritrean Ministry of Information 2023",
      },
      revenueModel: "State publishing subsidy and retail kiosk print sales",
      logo: "newspaper-logos/er/haddas-eritrea.svg",
      logoExplainer:
        "Elegant Tigrinya Ge'ez calligraphy 'ሓዳስ ኤርትራ' on white ground, symbolising national renewal and indigenous language heritage.",
      sources: ["https://shabait.com/category/haddas-ertra/", "https://en.wikipedia.org/wiki/Haddas_Eritrea"],
    },
    {
      id: "er-eritrea-profile",
      countryCode: "ER",
      name: "Eritrea Profile",
      founded: 1993,
      frequency: "Bi-weekly newspaper (Wednesday & Saturday)",
      format: "Official state English broadsheet & portal",
      language: "English",
      headquarters: "Asmara",
      owner: {
        name: "Ministry of Information",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Official state English-language newspaper; foreign policy, Red Sea maritime cooperation, UN affairs, mining developments, and national history",
      readership: {
        metric: "Read by foreign diplomats, international organizations, scholars, and diaspora communities",
        source: "Ministry of Information Profile 2023",
      },
      revenueModel: "State budget funding and print sales",
      logo: "newspaper-logos/er/eritrea-profile.svg",
      logoExplainer:
        "Deep blue banner with classical serif lettering 'ERITREA PROFILE', the definitive English print masthead of Asmara.",
      sources: ["https://shabait.com/category/eritrea-profile/", "https://en.wikipedia.org/wiki/Eritrea_Profile"],
    },
    {
      id: "er-eritrean-digest",
      countryCode: "ER",
      name: "Eritrean Digest",
      founded: 2018,
      frequency: "Continuous digital analysis & portal",
      format: "Digital analytical portal",
      language: "English, Tigrinya",
      headquarters: "Asmara / Washington D.C.",
      owner: {
        name: "Eritrean Digest Media (Saleh Younis)",
        type: "Independent commercial media",
      },
      editorialStance: "Independent diaspora analytical platform; in-depth political commentary, peace accords, Horn of Africa regional geopolitics, and historical archives",
      readership: {
        metric: "Widely read by international Horn of Africa scholars, think tanks, and global diaspora communities",
        source: "Eritrean Digest Analytics 2024",
      },
      revenueModel: "Reader patronage and academic media grants",
      logo: "newspaper-logos/er/eritrean-digest.svg",
      logoExplainer:
        "Warm terracotta badge with modern typography 'ERITREAN DIGEST', symbolising independent historical analysis and debate.",
      sources: ["https://eritreandigest.com"],
    },
    {
      id: "er-assenna",
      countryCode: "ER",
      name: "Assenna",
      englishTranslation: "Assenna (Tigrinya: Foundation / Heritage)",
      founded: 2008,
      frequency: "Continuous digital news & satellite broadcasting",
      format: "Digital news portal & satellite TV",
      language: "Tigrinya, English",
      headquarters: "London, UK / Diaspora",
      owner: {
        name: "Assenna Foundation (Amanuel Eyasu)",
        type: "Independent trust / foundation",
      },
      editorialStance: "Prominent diaspora human rights and opposition media organization; investigative reporting on human rights conditions, political prisoners, and civic mobilization",
      readership: {
        metric: "Massive diaspora reach with over 2 million monthly digital video and news consumers across Europe, North America, and the Middle East",
        source: "Assenna Foundation Annual Report 2023",
      },
      revenueModel: "Diaspora crowdfunding, foundation grants, and viewer donations",
      logo: "newspaper-logos/er/assenna.svg",
      logoExplainer:
        "Vibrant red banner with stylized white flame and bold typography 'ASSENNA', representing independent human rights advocacy in exile.",
      sources: ["https://assenna.com", "https://en.wikipedia.org/wiki/Assenna"],
    },
  ],

  // Estonia
  EE: [
    {
      id: "ee-postimees",
      countryCode: "EE",
      name: "Postimees",
      nativeName: "Postimees",
      englishTranslation: "The Postman",
      founded: 1857,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Broadsheet & digital network",
      language: "Estonian, Russian",
      headquarters: "Tallinn & Tartu",
      owner: {
        name: "Postimees Grupp (Margus Linnamäe / MM Grupp)",
        type: "Independent commercial media",
      },
      editorialStance: "Estonia's oldest newspaper and premier national newspaper of record; conservative-liberal stance focusing on national sovereignty, digital society (e-Estonia), and European security",
      readership: {
        metric: "Over 650,000 weekly digital users on postimees.ee and largest paid newspaper circulation in Estonia",
        source: "Estonian Media Association & Kantar Emor 2024",
      },
      revenueModel: "Digital paywall subscriptions, print sales, and corporate advertising",
      logo: "newspaper-logos/ee/postimees.svg",
      logoExplainer:
        "Deep blue banner with white serif typography 'Postimees', the historic symbol of Estonian national awakening and journalism.",
      sources: ["https://www.postimees.ee", "https://en.wikipedia.org/wiki/Postimees"],
    },
    {
      id: "ee-delfi-ee",
      countryCode: "EE",
      name: "Delfi Estonia",
      founded: 1999,
      frequency: "Continuous 24/7 digital news service",
      format: "Digital-only news network",
      language: "Estonian, Russian",
      headquarters: "Tallinn",
      owner: {
        name: "Ekspress Grupp",
        type: "Independent commercial media",
      },
      editorialStance: "Estonia's largest digital news network; breaking real-time news, investigative journalism (Eesti Ekspress synergy), podcasts, and civic debate",
      readership: {
        metric: "Over 1.2 million monthly unique digital visitors; highest digital news reach in Estonia with 100,000+ digital subscribers",
        source: "Ekspress Grupp Financial Results 2024",
      },
      revenueModel: "Digital paywall subscriptions (Delfi Kogupakett) and programmatic advertising",
      logo: "newspaper-logos/ee/delfi-ee.svg",
      logoExplainer:
        "Orange and dark blue badge with bold sans-serif text 'DELFI', representing modern Baltic digital breaking journalism.",
      sources: ["https://www.delfi.ee", "https://en.wikipedia.org/wiki/Delfi_(web_portal)"],
    },
    {
      id: "ee-eesti-paevaleht",
      countryCode: "EE",
      name: "Eesti Päevaleht",
      officialName: "EPL",
      nativeName: "Eesti Päevaleht",
      englishTranslation: "Estonian Daily",
      founded: 1995,
      frequency: "Digital daily & weekend print",
      format: "Digital daily portal & analytical weekend edition",
      language: "Estonian",
      headquarters: "Tallinn",
      owner: {
        name: "Ekspress Grupp",
        type: "Independent commercial media",
      },
      editorialStance: "Center-left progressive quality newspaper; in-depth investigative political reporting, education reform, climate policy, and European affairs",
      readership: {
        metric: "Highly regarded intellectual broadsheet with strong digital readership integrated into Ekspress Grupp network",
        source: "Ekspress Grupp Media Report 2023",
      },
      revenueModel: "Digital subscriber packages and institutional subscriptions",
      logo: "newspaper-logos/ee/eesti-päevaleht.svg",
      logoExplainer:
        "Blue and red logo with bold clean lettering 'Eesti Päevaleht', symbolising contemporary analytical journalism.",
      sources: ["https://epl.delfi.ee", "https://en.wikipedia.org/wiki/Eesti_P%C3%A4evaleht"],
    },
    {
      id: "ee-aripaev",
      countryCode: "EE",
      name: "Äripäev",
      nativeName: "Äripäev",
      englishTranslation: "Business Day",
      founded: 1989,
      frequency: "Continuous digital business daily",
      format: "Digital-only financial daily & radio (Äripäeva Raadio)",
      language: "Estonian",
      headquarters: "Tallinn",
      owner: {
        name: "Bonnier Business Press",
        type: "Independent commercial media",
      },
      editorialStance: "Estonia's premier financial and economic daily; Tallinn Stock Exchange, startup ecosystem (tech unicorns), corporate governance, and fiscal policy",
      readership: {
        metric: "Over 25,000 paid corporate digital subscribers; primary business publication for Estonian entrepreneurs and investors",
        source: "Bonnier Business Press Estonia 2024",
      },
      revenueModel: "Digital corporate paywall, specialized business conferences, and B2B advertising",
      logo: "newspaper-logos/ee/äripäev.svg",
      logoExplainer:
        "Signature magenta-red banner with crisp white typography 'Äripäev', representing Nordic business intelligence in the Baltics.",
      sources: ["https://www.aripaev.ee", "https://en.wikipedia.org/wiki/%C3%84rip%C3%A4ev"],
    },
    {
      id: "ee-ohtuleht",
      countryCode: "EE",
      name: "Õhtuleht",
      nativeName: "Õhtuleht",
      englishTranslation: "Evening Paper",
      founded: 1944,
      frequency: "Daily newspaper (Monday–Saturday)",
      format: "Tabloid publication & digital portal",
      language: "Estonian",
      headquarters: "Tallinn",
      owner: {
        name: "Õhtuleht Kirjastus (Ekspress Grupp & Suits Media)",
        type: "Independent commercial media",
      },
      editorialStance: "Popular tabloid; consumer rights advocacy, sports, investigative exposés, human interest stories, and entertainment",
      readership: {
        metric: "Largest print circulation tabloid in Estonia and 700,000+ monthly digital readers on ohtuleht.ee",
        source: "Õhtuleht Kirjastus Annual Report 2023",
      },
      revenueModel: "Print newsstand sales, digital subscriptions, and display advertising",
      logo: "newspaper-logos/ee/õhtuleht.svg",
      logoExplainer:
        "Red and yellow title block with bold uppercase font 'ÕHTULEHT', iconic across Estonian newsstands.",
      sources: ["https://www.ohtuleht.ee", "https://en.wikipedia.org/wiki/%C3%95htuleht"],
    },
  ],

  // Eswatini
  SZ: [
    {
      id: "sz-times-of-eswatini",
      countryCode: "SZ",
      name: "Times of Eswatini",
      officialName: "The Times of Swaziland",
      founded: 1897,
      frequency: "Daily newspaper (Monday–Friday)",
      format: "Broadsheet & digital portal",
      language: "English",
      headquarters: "Mbabane",
      owner: {
        name: "African Echo (Pty) Ltd / Times of Swaziland Ltd",
        type: "Independent commercial media",
      },
      editorialStance: "Eswatini's oldest and primary independent newspaper; national politics, parliamentary proceedings, traditional tinkhundla governance, and social affairs",
      readership: {
        metric: "Largest print circulation daily in Eswatini with 30,000 daily copies and extensive digital readership",
        source: "Times of Eswatini Corporate Profile 2023",
      },
      revenueModel: "Print sales, legal notices, and commercial display advertising",
      logo: "newspaper-logos/sz/times-of-eswatini.svg",
      logoExplainer:
        "Classic black serif masthead 'Times of Eswatini' on white canvas, symbolising over 125 years of independent press history.",
      sources: ["http://www.times.co.sz", "https://en.wikipedia.org/wiki/The_Times_of_Swaziland"],
    },
    {
      id: "sz-ebuswini-observer",
      countryCode: "SZ",
      name: "Eswatini Observer",
      officialName: "The Swazi Observer",
      founded: 1981,
      frequency: "Daily newspaper (Monday–Friday)",
      format: "Broadsheet & digital portal",
      language: "English",
      headquarters: "Mbabane",
      owner: {
        name: "Tibiyo Taka Ngwane (Royal Charter Trust)",
        type: "State-owned / statutory corporation",
      },
      editorialStance: "Royal trust-owned daily newspaper; royal decrees, government infrastructure developments, diplomatic visits, and cultural preservation (Umhlanga)",
      readership: {
        metric: "Second largest daily newspaper in Eswatini, read throughout public administration and traditional councils",
        source: "Tibiyo Taka Ngwane Annual Report 2023",
      },
      revenueModel: "Commercial sales, official state notices, and royal trust funding",
      logo: "newspaper-logos/sz/ebuswini-observer.svg",
      logoExplainer:
        "Navy blue banner with white serif lettering 'Eswatini Observer', representing the royal chartered press of the Kingdom.",
      sources: ["https://new.observer.org.sz", "https://en.wikipedia.org/wiki/Swazi_Observer"],
    },
    {
      id: "sz-swaziland-news",
      countryCode: "SZ",
      name: "Swaziland News",
      founded: 2017,
      frequency: "Continuous digital investigative portal",
      format: "Investigative digital portal",
      language: "English, SiSwati",
      headquarters: "Mbabane / South Africa (Diaspora)",
      owner: {
        name: "Zweli Martin Dlamini",
        type: "Independent commercial media",
      },
      editorialStance: "Leading independent investigative online publication; critical coverage of absolute monarchy governance, human rights abuses, and pro-democracy movements",
      readership: {
        metric: "Highly influential digital news platform with over 800,000 monthly readers across Southern Africa",
        source: "Swaziland News Analytics 2024",
      },
      revenueModel: "Digital reader donations and international investigative journalism grants",
      logo: "newspaper-logos/sz/swaziland-news.svg",
      logoExplainer:
        "Red and black badge with bold typography 'SWAZILAND NEWS', symbolising fearless pro-democracy investigative journalism.",
      sources: ["https://swazilandnews.co.za"],
    },
    {
      id: "sz-swazi-bridge",
      countryCode: "SZ",
      name: "Swazi Bridge",
      founded: 2019,
      frequency: "Continuous digital news service",
      format: "Digital community portal",
      language: "English, SiSwati",
      headquarters: "Mbabane",
      owner: {
        name: "Swazi Bridge Media",
        type: "Independent commercial media",
      },
      editorialStance: "Digital community news network; rural development, youth initiatives, public healthcare, and educational opportunities in Eswatini",
      readership: {
        metric: "Popular digital news platform connecting urban centers with rural communities across Eswatini",
        source: "Swazi Bridge Audience Review 2023",
      },
      revenueModel: "Digital advertising and community sponsorships",
      logo: "newspaper-logos/sz/swazi-bridge.svg",
      logoExplainer:
        "Green and gold emblem with stylized arch bridge 'SWAZI BRIDGE', symbolising community connection and national dialogue.",
      sources: ["https://swazibridge.com"],
    },
    {
      id: "sz-independent-news-eswatini",
      countryCode: "SZ",
      name: "Independent News Eswatini",
      founded: 2015,
      frequency: "Weekly publication & digital portal",
      format: "Tabloid publication & digital portal",
      language: "English",
      headquarters: "Mbabane",
      owner: {
        name: "Independent News Media Eswatini",
        type: "Independent commercial media",
      },
      editorialStance: "Independent commercial weekly; business news, SME financing, agricultural reform, and cultural commentary",
      readership: {
        metric: "Read by business professionals, agricultural cooperatives, and civil society leaders",
        source: "Independent News Media 2023",
      },
      revenueModel: "Print retail sales and local commercial advertising",
      logo: "newspaper-logos/sz/independent-news-eswatini.svg",
      logoExplainer:
        "Dark slate banner with clean white text 'INDEPENDENT NEWS ESWATINI', representing commercial and economic weekly reporting.",
      sources: ["https://independentnews.co.sz"],
    },
  ],
`;

const closingIndex = content.lastIndexOf("};");
if (closingIndex === -1) {
  throw new Error("Could not find closing '};' in " + dataFile);
}

const updatedContent = content.slice(0, closingIndex) + block6Entries + "};\n";
fs.writeFileSync(dataFile, updatedContent, "utf8");
console.log("✓ Successfully added Block 6 entries to src/data/nationalNewsAgencies.ts");
