// GENERATED by scripts/build-national-flags.mjs — DO NOT EDIT BY HAND.
// Source of truth: scripts/data/national-flag-sources.json (curated + sourced).
// Re-run: node scripts/build-national-flags.mjs
//
// The Learn-mode "National flags" tab: every flag a country flies beyond its
// sub-national ones — its historical national flags (newest first, including the
// current one), any additional flags with official national status, its military
// service flags, maritime ensigns and jacks, head-of-state standards, civil/state
// variants and officially recognised indigenous flags.
//
// LINK TO THE HISTORICAL ERAS — a flag whose `path` starts with "historical-flags/"
// is the SAME image file the era maps show, carrying the same sourced from/to window
// (checked against src/data/historicalFlagValidity.ts by
// scripts/check-national-flags.mjs), so the two views can never disagree about what
// a country flew at a given date. The tab is NOT limited to the eras' 21 fixed
// dates: a flag flown between two era snapshots is listed here with its own window.

import type { FlagMeaning } from "./flagMeanings";

export type NationalFlagCategory =
  | "historical"
  | "official"
  | "military"
  | "maritime"
  | "standard"
  | "civilstate"
  | "indigenous";

export type NationalFlag = {
  /** Stable slug — React key, and the key into NATIONAL_FLAG_MEANINGS. */
  readonly id: string;
  readonly category: NationalFlagCategory;
  /** The flag's own name, as its cited source gives it. */
  readonly name: string;
  /**
   * First year the design was in official use. ABSENT when the source does not
   * date the flag — a service or ensign whose adoption year no authoritative
   * source gives is listed with no years rather than an invented one, and the
   * card simply shows its name. Always present on a "historical" flag, whose
   * whole point is the date (enforced by check-national-flags.mjs).
   */
  readonly from?: number;
  /** Last year it was in use (9999 = still current). */
  readonly to?: number;
  /** Image path relative to BASE_URL. */
  readonly path: string;
  /** What the image is — the card's sub-label. */
  readonly design: string;
  /** Authoritative source for the name and dates. */
  readonly source: string;
};

/** Keyed by ISO 3166-1 alpha-2. Countries with no curated flags are absent. */
export const NATIONAL_FLAGS: Readonly<Record<string, readonly NationalFlag[]>> = {
  "AU": [
    { id: "au-1908", category: "historical", name: "Australian National Flag", from: 1908, to: 9999, path: "flags/au.svg", design: "A Blue Ensign with the Union Jack in the canton, the seven-pointed Commonwealth Star beneath it and the Southern Cross in the fly.", source: "https://en.wikipedia.org/wiki/List_of_Australian_flags" },
    { id: "au-1903", category: "historical", name: "Flag of Australia (1903–1908)", from: 1903, to: 1908, path: "national-flags/au/australia-1903.svg", design: "The design as approved by Edward VII, with every star of the Southern Cross given seven points.", source: "https://en.wikipedia.org/wiki/List_of_Australian_flags" },
    { id: "au-1901", category: "historical", name: "Flag of Australia (1901–1903)", from: 1901, to: 1903, path: "national-flags/au/australia-1901.svg", design: "The winning entry in the 1901 Federal Flag design competition: a six-pointed Commonwealth Star, and Southern Cross stars of differing point counts.", source: "https://en.wikipedia.org/wiki/List_of_Australian_flags" },
    { id: "au-official-national", category: "official", name: "Australian National Flag", from: 1908, to: 9999, path: "flags/au.svg", design: "Proclaimed under the Flags Act 1953 as the flag of the Commonwealth of Australia.", source: "https://en.wikipedia.org/wiki/List_of_Australian_flags" },
    { id: "au-aboriginal", category: "official", name: "Australian Aboriginal Flag", from: 1971, to: 9999, path: "national-flags/au/australia-aboriginal.svg", design: "Black over red with a yellow disc at the centre; proclaimed a Flag of Australia in 1995.", source: "https://en.wikipedia.org/wiki/List_of_Australian_flags" },
    { id: "au-adf", category: "military", name: "Australian Defence Force Ensign", from: 2000, to: 9999, path: "national-flags/au/australia-adf.svg", design: "A tricolour of navy, army red and air-force blue bearing the Defence Force badge.", source: "https://en.wikipedia.org/wiki/List_of_Australian_flags" },
    { id: "au-navy", category: "military", name: "Australian White Ensign", from: 1967, to: 9999, path: "national-flags/au/australia-navy.svg", design: "The national flag on a white field, with the Commonwealth Star and Southern Cross in blue.", source: "https://en.wikipedia.org/wiki/List_of_Australian_flags" },
    { id: "au-raaf", category: "military", name: "Royal Australian Air Force Ensign", from: 1982, to: 9999, path: "national-flags/au/australia-raaf.svg", design: "An Air-Force-blue field with the Union Jack, the RAAF roundel and the Southern Cross.", source: "https://en.wikipedia.org/wiki/List_of_Australian_flags" },
    { id: "au-red-ensign", category: "maritime", name: "Australian Red Ensign", from: 1908, to: 9999, path: "national-flags/au/australia-red-ensign.svg", design: "A Red Ensign with the Commonwealth Star and the Southern Cross — the flag of Australian-registered merchant ships.", source: "https://en.wikipedia.org/wiki/List_of_Australian_flags" },
    { id: "au-royal", category: "standard", name: "King's Flag for Australia", from: 2024, to: 9999, path: "national-flags/au/australia-royal-standard.svg", design: "A banner of the Australian coat of arms, used by the sovereign in Australia.", source: "https://en.wikipedia.org/wiki/List_of_Australian_flags" },
    { id: "au-gg", category: "standard", name: "Flag of the Governor-General of Australia", from: 1936, to: 9999, path: "national-flags/au/australia-governor-general.svg", design: "A crowned lion standing on a crown, on a blue field.", source: "https://en.wikipedia.org/wiki/List_of_Australian_flags" },
  ],
  "BO": [
    { id: "bo-1851", category: "historical", name: "Flag of Bolivia", from: 1851, to: 9999, path: "flags/bo.svg", design: "A horizontal tricolour of red, yellow and green.", source: "https://en.wikipedia.org/wiki/List_of_Bolivian_flags" },
    { id: "bo-1826", category: "historical", name: "Flag of Bolivia (1826–1851)", from: 1826, to: 1851, path: "national-flags/bo/bolivia-1826.svg", design: "The second design: yellow over red over green, before the red and yellow were reversed in 1851.", source: "https://en.wikipedia.org/wiki/List_of_Bolivian_flags" },
    { id: "bo-1825", category: "historical", name: "Flag of Bolivia (1825–1826)", from: 1825, to: 1826, path: "national-flags/bo/bolivia-1825.svg", design: "The first flag of the new republic: a vertical triband of green, red and green with five stars.", source: "https://en.wikipedia.org/wiki/List_of_Bolivian_flags" },
    { id: "bo-wiphala", category: "official", name: "Wiphala", from: 2009, to: 9999, path: "national-flags/bo/bolivia-wiphala.svg", design: "A seven-by-seven patchwork of squares in the seven colours of the rainbow, set on the diagonal.", source: "https://en.wikipedia.org/wiki/List_of_Bolivian_flags" },
    { id: "bo-naval-ensign", category: "maritime", name: "Naval ensign of the Bolivian Navy", from: 2013, to: 9999, path: "national-flags/bo/bolivia-naval-ensign.svg", design: "A blue field bearing the tricolour and nine stars — one for each department, flown by a navy that patrols rivers and lakes since Bolivia lost its coastline in 1884.", source: "https://en.wikipedia.org/wiki/List_of_Bolivian_flags" },
    { id: "bo-naval-jack", category: "maritime", name: "Naval jack of Bolivia", from: 1851, to: 9999, path: "national-flags/bo/bolivia-naval-jack.svg", design: "A green field with a yellow and red double border.", source: "https://en.wikipedia.org/wiki/List_of_Bolivian_flags" },
    { id: "bo-state", category: "civilstate", name: "State flag of Bolivia", from: 1851, to: 9999, path: "national-flags/bo/bolivia-state.svg", design: "The tricolour charged with the coat of arms — flown by the state, while citizens fly the plain tricolour.", source: "https://en.wikipedia.org/wiki/List_of_Bolivian_flags" },
  ],
  "BR": [
    { id: "br-1992", category: "historical", name: "Flag of Brazil", from: 1992, to: 9999, path: "flags/br.svg", design: "27 stars — Tocantins, Amapá and Roraima were added when the states they represent were created.", source: "https://en.wikipedia.org/wiki/Flag_of_Brazil" },
    { id: "br-1968", category: "historical", name: "Flag of Brazil (1968–1992)", from: 1968, to: 1992, path: "national-flags/br/brazil-1968.svg", design: "23 stars — the celestial sphere as redrawn when Acre's star and Guanabara's were both carried.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    { id: "br-1960", category: "historical", name: "Flag of Brazil (1960–1968)", from: 1960, to: 1968, path: "historical-flags/brazil-1960.svg", design: "22 stars — Guanabara's admission as a state added the 22nd.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    { id: "br-1889-republic", category: "historical", name: "Flag of Brazil (1889–1960)", from: 1889, to: 1960, path: "historical-flags/brazil-1889.svg", design: "The first republican flag, with 21 stars, adopted 19 November 1889.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    { id: "br-1889-provisional", category: "historical", name: "Provisional flag of the Republic (15–19 November 1889)", from: 1889, to: 1889, path: "national-flags/br/brazil-1889-provisional.svg", design: "Thirteen green and yellow stripes with 21 white stars in a blue canton — flown for four days after the proclamation of the republic.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    { id: "br-empire", category: "historical", name: "Flag of the Empire of Brazil", from: 1822, to: 1889, path: "historical-flags/empire-of-brazil.png", design: "The imperial arms on a yellow rhombus on a green field; the arms were redrawn in 1853 as provinces were added.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    { id: "br-1822-kingdom", category: "historical", name: "Flag of the Kingdom of Brazil (1822)", from: 1822, to: 1822, path: "national-flags/br/brazil-1822-kingdom.svg", design: "The Prince Royal's personal standard with a royal, rather than imperial, crown — flown in the months between independence and the empire.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    { id: "br-army", category: "military", name: "Flag of the Brazilian Army", from: 1987, to: 9999, path: "national-flags/br/brazil-army.svg", design: "The coat of arms of the Brazilian Army on a white field.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    { id: "br-navy", category: "military", name: "Flag of the Brazilian Navy", from: 1982, to: 9999, path: "national-flags/br/brazil-navy.svg", design: "The coat of arms of the Brazilian Navy on a white field.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    { id: "br-air-force", category: "military", name: "Flag of the Aeronautics Command (Brazilian Air Force)", from: 1999, to: 9999, path: "national-flags/br/brazil-air-force.svg", design: "The arms of the Aeronautics Command on a sky-blue field crossed by a diagonal band.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    { id: "br-marines", category: "military", name: "Flag of the Brazilian Marine Corps", from: 1931, to: 9999, path: "national-flags/br/brazil-marines.svg", design: "The arms of the Corpo de Fuzileiros Navais — the navy's marine corps.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    { id: "br-jack", category: "maritime", name: "Naval jack (Bandeira do Cruzeiro)", from: 1847, to: 9999, path: "national-flags/br/brazil-naval-jack.svg", design: "Dark blue with 21 white stars in a cross — 13 across and 9 down.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    { id: "br-president", category: "standard", name: "Presidential Standard of Brazil", from: 1992, to: 9999, path: "national-flags/br/brazil-president.svg", design: "A dark green field with the national coat of arms in the centre.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    { id: "br-vice-president", category: "standard", name: "Vice-Presidential Standard of Brazil", from: 1992, to: 9999, path: "national-flags/br/brazil-vice-president.svg", design: "A yellow field with 21 blue stars in a cross and the coat of arms at the centre.", source: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
  ],
  "CN": [
    { id: "cn-1949", category: "historical", name: "Flag of the People's Republic of China", from: 1949, to: 9999, path: "flags/cn.svg", design: "A red field with one large gold star and four smaller stars in an arc, hoisted on 1 October 1949.", source: "https://en.wikipedia.org/wiki/List_of_Chinese_flags" },
    { id: "cn-roc-1928", category: "historical", name: "Flag of the Republic of China (1928–1949)", from: 1928, to: 1949, path: "national-flags/cn/china-roc-1928.svg", design: "The Blue Sky with a White Sun in the canton of a red field — the national flag of China from the Northern Expedition until 1949.", source: "https://en.wikipedia.org/wiki/List_of_Chinese_flags" },
    { id: "cn-roc-1912", category: "historical", name: "Flag of the Republic of China (1912–1928)", from: 1912, to: 1928, path: "national-flags/cn/china-roc-1912.svg", design: "The Five-Races-Under-One-Union flag: red, yellow, blue, white and black stripes for the Han, Manchu, Mongol, Hui and Tibetan peoples.", source: "https://en.wikipedia.org/wiki/List_of_Chinese_flags" },
    { id: "cn-qing", category: "historical", name: "Yellow Dragon Flag of the Qing dynasty", from: 1889, to: 1912, path: "historical-flags/qing-dynasty.png", design: "A rectangular yellow field with a blue dragon chasing a red pearl. The triangular version dates from 1862; before that China had no national flag.", source: "https://en.wikipedia.org/wiki/List_of_Chinese_flags" },
    { id: "cn-pla", category: "military", name: "Flag of the People's Liberation Army", from: 1948, to: 9999, path: "national-flags/cn/china-pla.svg", design: "A red field with a gold star and the characters 八一 for 1 August, the date of the 1927 Nanchang uprising.", source: "https://en.wikipedia.org/wiki/List_of_Chinese_flags" },
    { id: "cn-pla-ground", category: "military", name: "Ensign of the PLA Ground Force", from: 1992, to: 9999, path: "national-flags/cn/china-pla-ground.svg", design: "The PLA flag with a green stripe along the bottom.", source: "https://en.wikipedia.org/wiki/List_of_Chinese_flags" },
    { id: "cn-pla-navy", category: "military", name: "Ensign of the PLA Navy", from: 1992, to: 9999, path: "national-flags/cn/china-pla-navy.svg", design: "The PLA flag with blue and white stripes along the bottom.", source: "https://en.wikipedia.org/wiki/List_of_Chinese_flags" },
    { id: "cn-pla-air", category: "military", name: "Ensign of the PLA Air Force", path: "national-flags/cn/china-pla-air.svg", design: "The PLA flag with a sky-blue stripe along the bottom.", source: "https://en.wikipedia.org/wiki/List_of_Chinese_flags" },
    { id: "cn-pla-rocket", category: "military", name: "Ensign of the PLA Rocket Force", from: 2016, to: 9999, path: "national-flags/cn/china-pla-rocket.svg", design: "The PLA flag with a gold-and-blue stripe along the bottom.", source: "https://en.wikipedia.org/wiki/List_of_Chinese_flags" },
  ],
  "ES": [
    { id: "es-1981", category: "historical", name: "Flag of Spain", from: 1981, to: 9999, path: "flags/es.svg", design: "Red-yellow-red with the coat of arms toward the hoist, in the form fixed by the 1981 royal decree.", source: "https://en.wikipedia.org/wiki/List_of_Spanish_flags" },
    { id: "es-1977", category: "historical", name: "Flag of Spain (1977–1981)", from: 1977, to: 1981, path: "national-flags/es/spain-1977.svg", design: "The transition-era flag: the eagle of Saint John retained, with the wings raised.", source: "https://en.wikipedia.org/wiki/List_of_Spanish_flags" },
    { id: "es-1945", category: "historical", name: "Flag of Spain (1945–1977)", from: 1945, to: 1977, path: "historical-flags/spain-1945.svg", design: "Francoist Spain — red-yellow-red charged with the Eagle of Saint John in its 1945 arrangement.", source: "https://en.wikipedia.org/wiki/List_of_Spanish_flags" },
    { id: "es-1938", category: "historical", name: "Flag of Spain (1938–1945)", from: 1938, to: 1945, path: "national-flags/es/spain-1938.svg", design: "The first Francoist arms, with the eagle's wings spread wide.", source: "https://en.wikipedia.org/wiki/List_of_Spanish_flags" },
    { id: "es-1931", category: "historical", name: "Flag of the Second Spanish Republic", from: 1931, to: 1939, path: "national-flags/es/spain-1931.svg", design: "A horizontal tricolour of red, yellow and murrey with the republican arms.", source: "https://en.wikipedia.org/wiki/List_of_Spanish_flags" },
    { id: "es-1785", category: "historical", name: "Flag of Spain (1785–1931)", from: 1785, to: 1931, path: "historical-flags/spain-1785.png", design: "The red-yellow-red ensign chosen by Charles III in 1785 so Spanish ships could be told apart at sea, with the royal arms.", source: "https://en.wikipedia.org/wiki/List_of_Spanish_flags" },
    { id: "es-burgundy", category: "historical", name: "Cross of Burgundy", from: 1506, to: 1785, path: "historical-flags/spain-burgundy.png", design: "A red ragged saltire on white — the ensign of Habsburg and early Bourbon Spain.", source: "https://en.wikipedia.org/wiki/List_of_Spanish_flags" },
    { id: "es-naval-jack", category: "maritime", name: "Naval jack of Spain", from: 1939, to: 9999, path: "national-flags/es/spain-naval-jack.svg", design: "A square quartered with the arms of Castile, León, Aragón and Navarre.", source: "https://en.wikipedia.org/wiki/List_of_Spanish_flags" },
    { id: "es-yacht", category: "maritime", name: "Yacht ensign of Spain", from: 1977, to: 9999, path: "national-flags/es/spain-yacht-ensign.svg", design: "The national flag charged with a plain blue royal crown.", source: "https://en.wikipedia.org/wiki/List_of_Spanish_flags" },
    { id: "es-royal", category: "standard", name: "Standard of the King of Spain", from: 2014, to: 9999, path: "national-flags/es/spain-royal-standard.svg", design: "A crimson square bearing the arms of the sovereign.", source: "https://en.wikipedia.org/wiki/List_of_Spanish_flags" },
    { id: "es-civil", category: "civilstate", name: "Civil flag of Spain", from: 1981, to: 9999, path: "national-flags/es/spain-civil.svg", design: "The red-yellow-red bands without the coat of arms — the flag private citizens fly, alongside the state flag which bears the arms.", source: "https://en.wikipedia.org/wiki/List_of_Spanish_flags" },
  ],
  "FR": [
    { id: "fr-tricolore", category: "historical", name: "Flag of France (the Tricolore)", from: 1830, to: 9999, path: "flags/fr.svg", design: "Three vertical bands of blue, white and red. The darker navy of the original was restored in 2020, after a lighter version had been used since 1976.", source: "https://en.wikipedia.org/wiki/List_of_French_flags" },
    { id: "fr-bourbon", category: "historical", name: "Royal flag of the House of Bourbon", from: 1590, to: 1830, path: "historical-flags/france-bourbon.png", design: "A plain white field strewn with gold fleurs-de-lis. Not flown between 1790 and 1814, when the Revolution and the First Empire intervened.", source: "https://en.wikipedia.org/wiki/List_of_French_flags" },
    { id: "fr-royal-banner", category: "historical", name: "Royal banner of France", from: 1376, to: 1792, path: "historical-flags/france-royal-banner.svg", design: "Azure with three gold fleurs-de-lis — \"France moderne\", after Charles V reduced the strewn field to three flowers in 1376.", source: "https://en.wikipedia.org/wiki/List_of_French_flags" },
    { id: "fr-naval-ensign", category: "maritime", name: "Naval ensign of France", from: 1853, to: 9999, path: "national-flags/fr/france-naval-ensign.svg", design: "The Tricolore in the navy's own proportions, with the three bands of unequal width so they appear equal when flying.", source: "https://en.wikipedia.org/wiki/List_of_French_flags" },
  ],
  "GB": [
    { id: "gb-1801", category: "historical", name: "Union Flag", from: 1801, to: 9999, path: "flags/gb.svg", design: "The crosses of St George, St Andrew and St Patrick combined — the design adopted when Ireland joined the union on 1 January 1801.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
    { id: "gb-1707", category: "historical", name: "Flag of the Kingdom of Great Britain", from: 1707, to: 1801, path: "national-flags/gb/great-britain-1707.svg", design: "The first Union Flag: St George's cross over St Andrew's saltire, without the Irish saltire.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
    { id: "gb-protectorate", category: "historical", name: "Flag of the Protectorate", from: 1658, to: 1660, path: "national-flags/gb/protectorate-1658.svg", design: "The 1606 Union Flag defaced with an Irish harp, flown under Oliver Cromwell.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
    { id: "gb-commonwealth-1651", category: "historical", name: "Flag of the Commonwealth of England", from: 1651, to: 1658, path: "national-flags/gb/commonwealth-1651.svg", design: "St George's cross quartered with St Andrew's cross and an Irish harp.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
    { id: "gb-commonwealth-1649", category: "historical", name: "Flag of the Commonwealth of England", from: 1649, to: 1651, path: "national-flags/gb/commonwealth-1649.svg", design: "St George's cross joined with an Irish harp, adopted after the execution of Charles I.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
    { id: "gb-army", category: "military", name: "Non-ceremonial flag of the British Army", path: "national-flags/gb/uk-army.svg", design: "A red field bearing the badge of the British Army.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
    { id: "gb-raf", category: "military", name: "Royal Air Force Ensign", from: 1921, to: 9999, path: "national-flags/gb/uk-raf.svg", design: "An Air-Force-blue field with the Union Flag in the canton and the RAF roundel in the fly.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
    { id: "gb-white-ensign", category: "military", name: "White Ensign", from: 1801, to: 9999, path: "national-flags/gb/uk-white-ensign.svg", design: "A white field with St George's cross and the Union Flag in the canton — flown by ships of the Royal Navy.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
    { id: "gb-red-ensign", category: "maritime", name: "Red Ensign", from: 1801, to: 9999, path: "national-flags/gb/uk-red-ensign.svg", design: "A red field with the Union Flag in the canton — the flag of the British merchant fleet.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
    { id: "gb-blue-ensign", category: "maritime", name: "Blue Ensign", from: 1801, to: 9999, path: "national-flags/gb/uk-blue-ensign.svg", design: "A blue field with the Union Flag in the canton, flown by government vessels and by organisations warranted to use it.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
    { id: "gb-civil-jack", category: "maritime", name: "Civil Jack", from: 1801, to: 9999, path: "national-flags/gb/uk-civil-jack.svg", design: "The Union Flag within a white border, flown as a jack by British merchant ships.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
    { id: "gb-royal-standard", category: "standard", name: "Royal Standard of the United Kingdom", from: 1837, to: 9999, path: "national-flags/gb/uk-royal-standard.svg", design: "A banner of the royal arms: the three lions of England quartered with the lion of Scotland and the harp of Ireland.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
    { id: "gb-royal-standard-scotland", category: "standard", name: "Royal Standard of the United Kingdom in Scotland", from: 1837, to: 9999, path: "national-flags/gb/uk-royal-standard-scotland.svg", design: "The royal arms in their Scottish form, with the lion rampant taking precedence.", source: "https://en.wikipedia.org/wiki/List_of_United_Kingdom_flags" },
  ],
  "IN": [
    { id: "in-1947", category: "historical", name: "Flag of India (Tiranga)", from: 1947, to: 9999, path: "flags/in.svg", design: "A horizontal tricolour of saffron, white and green with the navy-blue Ashoka Chakra of 24 spokes at the centre; adopted 22 July 1947.", source: "https://en.wikipedia.org/wiki/List_of_Indian_flags" },
    { id: "in-armed-forces", category: "military", name: "Flag of the Indian Armed Forces", path: "national-flags/in/india-armed-forces.svg", design: "A horizontal tricolour of red, navy blue and sky blue — one colour for each service — with the tri-service crest.", source: "https://en.wikipedia.org/wiki/List_of_Indian_flags" },
    { id: "in-naval-ensign", category: "maritime", name: "Indian Naval Ensign", from: 2022, to: 9999, path: "national-flags/in/india-naval-ensign.svg", design: "A white field with the national flag in the canton and the navy's octagonal crest in the fly, adopted in 2022.", source: "https://en.wikipedia.org/wiki/List_of_Indian_flags" },
    { id: "in-civil-ensign", category: "maritime", name: "Civil ensign of India", path: "national-flags/in/india-civil-ensign.svg", design: "A Red Ensign with the national flag in the canton, flown by Indian merchant ships.", source: "https://en.wikipedia.org/wiki/List_of_Indian_flags" },
    { id: "in-state-ensign", category: "maritime", name: "State ensign of India", path: "national-flags/in/india-state-ensign.svg", design: "A Blue Ensign with the national flag in the canton and a yellow anchor.", source: "https://en.wikipedia.org/wiki/List_of_Indian_flags" },
    { id: "in-president-1950", category: "standard", name: "Presidential Standard of India (1950–1971)", from: 1950, to: 1971, path: "national-flags/in/india-president-1950.svg", design: "Quartered dark blue: the Lions of Sarnath, an elephant, a pair of scales and a lotus vase — discontinued in 1971 in favour of the national flag.", source: "https://en.wikipedia.org/wiki/List_of_Indian_flags" },
  ],
  "JP": [
    { id: "jp-1999", category: "historical", name: "Flag of Japan (Hinomaru)", from: 1999, to: 9999, path: "flags/jp.svg", design: "A crimson disc centred on white, at 2:3 — the proportions and placement fixed by the Act on National Flag and Anthem of 13 August 1999.", source: "https://en.wikipedia.org/wiki/List_of_Japanese_flags" },
    { id: "jp-1870", category: "historical", name: "Flag of Japan (1870–1999)", from: 1870, to: 1999, path: "historical-flags/japan-1870.svg", design: "The Meiji Hinomaru of Proclamation 57 of 1870: 7:10, with the disc set slightly toward the hoist.", source: "https://en.wikipedia.org/wiki/List_of_Japanese_flags" },
    { id: "jp-shogunate", category: "historical", name: "Naval ensign of the Tokugawa shogunate", from: 1603, to: 1868, path: "historical-flags/japan-shogunate.png", design: "The naka-guro — a white field with a broad black horizontal band.", source: "https://en.wikipedia.org/wiki/List_of_Japanese_flags" },
    { id: "jp-jsdf", category: "military", name: "Flag of the Japan Self-Defense Forces", from: 1954, to: 9999, path: "national-flags/jp/japan-jsdf.svg", design: "A sun disc with eight red rays, used by the Self-Defense Forces and the Ground Self-Defense Force.", source: "https://en.wikipedia.org/wiki/List_of_Japanese_flags" },
    { id: "jp-jmsdf", category: "military", name: "Ensign of the Japan Maritime Self-Defense Force", path: "national-flags/jp/japan-jmsdf.svg", design: "The rising-sun ensign: a sun disc offset toward the hoist with sixteen rays.", source: "https://en.wikipedia.org/wiki/List_of_Japanese_flags" },
    { id: "jp-ijn", category: "military", name: "Ensign of the Imperial Japanese Navy", from: 1889, to: 1945, path: "national-flags/jp/japan-ijn.svg", design: "The same sixteen-ray rising sun, flown by the navy of the Empire of Japan.", source: "https://en.wikipedia.org/wiki/List_of_Japanese_flags" },
    { id: "jp-emperor", category: "standard", name: "Imperial Standard of the Emperor of Japan", from: 1869, to: 9999, path: "national-flags/jp/japan-emperor.svg", design: "A gold sixteen-petal chrysanthemum centred on red.", source: "https://en.wikipedia.org/wiki/List_of_Japanese_flags" },
  ],
  "MY": [
    { id: "my-1963", category: "historical", name: "Flag of Malaysia (Jalur Gemilang)", from: 1963, to: 9999, path: "flags/my.svg", design: "Fourteen red and white stripes with a blue canton bearing a crescent and a fourteen-point star.", source: "https://en.wikipedia.org/wiki/List_of_Malaysian_flags" },
    { id: "my-malaya", category: "historical", name: "Flag of the Federation of Malaya", from: 1950, to: 1963, path: "national-flags/my/malaya-1950.svg", design: "Eleven red and white stripes with a crescent and an eleven-point star — one for each state of the Federation.", source: "https://en.wikipedia.org/wiki/List_of_Malaysian_flags" },
    { id: "my-navy", category: "maritime", name: "Naval ensign of the Royal Malaysian Navy", from: 1968, to: 9999, path: "national-flags/my/malaysia-navy-ensign.svg", design: "A white field with blue crosses and the national flag in the canton.", source: "https://en.wikipedia.org/wiki/List_of_Malaysian_flags" },
    { id: "my-navy-1963", category: "maritime", name: "Naval ensign of the Royal Malaysian Navy (1963–1968)", from: 1963, to: 1968, path: "national-flags/my/malaysia-navy-ensign-1963.svg", design: "St George's Cross on a white field with the national flag in the canton.", source: "https://en.wikipedia.org/wiki/List_of_Malaysian_flags" },
    { id: "my-coast-guard", category: "maritime", name: "Ensign of the Malaysian Maritime Enforcement Agency", from: 2005, to: 9999, path: "national-flags/my/malaysia-coast-guard.svg", design: "A blue field bearing the agency's crest, with the national flag in the canton.", source: "https://en.wikipedia.org/wiki/List_of_Malaysian_flags" },
    { id: "my-agong", category: "standard", name: "Standard of the Yang di-Pertuan Agong", from: 1988, to: 9999, path: "national-flags/my/malaysia-agong.svg", design: "The royal standard of Malaysia's elected king.", source: "https://en.wikipedia.org/wiki/List_of_Malaysian_flags" },
  ],
  "TR": [
    { id: "tr-1936", category: "historical", name: "Flag of Turkey", from: 1936, to: 9999, path: "flags/tr.svg", design: "A white star and crescent on red, in the proportions fixed by the Turkish Flag Law of 1936.", source: "https://en.wikipedia.org/wiki/List_of_Turkish_flags" },
    { id: "tr-ottoman", category: "historical", name: "Flag of the Ottoman Empire", from: 1844, to: 1922, path: "historical-flags/ottoman-empire.png", design: "Red with a white crescent and five-pointed star, as fixed by the Tanzimat regulation of 1844.", source: "https://en.wikipedia.org/wiki/List_of_Turkish_flags" },
    { id: "tr-president", category: "standard", name: "Presidential Standard of Turkey", from: 1923, to: 9999, path: "national-flags/tr/turkey-president.svg", design: "The national flag with a golden sun of sixteen rays in the canton, one ray for each of the historic Turkic states.", source: "https://en.wikipedia.org/wiki/List_of_Turkish_flags" },
    { id: "tr-gnat", category: "standard", name: "Flag of the Grand National Assembly of Turkey", path: "national-flags/tr/turkey-gnat.svg", design: "A white field bearing the assembly's seal.", source: "https://en.wikipedia.org/wiki/List_of_Turkish_flags" },
  ],
  "US": [
    { id: "us-1960", category: "historical", name: "Flag of the United States", from: 1960, to: 9999, path: "flags/us.svg", design: "Fifty stars — Hawaii's admission completed the present design.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1959", category: "historical", name: "Flag of the United States (1959–1960)", from: 1959, to: 1960, path: "national-flags/us/us-1959.svg", design: "49 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1912", category: "historical", name: "Flag of the United States (1912–1959)", from: 1912, to: 1959, path: "national-flags/us/us-1912.svg", design: "48 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1908", category: "historical", name: "Flag of the United States (1908–1912)", from: 1908, to: 1912, path: "national-flags/us/us-1908.svg", design: "46 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1896", category: "historical", name: "Flag of the United States (1896–1908)", from: 1896, to: 1908, path: "national-flags/us/us-1896.svg", design: "45 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1891", category: "historical", name: "Flag of the United States (1891–1896)", from: 1891, to: 1896, path: "national-flags/us/us-1891.svg", design: "44 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1890", category: "historical", name: "Flag of the United States (1890–1891)", from: 1890, to: 1891, path: "national-flags/us/us-1890.svg", design: "43 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1877", category: "historical", name: "Flag of the United States (1877–1890)", from: 1877, to: 1890, path: "national-flags/us/us-1877.svg", design: "38 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1867", category: "historical", name: "Flag of the United States (1867–1877)", from: 1867, to: 1877, path: "national-flags/us/us-1867.svg", design: "37 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1865", category: "historical", name: "Flag of the United States (1865–1867)", from: 1865, to: 1867, path: "national-flags/us/us-1865.svg", design: "36 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1863", category: "historical", name: "Flag of the United States (1863–1865)", from: 1863, to: 1865, path: "national-flags/us/us-1863.svg", design: "35 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1861", category: "historical", name: "Flag of the United States (1861–1863)", from: 1861, to: 1863, path: "national-flags/us/us-1861.svg", design: "34 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1859", category: "historical", name: "Flag of the United States (1859–1861)", from: 1859, to: 1861, path: "national-flags/us/us-1859.svg", design: "33 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1858", category: "historical", name: "Flag of the United States (1858–1859)", from: 1858, to: 1859, path: "national-flags/us/us-1858.svg", design: "32 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1851", category: "historical", name: "Flag of the United States (1851–1858)", from: 1851, to: 1858, path: "national-flags/us/us-1851.svg", design: "31 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1848", category: "historical", name: "Flag of the United States (1848–1851)", from: 1848, to: 1851, path: "national-flags/us/us-1848.svg", design: "30 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1847", category: "historical", name: "Flag of the United States (1847–1848)", from: 1847, to: 1848, path: "national-flags/us/us-1847.svg", design: "29 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1846", category: "historical", name: "Flag of the United States (1846–1847)", from: 1846, to: 1847, path: "national-flags/us/us-1846.svg", design: "28 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1845", category: "historical", name: "Flag of the United States (1845–1846)", from: 1845, to: 1846, path: "national-flags/us/us-1845.svg", design: "27 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1837", category: "historical", name: "Flag of the United States (1837–1845)", from: 1837, to: 1845, path: "national-flags/us/us-1837.svg", design: "26 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1836", category: "historical", name: "Flag of the United States (1836–1837)", from: 1836, to: 1837, path: "national-flags/us/us-1836.svg", design: "25 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1822", category: "historical", name: "Flag of the United States (1822–1836)", from: 1822, to: 1836, path: "national-flags/us/us-1822.svg", design: "24 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1820", category: "historical", name: "Flag of the United States (1820–1822)", from: 1820, to: 1822, path: "national-flags/us/us-1820.svg", design: "23 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1819", category: "historical", name: "Flag of the United States (1819–1820)", from: 1819, to: 1820, path: "national-flags/us/us-1819.svg", design: "21 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1818", category: "historical", name: "Flag of the United States (1818–1819)", from: 1818, to: 1819, path: "national-flags/us/us-1818.svg", design: "20 stars — the stripes returned to thirteen in 1818, and from then a star was added on the 4th of July following each new state's admission.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1795", category: "historical", name: "Flag of the United States (1795–1818)", from: 1795, to: 1818, path: "national-flags/us/us-1795.svg", design: "Fifteen stars AND fifteen stripes, for Vermont and Kentucky — the only US flag ever to carry more than thirteen stripes, and the one that flew over Fort McHenry.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1777", category: "historical", name: "Flag of the United States (1777–1795)", from: 1777, to: 1795, path: "national-flags/us/us-1777.svg", design: "Thirteen stars and thirteen stripes, as fixed by the Flag Resolution of 1777. The star arrangement was not specified, so several patterns were used.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-1775", category: "historical", name: "Continental Union Flag", from: 1775, to: 1777, path: "national-flags/us/us-1775.svg", design: "Thirteen stripes with the British Union Flag in the canton — flown before the Stars and Stripes.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-army", category: "military", name: "Flag of the United States Army", path: "national-flags/us/us-army.svg", design: "The Army's war office seal in blue on white, with a scarlet scroll bearing the Army's name and the year 1775.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-navy", category: "military", name: "Flag of the United States Navy", path: "national-flags/us/us-navy.svg", design: "The Navy's seal on a dark blue field, with a yellow scroll reading UNITED STATES NAVY.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-marines", category: "military", name: "Flag of the United States Marine Corps", path: "national-flags/us/us-marines.svg", design: "The Marine Corps emblem — eagle, globe and anchor — on a scarlet field.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-air-force", category: "military", name: "Flag of the United States Air Force", path: "national-flags/us/us-air-force.svg", design: "The Air Force coat of arms and thirteen white stars on an ultramarine field.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-space-force", category: "military", name: "Flag of the United States Space Force", path: "national-flags/us/us-space-force.svg", design: "The Space Force delta emblem on a dark blue field.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-coast-guard", category: "military", name: "Flag of the United States Coast Guard", path: "national-flags/us/us-coast-guard.svg", design: "The Coast Guard's seal on white, with the service's name and its founding year.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-coast-guard-ensign", category: "maritime", name: "Ensign of the United States Coast Guard", path: "national-flags/us/us-coast-guard-ensign.svg", design: "Sixteen vertical red and white stripes with the Coast Guard emblem — flown to signal a vessel's authority to enforce federal law.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-jack", category: "maritime", name: "Union Jack of the United States", path: "national-flags/us/us-jack.svg", design: "The canton of the national flag flown alone at the bow: fifty white stars on blue.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-yacht-ensign", category: "maritime", name: "Yacht ensign of the United States", path: "national-flags/us/us-yacht-ensign.svg", design: "Thirteen stripes with a fouled anchor in a ring of thirteen stars, flown by recreational vessels.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-president", category: "standard", name: "Flag of the President of the United States", path: "national-flags/us/us-president.svg", design: "The presidential coat of arms encircled by fifty stars on a dark blue field.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
    { id: "us-vice-president", category: "standard", name: "Flag of the Vice President of the United States", path: "national-flags/us/us-vice-president.svg", design: "The vice-presidential coat of arms with four blue stars on white.", source: "https://en.wikipedia.org/wiki/List_of_flags_of_the_United_States" },
  ],
  "ZA": [
    { id: "za-1994", category: "historical", name: "Flag of South Africa", from: 1994, to: 9999, path: "flags/za.svg", design: "A horizontal Y in green, fimbriated white and gold, separating red and blue from a black triangle at the hoist.", source: "https://en.wikipedia.org/wiki/List_of_South_African_flags" },
    { id: "za-1982", category: "historical", name: "Flag of South Africa (1982–1994)", from: 1982, to: 1994, path: "national-flags/za/south-africa-1982.svg", design: "The orange-white-blue \"Oranje-Blanje-Blou\" with the three small flags at its centre, in the lighter shades specified in 1982.", source: "https://en.wikipedia.org/wiki/List_of_South_African_flags" },
    { id: "za-1928", category: "historical", name: "Flag of the Union of South Africa", from: 1928, to: 1982, path: "national-flags/za/south-africa-1928.svg", design: "Orange, white and blue, with the Union Flag, the Orange Free State flag and the Transvaal flag together in the centre.", source: "https://en.wikipedia.org/wiki/List_of_South_African_flags" },
    { id: "za-sandf", category: "military", name: "Flag of the South African National Defence Force", from: 2003, to: 9999, path: "national-flags/za/south-africa-sandf.svg", design: "The Defence Force's emblem on a field bearing the colours of the national flag.", source: "https://en.wikipedia.org/wiki/List_of_South_African_flags" },
    { id: "za-sandf-1994", category: "military", name: "Ensign of the South African National Defence Force (1994–2003)", from: 1994, to: 2003, path: "national-flags/za/south-africa-sandf-1994.svg", design: "The first post-apartheid defence-force ensign, replaced in 2003.", source: "https://en.wikipedia.org/wiki/List_of_South_African_flags" },
  ],
};

/**
 * Sourced "What this flag means" explainers, keyed by NationalFlag.id, passed to
 * the shared `FlagMeaning` component via its `meanings` prop — the same discipline
 * and shape as FLAG_MEANINGS / CITY_FLAG_MEANINGS. Coverage grows incrementally: a
 * flag with no entry simply renders no disclosure rather than a guessed one.
 */
export const NATIONAL_FLAG_MEANINGS: Record<string, FlagMeaning> = {
  "au-aboriginal": {
    description: "Harold Thomas designed the flag in 1971 for the land-rights movement and gave each element a meaning: the black upper half represents the Aboriginal people of Australia, the red lower half the red earth and the ochre used in ceremony, and the yellow disc the sun, the giver of life. It was proclaimed a Flag of Australia in July 1995, and in January 2022 the Commonwealth acquired the copyright so that it can be reproduced freely.",
    sources: [
      { title: "Australian Aboriginal Flag — Wikipedia", url: "https://en.wikipedia.org/wiki/Australian_Aboriginal_Flag" },
      { title: "Australian flags — Department of the Prime Minister and Cabinet", url: "https://www.pmc.gov.au/government/australian-national-symbols/australian-flags" },
    ],
  },
  "bo-wiphala": {
    description: "The Wiphala of the Qullasuyu is recognised by Article 6 of Bolivia's 2009 constitution as a dual national symbol alongside the tricolour — the state's acknowledgement that it is plurinational. Its 49 squares are arranged so that the seven colours run diagonally, and it stands for the Andean indigenous peoples of the region the Inca called Qullasuyu.",
    sources: [
      { title: "Wiphala — Wikipedia", url: "https://en.wikipedia.org/wiki/Wiphala" },
      { title: "List of Bolivian flags — Wikipedia", url: "https://en.wikipedia.org/wiki/List_of_Bolivian_flags" },
    ],
  },
  "br-1889-provisional": {
    description: "Raised on 15 November 1889, the day the republic was proclaimed, this flag closely copied the flag of the United States — thirteen stripes and a starred canton — as a deliberate statement that Brazil was now a federal republic on the American model. Deodoro da Fonseca rejected it four days later precisely because it imitated another nation's flag, and the green-and-yellow field of the imperial flag was kept instead, so that the change of regime did not read as a change of country.",
    sources: [
      { title: "Flag of Brazil — Wikipedia", url: "https://en.wikipedia.org/wiki/Flag_of_Brazil" },
    ],
  },
  "br-jack": {
    description: "The jack flown at the bow of Brazilian warships shows the Southern Cross constellation, from which the flag takes its name, and 21 stars for the provinces of the empire at the time it was adopted in 1847. It is the oldest Brazilian flag still in use, having survived both the fall of the empire and every redrawing of the national flag's star field.",
    sources: [
      { title: "List of Brazilian flags — Wikipedia", url: "https://en.wikipedia.org/wiki/List_of_Brazilian_flags" },
    ],
  },
  "gb-1801": {
    description: "The Union Flag layers three patron saints' crosses in the order the kingdoms joined: England's red cross of St George on white, Scotland's white saltire of St Andrew on blue (joined at the union of the crowns in 1606) and the red saltire of St Patrick for Ireland, added when the Kingdom of Ireland joined the union in 1801. St Patrick's saltire is set counterchanged — offset from the centre of the white Scottish saltire — so that neither saltire appears to take precedence over the other, which is why the flag is not symmetrical and can be flown upside down.",
    sources: [
      { title: "Union Jack — Wikipedia", url: "https://en.wikipedia.org/wiki/Union_Jack" },
    ],
  },
  "za-1994": {
    description: "Designed by State Herald Frederick Brownell and first flown on 27 April 1994, the day of the first democratic election, the flag was drawn to carry no per-colour symbolism at all — the only South African national flag whose design has no official meaning attached to its colours. What the design does say is said by its shape: the horizontal Y, or pall, shows two paths converging into one, which the government describes as the convergence of diverse elements within South African society taking the road ahead in unity.",
    sources: [
      { title: "Flag of South Africa — Wikipedia", url: "https://en.wikipedia.org/wiki/Flag_of_South_Africa" },
      { title: "National flag — South African Government", url: "https://www.gov.za/about-sa/national-symbols/national-flag" },
    ],
  },
};
