// Auto-generated by scripts/build-shared-capital-flags.mjs — DO NOT EDIT MANUALLY
// Subdivision codes whose bundled capital-city flag is visually the SAME image
// as the subdivision's own flag (byte-identical, or perceptual difference-hash
// distance < 12 — the near-identical-duplicate threshold calibrated in
// scripts/check-parent-flag-collision.mjs). A mixed division+capital game deck
// asks such a flag only once. Re-run: node scripts/build-shared-capital-flags.mjs

/** Codes whose capital flag duplicates the subdivision flag. */
export const SHARED_CAPITAL_FLAGS: ReadonlySet<string> = new Set([
  "AE-AJ", // byte-identical
  "AE-AZ", // perceptual distance 0
  "AE-DU", // byte-identical
  "AE-SH", // byte-identical
  "AE-UQ", // byte-identical
  "AU-NF", // perceptual distance 0
  "BO-C", // byte-identical
  "BO-H", // perceptual distance 0
  "BO-O", // perceptual distance 0
  "BO-S", // byte-identical
  "BO-T", // byte-identical
  "CH-BS", // byte-identical
  "CH-LU", // perceptual distance 0
  "CH-SO", // perceptual distance 0
  "CH-ZG", // perceptual distance 0
  "CH-ZH", // perceptual distance 0
  "CR-P", // byte-identical
  "CU-11", // byte-identical
  "CV-PR", // byte-identical
  "DE-HB", // byte-identical
  "EC-A", // perceptual distance 0
  "EG-ALX", // byte-identical
  "EG-ASN", // byte-identical
  "EG-BH", // byte-identical
  "EG-DT", // byte-identical
  "EG-GZ", // perceptual distance 5
  "EG-KB", // perceptual distance 0
  "EG-KFS", // byte-identical
  "EG-LX", // perceptual distance 0
  "EG-SHG", // perceptual distance 0
  "EG-SUZ", // byte-identical
  "ES-CE", // perceptual distance 0
  "ES-ZA", // byte-identical
  "ET-HA", // byte-identical
  "GB-GI", // perceptual distance 0
  "HN-SB", // byte-identical
  "IT-AN", // byte-identical
  "IT-BG", // perceptual distance 0
  "IT-CO", // byte-identical
  "IT-CT", // byte-identical
  "IT-PT", // byte-identical
  "KG-O", // byte-identical
  "LV-050", // byte-identical
  "ME-06", // byte-identical
  "ME-11", // perceptual distance 0
  "ME-13", // perceptual distance 0
  "ME-15", // byte-identical
  "ME-16", // byte-identical
  "ME-17", // byte-identical
  "ME-18", // byte-identical
  "ME-19", // byte-identical
  "ME-20", // perceptual distance 0
  "MU-PL", // byte-identical
  "MY-14", // byte-identical
  "NG-FC", // byte-identical
  "NI-BO", // byte-identical
  "NI-CA", // byte-identical
  "NI-CI", // byte-identical
  "NI-ES", // byte-identical
  "NI-LE", // perceptual distance 1
  "NI-MD", // byte-identical
  "PE-AYA", // perceptual distance 0
  "PE-CUS", // byte-identical
  "PE-MDD", // byte-identical
  "PE-MOQ", // byte-identical
  "PE-TUM", // byte-identical
  "SI-030", // byte-identical
  "SI-032", // byte-identical
  "SI-034", // byte-identical
  "SI-099", // byte-identical
  "SI-104", // byte-identical
  "SI-106", // byte-identical
  "SI-147", // byte-identical
  "SV-AH", // perceptual distance 8
  "SV-CH", // byte-identical
  "SV-SM", // perceptual distance 0
  "SV-SV", // byte-identical
  "UY-RV", // perceptual distance 9
  "VE-X", // byte-identical
]);
