// Auto-generated by scripts/build-shared-capital-flags.mjs — DO NOT EDIT MANUALLY
// Subdivision codes whose bundled capital-city flag is visually the SAME image
// as the subdivision's own flag (byte-identical, or perceptual difference-hash
// distance < 12 — the near-identical-duplicate threshold calibrated in
// scripts/check-parent-flag-collision.mjs), PLUS a curated set of pairs that are
// the same flag from two sources but render too far apart for the perceptual
// pass to catch (confirmed by a side-by-side montage audit — see
// EFFECTIVELY_SHARED in the generator). A mixed division+capital game deck asks
// such a flag only once. Re-run: node scripts/build-shared-capital-flags.mjs

/** Codes whose capital flag duplicates the subdivision flag. */
export const SHARED_CAPITAL_FLAGS: ReadonlySet<string> = new Set([
  "AE-AJ", // byte-identical
  "AE-AZ", // perceptual distance 0
  "AE-DU", // byte-identical
  "AE-SH", // byte-identical
  "AE-UQ", // byte-identical
  "AU-NF", // perceptual distance 0
  "BO-C", // byte-identical
  "BO-H", // perceptual distance 0
  "BO-L", // curated (audit): La Paz department ≡ city (red-over-green bicolour); shades differ (dHash 27)
  "BO-O", // perceptual distance 0
  "BO-S", // byte-identical
  "BO-T", // byte-identical
  "BR-DF", // curated (audit): Distrito Federal ≡ Brasília (golden-arrow cross); shade/crop differ
  "CH-BS", // byte-identical
  "CH-LU", // perceptual distance 0
  "CH-SO", // perceptual distance 0
  "CH-SZ", // curated (audit): Schwyz canton ≡ town (red field, white canton cross)
  "CH-ZG", // perceptual distance 0
  "CH-ZH", // perceptual distance 0
  "CN-HK", // byte-identical
  "CN-MO", // byte-identical
  "CR-A", // curated (audit): Alajuela province ≡ city (arms + wreath on white)
  "CR-C", // curated (audit): Cartago province ≡ city (red-over-blue bicolour)
  "CR-P", // byte-identical
  "CV-PR", // byte-identical
  "DE-HB", // byte-identical
  "EC-A", // perceptual distance 0
  "EC-E", // curated (audit): Esmeraldas province ≡ capital (green/white bicolour)
  "EC-G", // curated (audit): Guayas ≡ Guayaquil (pale blue/white bands, three stars)
  "EC-T", // curated (audit): Tungurahua ≡ Ambato (red/green field)
  "EG-ALX", // byte-identical
  "EG-ASN", // byte-identical
  "EG-BH", // byte-identical
  "EG-DT", // byte-identical
  "EG-GZ", // byte-identical
  "EG-KB", // byte-identical
  "EG-KFS", // byte-identical
  "EG-LX", // byte-identical
  "EG-PTS", // curated (audit): Port Said governorate ≡ city (red field + anchor & wreath)
  "EG-SHG", // byte-identical
  "EG-SUZ", // byte-identical
  "ES-CE", // perceptual distance 0
  "ES-OR", // curated (audit): Ourense province ≡ city (blue field, arms + star border)
  "ET-HA", // byte-identical
  "GB-GI", // perceptual distance 0
  "HN-FM", // curated (audit): Francisco Morazán ≡ Tegucigalpa (navy/gold + arms)
  "HN-OC", // curated (audit): Ocotepeque dept ≡ capital (red/white/green triband)
  "HN-SB", // byte-identical
  "KG-O", // byte-identical
  "LV-050", // byte-identical
  "LV-056", // curated (audit): Līvāni municipality ≡ town (light-blue field + emblem)
  "ME-06", // byte-identical
  "ME-08", // curated (audit): Herceg Novi ≡ town (ornate blue cross emblem)
  "ME-11", // byte-identical
  "ME-13", // perceptual distance 0
  "ME-14", // curated (audit): Pljevlja ≡ town (blue field + shield)
  "ME-15", // byte-identical
  "ME-16", // byte-identical
  "ME-17", // byte-identical
  "ME-18", // byte-identical
  "ME-19", // byte-identical
  "ME-20", // perceptual distance 0
  "MM-04", // curated (audit): Mandalay Region ≡ capital (blue field + regional seal)
  "MM-06", // curated (audit): Bago Region ≡ capital (green/yellow/red + gear seal)
  "MU-PL", // byte-identical
  "MX-ZAC", // curated (audit): Zacatecas state ≡ city (coat of arms on white)
  "MY-14", // byte-identical
  "MY-16", // perceptual distance 0
  "NI-AN", // curated (audit): Nicaragua dept ≡ capital (shared departmental banner)
  "PA-3", // perceptual distance 0
  "PE-ARE", // perceptual distance 2
  "PE-AYA", // perceptual distance 0
  "PE-CAJ", // perceptual distance 5
  "PE-CUS", // byte-identical
  "PE-HUC", // curated (audit): Huánuco dept ≡ city (white/green diagonal)
  "PE-HUV", // curated (audit): Huancavelica dept ≡ city (light-blue field + arms)
  "PE-MDD", // byte-identical
  "PE-MOQ", // byte-identical
  "PE-TAC", // perceptual distance 0
  "PE-TUM", // byte-identical
  "PW-212", // curated (audit): Koror state ≡ capital (red/blue starburst + emblem)
  "SI-030", // byte-identical
  "SI-032", // byte-identical
  "SI-034", // byte-identical
  "SI-043", // byte-identical
  "SI-099", // byte-identical
  "SI-104", // byte-identical
  "SI-106", // byte-identical
  "SI-147", // byte-identical
  "SV-AH", // curated (audit): Ahuachapán dept ≡ capital (blue/white/blue + arms)
  "SV-CH", // byte-identical
  "SV-SM", // byte-identical
  "SV-SV", // byte-identical
  "SV-UN", // curated (audit): La Unión dept ≡ capital (yellow/red + emblem)
  "UY-RV", // byte-identical
  "UY-SA", // perceptual distance 0
  "VE-T", // curated (audit): Táchira ≡ capital (white triangle + star)
  "VE-X", // byte-identical
]);
