/* Auto-generated by scripts/build-wvs-results.mjs — do not edit. */
export const WVS_RESULTS_SOURCE = {
  "path": "data/wvs/wave7/wave-results/F00010763-WVS_Results_By_Country_2017-2022_v6.0.0.pdf",
  "sha256": "577596a3cd6a3b3ad4e63fee4dfc07aff7bf0867916a52b4ed9caf095bb695db",
  "bytes": 22443406,
  "wave": 7,
  "wave_years_label": "2017-2022",
  "publisher": "World Values Survey Association",
  "documentation_url": "https://www.worldvaluessurvey.org/WVSDocumentationWV7.jsp",
  "joint_evs_wvs_path": "data/wvs/joint-evs-wvs-2017-2022/F00011082-EVS_WVS_Joint_v5_Results_by_Country.pdf",
  "france_questions_merged": 51,
  "retrieved_note": "Wave 7 percentages from the official Results By Country PDF (weighted by w_weight). France never fielded WVS Wave 7 — its figures are merged from the Joint EVS/WVS 2017–2022 Results by Country PDF, matched by shared short title, fieldwork year 2018. Wave 5 France is superseded and not used."
} as const;

export const WVS_THEME_ORDER = [
  "important-in-life",
  "child-qualities",
  "neighbors",
  "trust",
  "confidence",
  "democracy",
  "politics",
  "religion",
  "morals",
  "security",
  "migration",
  "economy",
  "science",
  "corruption",
  "happiness",
  "gender",
  "media",
  "other"
] as const;

export type WvsThemeId = (typeof WVS_THEME_ORDER)[number];
