/* Auto-generated by scripts/build-wvs-results.mjs — do not edit. */
export const WVS_RESULTS_SOURCE = {
  "path": "data/wvs/wave7/wave-results/F00010763-WVS_Results_By_Country_2017-2022_v6.0.0.pdf",
  "sha256": "577596a3cd6a3b3ad4e63fee4dfc07aff7bf0867916a52b4ed9caf095bb695db",
  "bytes": 22443406,
  "wave": 7,
  "wave_years_label": "2017-2022",
  "publisher": "World Values Survey Association",
  "documentation_url": "https://www.worldvaluessurvey.org/WVSDocumentationWV7.jsp",
  "joint_evs_wvs_path": "data/wvs/joint-evs-wvs-2017-2022/F00011082-EVS_WVS_Joint_v5_Results_by_Country.pdf",
  "france_questions_merged": 140,
  "joint_evs_societies": [
    "AL",
    "AT",
    "AZ",
    "BY",
    "BA",
    "BG",
    "HR",
    "DK",
    "EE",
    "FI",
    "FR",
    "GE",
    "HU",
    "IS",
    "IT",
    "LV",
    "LT",
    "ME",
    "MK",
    "NO",
    "PL",
    "PT",
    "SI",
    "ES",
    "SE",
    "CH"
  ],
  "retrieved_note": "Wave 7 percentages from the official Results By Country PDF (weighted by w_weight). France never fielded WVS Wave 7 — its figures, like those of 25 other European countries that fielded only the EVS 2017 round (Italy, Spain, Poland, Sweden, …), are merged from the co-published Joint EVS/WVS 2017–2022 Results by Country PDF. A Joint table is used only where its figures for every Wave 7 society it shares reproduce that Wave 7 question exactly, which proves both the pairing and the column order. Wave 5 France is superseded and not used."
} as const;

export const WVS_THEME_ORDER = [
  "important-in-life",
  "child-qualities",
  "neighbors",
  "trust",
  "confidence",
  "democracy",
  "politics",
  "religion",
  "morals",
  "security",
  "migration",
  "economy",
  "science",
  "corruption",
  "happiness",
  "gender",
  "media",
  "other"
] as const;

export type WvsThemeId = (typeof WVS_THEME_ORDER)[number];
